// Stonewake's mobile interface. Bundled into the local game module.
const swElement = C.createElement;
const SWNavigationContext=C.createContext(null);
function SWAppFrame({navigate,...props}) { return swElement(SWNavigationContext.Provider,{value:navigate},swElement('main',props)); }
const SWNavigationItems=[['build','Build',N],['army','Army',we],['city','City',ne],['chronicle','Adventures',j]];
function SWQuickNav({navigate,current,state}) {
 const chapter=state&&typeof SWChapter==='function'?SWChapter(state):null,adventureReady=chapter?.missions.some(m=>m.status==='claimable');
 const raid=state&&typeof SWRaidStatus==='function'?SWRaidStatus(state,Date.now()):null,warning=raid&&['warning','ready'].includes(raid.phase),countdown=warning?(raid.phase==='ready'?'Raid ready':Qc(Math.max(0,raid.endsAt-Date.now())/1000)):null;
 return swElement('nav',{className:'sw-quick-nav','aria-label':'Quick navigation'},SWNavigationItems.map(([id,label,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),'aria-pressed':current===id,'aria-label':label+(id==='city'&&warning?', '+countdown:''),className:id==='city'&&warning?'has-raid-warning':id==='chronicle'&&adventureReady?'has-adventure-reward':''},swElement(Icon,{size:16}),swElement('span',null,label),id==='city'&&warning&&swElement('small',{className:'sw-city-nav-status'},countdown))));
}
function SWPanelSwitcher() {
 const navigate=C.useContext(SWNavigationContext),[open,setOpen]=C.useState(false);
 if(!navigate)return null;
 return swElement('span',{className:'sw-panel-switcher'},swElement('button',{type:'button','aria-label':'Switch panel','aria-expanded':open,onClick:()=>setOpen(!open)},swElement(ne,{size:16}),swElement(re,{size:12})),open&&swElement('nav',{'aria-label':'Switch to',className:'sw-panel-destinations'},[...SWNavigationItems,['frontier','Frontier',j],['fleet','Fleet',xe],['store','Store',M],['wardrobe','Customize',oe],['storage','Storage',A]].map(([id,label,Icon])=>swElement('button',{key:id,onClick:()=>{setOpen(false);navigate(id)}},swElement(Icon,{size:15}),label))));
}
function SWMainMenu({state,navigate,battle,sound,onSound,rewards}) {
 const items=[['capital','Capital',3],['town','Build',3],['army','Army',6],['chronicle','Adventures',0],['frontier','Frontier',2],['fleet','Fleet',1],['store','Store',4],['wardrobe','Customize',5],['achievements','Achievements',7]];
 return swElement('aside',{className:'kingdom-menu sw-main-menu sw-menu13','aria-label':'Kingdom navigation'},swElement('div',{className:'sw-menu-summary'},swElement('div',null,swElement('small',null,'YOUR REALM'),swElement('strong',null,state.name)),swElement('span',null,'Keep '+Ml(state)+' · '+zl(state)+' residents')),
 swElement('div',{className:'sw-menu-destinations13'},items.map(([id,name,art])=>swElement('button',{key:id,'aria-label':name,disabled:battle&&!['store','wardrobe','achievements'].includes(id),onClick:()=>navigate(id)},swElement(SWIllustration13,{index:art}),swElement('strong',null,name),id==='achievements'&&rewards>0&&swElement('small',{className:'sw-menu-count13'},rewards)))),
 swElement('nav',{className:'sw-menu-utilities13','aria-label':'Kingdom tools'},[['plan','Edit land',_e],['storage','Storage',A],['reports','Reports',ve],['settings','Settings',ye]].map(([id,name,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),disabled:battle&&id==='plan'},swElement(Icon,{size:16}),name))),swElement('button',{className:'sw-menu-sound','aria-pressed':sound,onClick:onSound},swElement(sound?Oe:ke,{size:16}),sound?'Sound on':'Sound off'));
}
function SWResourceBar({state,income,onStorage,onGems}) {
 const [pulse,setPulse]=C.useState(null),sequence=C.useRef(0),cap=typeof SWCapacity==='function'?SWCapacity(state):Fl(state);
 C.useEffect(()=>{let timer;const receive=e=>{clearTimeout(timer);setPulse({...e.detail,id:++sequence.current});timer=setTimeout(()=>setPulse(null),950)};window.addEventListener('stonewake-reward',receive);return()=>{clearTimeout(timer);window.removeEventListener('stonewake-reward',receive)}},[]);
 const brief=value=>value>=10000?(value/1000).toFixed(1)+'k':Math.floor(value).toLocaleString();
 return swElement(C.Fragment,null,swElement('div',{className:'resources sw-resource-bar'},xl.map(key=>{const Icon=Uu[key],amount=Math.floor(state.resources[key]),full=amount>=cap;return swElement('button',{key,className:'resource resource-'+key+(full?' sw-resource-full':''),onClick:onStorage,title:Wu[key]+' · '+amount.toLocaleString()+' / '+cap.toLocaleString()+' · +'+Math.round(income[key])+'/min','aria-label':Wu[key]+', '+amount+' of '+cap+(full?', storage full':'')},swElement(Icon,{size:16}),swElement('div',null,swElement('strong',null,swElement(Ru,{value:amount,duration:420})),swElement('small',null,'/ '+brief(cap))),swElement('progress',{'aria-hidden':true,max:cap,value:Math.min(amount,cap)}),pulse?.reward?.[key]>0&&swElement('span',{className:'sw-resource-gain',key:pulse.id},'+'+pulse.reward[key]));})),
  swElement('button',{className:'sw-gem-wallet','aria-label':'Gems, '+state.gems+' available',onClick:onGems},swElement('span',null,'◆'),swElement(Ru,{value:state.gems,duration:420}),pulse?.gems>0&&swElement('span',{className:'sw-resource-gain',key:pulse.id},'+'+pulse.gems)));
}
function SWBuildCard({kind,state,busy,onBuild}) {
 const type=Sl[kind],keep=Ml(state),limit=typeof SWBuildingLimit==='function'?SWBuildingLimit(state,kind):Infinity,count=typeof SWBuildingCount==='function'?SWBuildingCount(state,kind):state.buildings.filter(b=>b.kind===kind).length,cost=X(kind);
 let next=keep+1;while(next<=10&&typeof SWBuildingLimit==='function'&&SWBuildingLimit({...state,buildings:state.buildings.map(b=>b.kind==='keep'?{...b,level:next}:b)},kind)<=count)next++;
 const reason=keep<type.unlock?'Requires Keep '+type.unlock:kind==='monument'&&!state.cosmetics?.includes('monument')?'League reward required':count>=limit?(next<=10?'More at Keep '+next:'Building limit reached'):Rc(state)<1?'All builders busy':!Z(state,cost)?'More resources needed':null;
 return swElement('button',{className:'build-card sw-build-card'+(reason?' locked':''),disabled:busy||!!reason,onClick:()=>onBuild(kind),'aria-label':type.name+', '+count+' of '+(Number.isFinite(limit)?limit:'unlimited')+(reason?', '+reason:'')},swElement(qu,{kind}),swElement('strong',null,type.name),swElement('span',{className:'sw-build-count'},count+' / '+(Number.isFinite(limit)?limit:'∞')),swElement('span',{className:'build-benefit'},Bl({kind,level:1})),swElement(Ku,{cost,available:state.resources}),swElement('span',{className:'build-time'},reason||'Build · '+Qc(Zc(state,kind))));
}
function SWStorage({open,onClose,state,onBuilding,onBuild,act,busy}) {
 const cap=typeof SWCapacity==='function'?SWCapacity(state):Fl(state),reserve=state.reserveCrates||{},hasReserve=xl.some(k=>reserve[k]>0),space=xl.some(k=>reserve[k]>0&&state.resources[k]<cap),stores=state.buildings.filter(b=>b.kind==='storehouse'),limit=typeof SWBuildingLimit==='function'?SWBuildingLimit(state,'storehouse'):Infinity,buildReason=stores.length>=limit?'Storehouse limit reached':Rc(state)<1?'All builders busy':!Z(state,X('storehouse'))?'More resources needed':null;
 return swElement(SWDialog,{open,onClose,title:'Storage',subtitle:'Space for every resource',className:'sw-storage'},
  swElement('div',{className:'sw-storage-overview'},swElement('div',{className:'sw-storage-grid'},xl.map(key=>{const Icon=Uu[key],amount=Math.floor(state.resources[key]),full=amount>=cap;return swElement('section',{key,className:'sw-storage-resource'+(full?' full':'')},swElement('div',null,swElement(Icon,{size:17}),swElement('strong',null,Wu[key]),swElement('span',null,full?'Full':Math.round(amount/cap*100)+'%')),swElement('p',null,amount.toLocaleString(),swElement('span',null,' / '+cap.toLocaleString())),swElement('progress',{'aria-label':Wu[key]+' storage',max:cap,value:Math.min(amount,cap)}));})),
   hasReserve&&swElement('section',{className:'sw-reserve-crates'},swElement('strong',null,'Saved supplies'),swElement('p',null,'Earlier supplies stay safe here until there is room.'),swElement(Ku,{cost:reserve}),swElement('button',{className:'primary wide',disabled:busy||!space,onClick:()=>act({type:'claimReserve'},'Supplies moved into storage')},space?'Claim what fits':'Storage full'))),
  swElement('section',{className:'sw-storage-expansion'},swElement('div',{className:'sw-storage-heading'},swElement('h3',null,'Storehouses'),swElement('span',null,stores.length+' / '+(Number.isFinite(limit)?limit:'∞'))),
   stores.length?swElement('div',{className:'sw-storage-buildings'},stores.map(building=>swElement('button',{key:building.id,className:'secondary',onClick:()=>onBuilding(building.id)},swElement(qu,{kind:'storehouse',level:building.level}),swElement('span',null,'Storehouse · Level '+building.level,swElement('small',null,building.readyAt?'Upgrade in progress':SWUpgradeQuote14(state,building).reason||'Upgrade for more capacity')),swElement(re,{size:17})))):swElement('p',{className:'sw-muted'},'Build a storehouse to make room for income and battle rewards.'),
   swElement('button',{className:'secondary wide',disabled:busy||!!buildReason,onClick:onBuild},buildReason||'Build storehouse'),swElement('p',{className:'sw-storage-note'},'Full resources stop accumulating. Spend supplies or expand storage before collecting more.')));
}
function GemCost(readyAt, now = Date.now()) { return Math.max(1, Math.ceil(Math.max(0, readyAt - now) / 60000)); }
function GemProjects(state) {
  const seen = new Set(), projects = [];
  for (const building of state.buildings) {
    if (!building.readyAt) continue;
    const key = building.projectId || building.id;
    if (seen.has(key)) continue;
    seen.add(key);
    projects.push({ target: 'building', id: building.id, name: Sl[building.kind].name, readyAt: building.readyAt });
  }
  if (state.trainingResearch) projects.push({target:'research',id:state.trainingResearch.kind,name:J[state.trainingResearch.kind].name+' research',readyAt:state.trainingResearch.readyAt});
  for(const ship of state.fleet || []) if(ship.readyAt) projects.push({target:'ship',id:ship.id,name:wc[ship.kind].name,readyAt:ship.readyAt});
  return projects;
}
function ApplyGemAction(state, action, now) {
  if(action.type !== 'speedup') return false;
  if(!['building','research','ship'].includes(action.target) || typeof action.id !== 'string') throw Error('Choose an active project.');
  const project = GemProjects(state).find(p=>p.target===action.target && p.id===action.id);
  if(!project || project.readyAt<=now) throw Error('This project is already complete.');
  const cost=GemCost(project.readyAt,now);
  if(!Number.isInteger(action.maxCost) || action.maxCost<cost) throw Error('Review the current gem cost.');
  if(state.gems<cost) throw Error('Not enough gems. Earn more from objectives and first victories.');
  state.gems-=cost;
  if(action.target==='building') {
    const selected=state.buildings.find(b=>b.id===action.id);
    for(const b of state.buildings) if(b.id===selected.id || (selected.projectId && b.projectId===selected.projectId)) b.readyAt=now;
  } else if(action.target==='ship') state.fleet.find(s=>s.id===action.id).readyAt=now;
  else state.trainingResearch.readyAt=now;
  return true;
}
function SWDialog({open,onClose,title,subtitle,className='',children}) {
 return swElement(As,{open,onOpenChange:v=>{if(!v)onClose()}},open&&swElement(Ns,{className:'game-dialog sw-dialog '+className},
  swElement(Ps,null,swElement('div',{className:'sw-dialog-title-row'},swElement(Fs,null,title),swElement(SWPanelSwitcher)),swElement(Is,{className:subtitle?'':'sr-only'},subtitle||title)),swElement('div',{className:'sw-body'},children)));
}
function SWObjectives({open,onClose,state,act,busy,onAction,onFrontier}) {
 const navigate=C.useContext(SWNavigationContext),quest=Rl(state),ready=quest?.check(state),progress=quest?kl(state,quest.id):null,canReceive=!quest||typeof SWCanReceive!=='function'||SWCanReceive(state,quest.reward);
 return swElement(SWDialog,{open,onClose,title:quest?'Objectives':'A realm of your own',subtitle:quest?'Chapter '+(state.quests.length+1)+' of '+El.length:'Your founding chapters are complete.',className:'sw-objectives'},
  quest?swElement('section',{className:'sw-objective-card'},swElement('h3',null,quest.title),swElement('p',null,quest.text),
   progress&&swElement('div',{className:'sw-objective-progress'},swElement('span',null,ready?'Ready to collect':progress.value+' / '+progress.target),swElement('progress',{max:progress.target,value:progress.value})),
   swElement('div',{className:'sw-objective-reward'},swElement(Ku,{cost:quest.reward}),swElement('strong',null,'+8 ◆')),
   swElement('button',{className:'primary wide',disabled:busy||(ready&&!canReceive),onClick:()=>ready?act({type:'claim',id:quest.id}):onAction(quest.id)},ready&&!canReceive?'Make room in storage':ready?'Collect rewards':quest.id==='army'?'Recruit troops':quest.id==='age2'?'View keep':['quarry','barracks','forge'].includes(quest.id)?'Place building':'Explore frontier'),ready&&!canReceive&&swElement('button',{className:'secondary wide',onClick:()=>navigate?.('storage')},'Manage storage')):
   swElement('section',{className:'sw-objective-card'},swElement(oe,{size:28}),swElement('p',null,'Your capital is established. Develop your city, conquer provinces, and advance through the campaign.'),swElement('button',{className:'primary wide',onClick:onFrontier},'Explore the frontier')),
  swElement('details',{className:'sw-completed-chapters'},swElement('summary',null,state.quests.length+' chapters completed'),swElement('ol',null,El.filter(q=>state.quests.includes(q.id)).map(q=>swElement('li',{key:q.id},swElement(O,{size:14}),q.title)))));
}
function SWAbilitySummary({kind,level}) {
 const milestones=typeof SWTroopAbilities==='function'?SWTroopAbilities(kind):[],current=milestones.filter(a=>a.level<=level).at(-1),next=milestones.find(a=>a.level>level);
 if(!current&&!next)return null;
 return swElement('details',{className:'sw-ability-progress'},swElement('summary',null,
  swElement('span',null,current?'Active: '+current.name:'Next: '+next.name),swElement('small',null,current?(next?'Next at Lv '+next.level:'All abilities unlocked'):'Unlocks at Lv '+next.level)),
  current&&swElement('p',null,current.description),next&&swElement('p',null,swElement('strong',null,'Level '+next.level+' · '+next.name),swElement('br'),next.description));
}
function SWLandTools({tool,onTool,onClose,state,onBuildings}) {
 const icons={clear:Se,road:_e,tree:Te,rock:fe,garden:le},names={clear:'Clear',road:'Road',tree:'Tree',rock:'Rock',garden:'Garden'};
 const stats=state&&typeof SWLandStats==='function'?SWLandStats(state):null;
 return swElement('aside',{className:'landscape-panel panel sw-land-tools','aria-label':'Land editor'},
  swElement('div',{className:'tray-heading'},swElement('strong',null,'Plan city'),swElement('button',{className:'sw-plan-buildings',onClick:onBuildings},'Move & rotate'),swElement('button',{className:'icon-btn','aria-label':'Close landscape tools',onClick:onClose},swElement(je,{size:18}))),
  swElement('div',{className:'landscape-tools'},Object.keys(Tc).map(kind=>swElement('button',{key:kind,'aria-pressed':tool===kind,onClick:()=>onTool(kind)},swElement(icons[kind],{size:19}),names[kind]))),
  swElement('div',{className:'sw-land-feedback',role:'status'},swElement('span',null,swElement('strong',null,Tc[tool].name+'. '),tool==='clear'?'Tap a tree, rock or decoration to remove it.':tool==='road'?'Connect production buildings to the Keep for +10% income.':tool==='garden'?'Gardens near homes improve gold income.':'Tap empty land. The tool stays selected.'),swElement(Ku,{cost:Tc[tool].cost})),stats&&swElement('small',{className:'sw-plan-stats'},stats.connectedCount+' connected buildings · '+stats.gardenCount+' gardens'));
}
function SWRaidSummary({state,onReview,compact=false}) {
 const now=Date.now(),raid=typeof SWRaidStatus==='function'?SWRaidStatus(state,now):{phase:'peace',wave:1},remaining=Math.max(0,(raid.endsAt||0)-now),warning=['warning','ready'].includes(raid.phase);
 const title=raid.phase==='protected'?'Your city is protected':raid.phase==='warning'?'Raiders approaching':raid.phase==='ready'?'Raiders at the coast':raid.phase==='active'?'Defending the city':'Peace in the valley';
 const detail=raid.phase==='protected'?'Protection ends in '+Qc(remaining/1000):raid.phase==='warning'?'Wave '+raid.wave+' arrives in '+Qc(remaining/1000):raid.phase==='ready'?'Review your defenses and exposed stores.':raid.phase==='active'?'Your walls and towers are holding the line.':'Raids begin at Keep 3. Build defenses while the town grows.';
 return swElement('section',{className:'sw-raid-summary'+(warning?' warning':'')+(compact?' compact':''),'aria-label':'City defense status'},swElement(be,{size:22}),swElement('div',null,swElement('strong',null,title),swElement('span',null,detail)),onReview&&swElement('button',{className:'secondary',onClick:onReview},warning?'Review':'Defense'));
}
function SWDefenseReportSummary({report,compact=false}) {
 if(!report)return null;
 const metrics=[['Walls absorbed',report.wallDamageAbsorbed,' damage'],['Wall delay',report.wallDelaySeconds,'s'],['Tower damage',report.towerDamage,''],['Raiders defeated',report.attackersDefeated,'']].filter(([,value])=>Number.isFinite(value));
 return swElement('section',{className:'sw-defense-report'+(compact?' compact':'')},!compact&&swElement('div',{className:'sw-defense-report-heading'},swElement('strong',null,report.won?'The city held':'The keep was breached'),Number.isFinite(report.duration)&&swElement('span',null,Math.round(report.duration)+'s')),
  metrics.length>0&&swElement('div',{className:'sw-defense-metrics'},metrics.map(([label,value,suffix])=>swElement('span',{key:label},swElement('strong',null,Math.round(value).toLocaleString()+suffix),label))),
  !compact&&report.loot&&xl.some(k=>report.loot[k]>0)&&swElement('div',{className:'sw-defense-receipt lost'},swElement('span',null,'Supplies lost'),swElement(Ku,{cost:report.loot})),
  !compact&&report.reward&&xl.some(k=>report.reward[k]>0)&&swElement('div',{className:'sw-defense-receipt'},swElement('span',null,'Bounty received'),swElement(Ku,{cost:report.reward})),
  report.lootProtected&&swElement('p',{className:'sw-muted'},typeof report.lootProtected==='number'?Math.round(report.lootProtected).toLocaleString()+' of each resource stayed protected.':'Protected stores remained safe.'));
}
function SWCivicProjectCard({project,state,act,busy,onBuilding,onBuild,onResidents}) {
 const navigate=C.useContext(SWNavigationContext),[expanded,setExpanded]=C.useState(false),requirementsRef=C.useRef(null);
 C.useEffect(()=>{if(expanded)requirementsRef.current?.scrollIntoView({block:'nearest'})},[expanded]);
 const requirementAction=requirement=>{if(requirement.action==='residents')onResidents();else if(requirement.action==='plan'||requirement.action==='fleet')navigate(requirement.action);else if(requirement.action==='build')onBuild(requirement.buildKind);else{const existing=state.buildings.filter(b=>b.kind===requirement.buildKind).sort((a,b)=>b.level-a.level)[0];existing?onBuilding(existing.id):onBuild(requirement.buildKind)}};
 const stage=Math.min(3,Math.max(0,project.stage||0)),building=state.buildings.find(b=>b.id===project.siteId)||state.buildings.find(b=>b.kind===project.anchorKind&&b.level>0),now=Date.now(),working=project.status==='building',claimable=project.status==='claimable',complete=project.status==='complete',missing=project.requirements?.filter(r=>!r.met)||[],affordable=Z(state,project.cost||{});
 const primary=claimable?'Celebrate · +'+(project.gemReward||0)+' gems':working?'Building · '+Qc(Math.max(0,(project.readyAt-now)/1000)):complete?'District complete':project.status==='locked'?'View requirements':project.reason||!affordable?project.reason||'More resources needed':'Start '+(project.nextName||'stage '+(stage+1));
 return swElement('article',{className:'sw-civic-project','data-project':project.id},swElement('div',{className:'sw-civic-heading'},swElement(qu,{kind:project.anchorKind,level:Math.max(1,building?.level||1)}),swElement('div',null,swElement('h3',null,project.name),swElement('span',null,'Stage '+stage+' / 3'))),
  swElement('div',{className:'sw-civic-stages','aria-label':stage+' of 3 stages complete'},[1,2,3].map(n=>swElement('span',{key:n,className:n<=stage?'done':n===(project.targetStage||stage+1)&&working?'working':''}))),
  swElement('p',{className:'sw-civic-benefit'},complete||claimable?project.benefit:project.nextBenefit||project.description),
  working&&swElement('progress',{'aria-label':project.name+' construction',max:Math.max(1,project.readyAt-project.startedAt),value:Math.max(0,now-project.startedAt)}),
  !complete&&!working&&!claimable&&swElement(Ku,{cost:project.cost||{},available:state.resources}),
  !complete&&swElement('button',{className:claimable?'primary':'secondary',disabled:busy||working||(!claimable&&project.status!=='locked'&&(project.status!=='available'||!!project.reason||!affordable)),'aria-expanded':project.status==='locked'?expanded:undefined,onClick:()=>project.status==='locked'?setExpanded(!expanded):act({type:claimable?'claimCivicProject':'startCivicProject',id:project.id},claimable?'District celebration':'District work started')},primary),
  missing.length>0&&swElement('details',{className:'sw-civic-requirements',ref:requirementsRef,open:expanded,onToggle:event=>setExpanded(event.currentTarget.open)},swElement('summary',null,project.reason||missing.length+' requirements'),project.requirements.map((requirement,index)=>swElement('div',{key:index},swElement(requirement.met?O:be,{size:14}),swElement('span',null,requirement.label),!requirement.met&&(requirement.action||requirement.buildKind)&&swElement('button',{className:'text-button',onClick:()=>requirementAction(requirement)},requirement.action==='plan'?'Plan city':requirement.action==='residents'?'Requests':requirement.action==='fleet'?'Fleet':requirement.action==='build'?'Build':'View')))),
  building&&swElement('button',{className:'sw-civic-anchor',onClick:()=>onBuilding(building.id)},'View '+Sl[project.anchorKind].name.toLowerCase(),swElement(re,{size:14})));
}
function SWCityResidents({state,act,busy,onBuild,navigate}) {
 const city=SWCity(state),now=Date.now(),craft=city.craft&&SWCityRecipes[city.craft.kind],workshop=SWCivicLevel(state,'workshop'),tavern=SWCivicLevel(state,'tavern');
 return swElement('div',{className:'sw-city-stack sw-resident-stack'},
  swElement('section',{className:'sw-city-card sw-resident-story-link'},swElement('span',{className:'sw-eyebrow'},'People of the coast'),swElement('h3',null,'Give your residents a story'),swElement('p',{className:'sw-muted'},'Help Mara’s watch, rebuild the waterfront, and welcome the beacon crew. Your choices leave lasting rewards.'),swElement('button',{className:'primary',onClick:()=>navigate('residents')},'Meet your residents')),
  swElement('div',{className:'sw-city-summary'},city.jobs+' requests fulfilled · '+city.crafted+' goods crafted',swElement('small',null,'Every fifth request earns 3 gems.')),
  [0,1,2].map(slot=>{const task=SWCityRequest(state,slot),wait=Math.max(0,task.readyAt-now),room=SWCanReceive(state,task.reward,task.cost);return swElement('section',{className:'sw-city-card',key:slot},swElement('h3',null,task.name),swElement('p',{className:'sw-muted'},task.text),swElement('div',{className:'sw-city-exchange'},swElement('span',null,'Spend'),swElement(Ku,{cost:task.cost,available:state.resources}),swElement('span',null,'Receive'),swElement(Ku,{cost:task.reward})),swElement('button',{className:'primary',disabled:busy||wait>0||!Z(state,task.cost)||!room,onClick:()=>act({type:'cityRequest',slot,id:task.id},'Residents supplied')},wait?'New request in '+Qc(wait/1000):!room?'Make room in storage':'Deliver supplies'),!room&&swElement('button',{className:'text-button',onClick:()=>navigate('storage')},'Manage storage'));}),
  swElement('section',{className:'sw-city-card'},swElement('h3',null,'Artisan orders'),!workshop?swElement(C.Fragment,null,swElement('p',{className:'sw-muted'},'Turn spare timber into stone and trade goods.'),swElement('button',{className:'secondary',onClick:()=>onBuild('workshop')},'Build workshop')):craft?swElement(C.Fragment,null,swElement('strong',null,craft.name),swElement(Ku,{cost:craft.reward}),swElement('button',{className:'primary',disabled:busy||city.craft.readyAt>now||!SWCanReceive(state,craft.reward),onClick:()=>act({type:'collectCraft'},'Crafting complete')},city.craft.readyAt>now?'Ready in '+Qc((city.craft.readyAt-now)/1000):!SWCanReceive(state,craft.reward)?'Make room in storage':'Collect crafted goods'),!SWCanReceive(state,craft.reward)&&swElement('button',{className:'text-button',onClick:()=>navigate('storage')},'Manage storage')):Object.entries(SWCityRecipes).map(([id,recipe])=>swElement('div',{className:'sw-city-recipe',key:id},swElement('strong',null,recipe.name),swElement('div',{className:'sw-city-exchange'},swElement('span',null,'Spend'),swElement(Ku,{cost:recipe.cost,available:state.resources}),swElement('span',null,'Receive'),swElement(Ku,{cost:recipe.reward})),swElement('button',{className:'secondary',disabled:busy||!Z(state,recipe.cost),onClick:()=>act({type:'startCraft',kind:id},'Artisans are at work')},'Craft · '+Qc(Math.max(20,recipe.duration-workshop*3)))))),
  swElement('section',{className:'sw-city-card'},swElement('h3',null,'Town festival'),swElement('p',{className:'sw-muted'},city.festivalUntil>now?'Your festival is active. Resource income is 15% higher.':'Bring your residents together for +15% resource income.'),swElement(Ku,{cost:{gold:60,wood:0,stone:0,food:180},available:state.resources}),swElement('button',{className:'secondary',disabled:busy||!!tavern&&((city.festivalReadyAt||0)>now||!Z(state,{gold:60,wood:0,stone:0,food:180})),onClick:()=>tavern?act({type:'festival'},'The festival has begun'):onBuild('tavern')},!tavern?'Build tavern':city.festivalReadyAt>now?'Next festival in '+Qc((city.festivalReadyAt-now)/1000):'Host festival')));
}
function SWCityHub({open,onClose,state,act,busy,onBuild,onDefense,onBuilding,reports=[],onlineMode=false}) {
 const [tab,setTab]=C.useState('Overview'),navigate=C.useContext(SWNavigationContext),city=SWCity(state),now=Date.now();
 C.useEffect(()=>{if(open)setTab('Overview')},[open]);
 const projects=typeof SWCivicProjects!=='undefined'?SWCivicProjects.map(def=>SWCivicProject(state,def.id,now)):[],next=projects.find(p=>p.status==='claimable')||projects.find(p=>p.status==='building')||projects.find(p=>p.status==='available')||projects.find(p=>p.status!=='complete'),raid=typeof SWRaidStatus==='function'?SWRaidStatus(state,now):{phase:'peace',wave:1},latestReport=city.lastDefense||reports.find(report=>report.defenseReport)?.defenseReport;
 const capacity=SWCapacity(state),full=xl.filter(k=>state.resources[k]>=capacity),land=SWLandStats(state),quest=Rl(state),canDefend=Ml(state)>=3&&!state.activeBattle&&(onlineMode?raid.phase==='ready':(city.raidReadyAt||0)<=now);
 return swElement(SWDialog,{open,onClose,title:state.name,subtitle:'Your city',className:'sw-city-dialog sw-city-hub'},
  swElement('nav',{className:'sw-tabs','aria-label':'City sections'},['Overview','Projects','Residents','Defense'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,className:tab===name?'selected':'',onClick:()=>setTab(name)},name))),
  tab==='Overview'&&swElement('div',{className:'sw-city-stack sw-city-overview'},
   swElement(SWRaidSummary,{state,onReview:()=>setTab('Defense'),compact:true}),
   swElement('section',{className:'sw-city-card sw-city-next'},swElement('span',{className:'sw-eyebrow'},'Next city goal'),swElement('h3',null,next?.name||'A thriving kingdom'),swElement('p',{className:'sw-muted'},next?next.status==='claimable'?'The district is ready. Celebrate and collect your gems.':next.status==='building'?'Work is underway. Your district will unlock permanent benefits.':next.nextBenefit||next.description:'Your districts are complete. Keep the city supplied and strengthen its defenses.'),swElement('button',{className:'primary',onClick:()=>setTab(next?'Projects':'Residents')},next?.status==='claimable'?'Celebrate district':next?'View project':'Help residents')),
   swElement('section',{className:'sw-city-card'},swElement('h3',null,full.length?'Make room for your rewards':'Keep the city supplied'),swElement('p',{className:'sw-muted'},full.length?full.map(k=>Wu[k]).join(', ')+' storage is full. Spend supplies or improve your stores.':zl(state)+' residents · '+city.jobs+' requests fulfilled. Deliver supplies, craft goods, and host a festival.'),swElement('button',{className:'secondary',onClick:()=>full.length?navigate('storage'):setTab('Residents')},full.length?'Manage storage':'Resident requests')),
   swElement('section',{className:'sw-city-card'},swElement('h3',null,'Plan the neighborhood'),swElement('p',{className:'sw-muted'},land.connectedCount+' buildings linked by roads. Gardens add '+Math.round(land.gardenBonus*100)+'% gold income. Connect productive buildings to the Keep.'),swElement('button',{className:'secondary',onClick:()=>navigate('plan')},'Plan city')),
   quest&&swElement('button',{className:'sw-city-objective',onClick:()=>navigate('objectives')},swElement(j,{size:18}),swElement('span',null,'Founding objective',swElement('strong',null,quest.title)),swElement(re,{size:16}))),
  tab==='Projects'&&swElement('div',{className:'sw-city-stack sw-civic-grid'},projects.map(project=>swElement(SWCivicProjectCard,{key:project.id,project,state,act,busy,onBuilding,onBuild,onResidents:()=>setTab('Residents')}))),
  tab==='Residents'&&swElement(SWCityResidents,{state,act,busy,onBuild,navigate}),
  tab==='Defense'&&swElement('div',{className:'sw-city-stack sw-city-defense'},swElement(SWRaidSummary,{state}),
   swElement('section',{className:'sw-city-card sw-defense-preparation'},swElement('h3',null,'Prepare for wave '+raid.wave),swElement('p',{className:'sw-defense-layout-count'},state.buildings.filter(b=>zc(b)&&b.level).length+' wall segments · '+state.buildings.filter(b=>Cc.includes(b.kind)&&b.level).length+' defenses'),raid.lootRisk&&swElement('div',{className:'sw-defense-receipt lost'},swElement('span',null,'At risk'),swElement(Ku,{cost:raid.lootRisk})),swElement('div',{className:'sw-city-actions'},swElement('button',{className:'primary',disabled:busy||!canDefend,onClick:onDefense},state.activeBattle?'Battle in progress':Ml(state)<3?'Requires Keep 3':onlineMode?(canDefend?'Resolve raid':'Scheduled defense'):!canDefend?'Scouts return in '+Qc(((city.raidReadyAt||0)-now)/1000):'Defend now'),swElement('button',{className:'secondary',onClick:()=>onBuild('tower')},'Build defenses')),swElement('details',{className:'sw-defense-rules'},swElement('summary',null,'How raids work'),swElement('p',{className:'sw-muted'},'Walls buy time and towers damage raiders. 20% of storage capacity stays protected. Buildings recover afterward; your home army stays safe. Raids can resolve while you are away. Each raid is followed by two hours of protection.'))),
   latestReport?swElement(SWDefenseReportSummary,{report:latestReport}):swElement('section',{className:'sw-city-card'},swElement('h3',null,'Your defense report'),swElement('p',{className:'sw-muted'},'After a raid, review the damage your walls absorbed, the time they bought, and the damage dealt by your towers.')),
   swElement('button',{className:'secondary sw-city-reports',onClick:()=>navigate('reports')},'All battle reports')));
}
function SWUseOnline() {
 const snapshot=()=>window.SWOnline?.state()||{configured:false,signedIn:false,busy:false,products:[],message:'Online services are not connected yet. Your kingdom stays on this iPhone.'};
 const [online,setOnline]=C.useState(snapshot);
 C.useEffect(()=>{const update=event=>setOnline(event.detail||snapshot());window.addEventListener('stonewake-online-status',update);setOnline(snapshot());return()=>window.removeEventListener('stonewake-online-status',update)},[]);
 return online;
}
function SWAccountPanel({onBackup,onRestoreBackup,onEnterOnline,onReturnLocal,onlineMode=false,onlineBattle=false}) {
 const online=SWUseOnline(),[working,setWorking]=C.useState(false),[message,setMessage]=C.useState(''),[confirm,setConfirm]=C.useState(null),confirmRef=C.useRef(null),busy=working||online.busy;
 C.useEffect(()=>{if(confirm)confirmRef.current?.scrollIntoView({block:'nearest'})},[confirm]);
 const run=async(action,success)=>{setWorking(true);setMessage('');try{await action();setMessage(success||'');setConfirm(null)}catch(error){setMessage(error.message||'This action could not be completed. Your kingdom is unchanged.')}finally{setWorking(false)}};
 if(!online.configured)return swElement('section',{className:'sw-account-card'},swElement('h3',null,onlineMode?'Your local kingdom is safe':'Your kingdom is on this iPhone'),swElement('p',null,online.message||'Online services are not connected yet.'),swElement('p',{className:'sw-muted'},onlineMode?'Return to your local kingdom while the service is unavailable. Unconfirmed online battle orders may not reach the service.':'Account sign-in, cloud backup, online kingdoms, and purchases appear here when the service is connected. Your local game remains playable.'),onlineMode&&swElement('button',{className:'primary',onClick:()=>run(onReturnLocal,'Returned to your local kingdom.')},'Return to local kingdom'));
 return swElement('div',{className:'sw-account-panel'},
  swElement('section',{className:'sw-account-card'},swElement('h3',null,online.signedIn?'Apple account connected':'Keep your kingdom safe'),swElement('p',null,online.signedIn?(onlineMode?'You are playing your Online Kingdom.':'You are playing the kingdom saved on this iPhone.'):'Sign in with Apple to create a cloud backup and access your separate Online Kingdom.'),
   !online.signedIn?swElement('button',{className:'primary',disabled:busy,onClick:()=>run(()=>window.SWOnline.call('signIn'),'Account connected.')},busy?'Connecting…':'Sign in with Apple'):
   swElement('button',{className:'secondary',disabled:busy||onlineMode,onClick:()=>run(()=>window.SWOnline.call('signOut'),'Signed out. Your local kingdom is kept.')},onlineMode?'Return to local before signing out':'Sign out')),
  online.signedIn&&swElement('section',{className:'sw-account-card'},swElement('h3',null,'Cloud backup'),swElement('p',null,online.backup?'Last backup '+new Date(online.backup.updatedAt).toLocaleString():'No cloud backup yet. Back up your current local kingdom before changing devices.'),swElement('div',{className:'sw-account-actions'},swElement('button',{className:'secondary',disabled:busy||onlineMode||!onBackup,onClick:()=>run(onBackup,'Cloud backup saved.')},'Back up local kingdom'),swElement('button',{className:'secondary',disabled:busy||onlineMode||!online.backup||!onRestoreBackup,onClick:()=>setConfirm('restore')},'Restore backup'))),
  (online.signedIn||onlineMode)&&swElement('section',{className:'sw-account-card'},swElement('h3',null,'Online Kingdom'),swElement('p',null,onlineMode?(onlineBattle?'Your online battle continues while you are away. Unconfirmed orders may not reach the service. Re-enter to resume the saved battle. Your local kingdom is kept separately.':'Your online balance and battles are verified by the game service. Your local kingdom is kept separately.'):'Start a separate kingdom for player battles and verified purchases. Your current kingdom stays on this iPhone.'),swElement('button',{className:'primary',disabled:onlineMode?!onReturnLocal:busy||!onEnterOnline,onClick:()=>onlineMode?run(onReturnLocal,'Returned to your local kingdom.'):setConfirm('online')},onlineMode?'Return to local kingdom':'Enter Online Kingdom')),
  confirm&&swElement('section',{className:'sw-account-confirm',ref:confirmRef,role:'group','aria-label':confirm==='restore'?'Confirm cloud restore':'Confirm Online Kingdom'},swElement('h3',null,confirm==='restore'?'Use your cloud backup?':'Enter a separate kingdom?'),swElement('p',null,confirm==='restore'?'Your current local kingdom will be archived before the backup is restored. This switches the local progress you are playing.':'Online Kingdom starts separately. Your current kingdom is kept. Purchases apply only to your online balance.'),swElement('div',{className:'sw-account-actions'},swElement('button',{className:'secondary',disabled:busy,onClick:()=>setConfirm(null)},'Cancel'),swElement('button',{className:'primary',disabled:busy,onClick:()=>run(confirm==='restore'?onRestoreBackup:onEnterOnline,confirm==='restore'?'Backup restored.':'Online Kingdom opened.')},confirm==='restore'?'Restore this backup':'Enter Online Kingdom'))),
  message&&swElement('p',{className:'sw-account-message',role:'status'},message));
}
function SWGemStore({onlineMode=false,onOnlineGame}) {
 const online=SWUseOnline(),navigate=C.useContext(SWNavigationContext),[working,setWorking]=C.useState(false),[message,setMessage]=C.useState('');
 C.useEffect(()=>{if(online.configured&&online.signedIn&&onlineMode)window.SWOnline.call('products').catch(error=>setMessage(error.message))},[online.configured,online.signedIn,onlineMode]);
 const run=async(method,payload)=>{setWorking(true);setMessage('');try{const result=await window.SWOnline.call(method,payload);if(result.game&&onOnlineGame)await onOnlineGame(result.game);setMessage(result.status==='pending'?'Purchase pending. Gems appear after Apple and the game service confirm it.':result.status==='cancelled'?'Purchase cancelled. No gems were added.':result.status==='granted'?'Purchase verified. Your online balance is updated.':'Purchase check complete. Only verified purchases are credited.')}catch(error){setMessage(error.message||'The purchase could not be completed. No gems were added.')}finally{setWorking(false)}};
 return swElement('section',{className:'sw-gem-store'},swElement('h3',null,'Gem shop'),
  !online.configured?swElement('p',{className:'sw-muted'},'Purchases are unavailable while online services are not connected. You can still earn gems by playing.'):
  !online.signedIn||!onlineMode?swElement(C.Fragment,null,swElement('p',{className:'sw-muted'},'Purchased gems belong to your separate Online Kingdom. Your local kingdom and its earned gems stay here.'),swElement('button',{className:'secondary',onClick:()=>navigate('account')},'Open Account')):
  swElement(C.Fragment,null,swElement('div',{className:'sw-gem-products'},online.products?.length?online.products.map(product=>swElement('button',{className:'secondary',key:product.id,disabled:working||online.busy||!onOnlineGame,onClick:()=>run('purchase',{productId:product.id})},swElement('span',{className:'sw-gem-product-title'},swElement('strong',null,Number(product.gems).toLocaleString()+' gems'),swElement('small',null,product.name)),swElement('strong',null,product.displayPrice))):swElement('p',{className:'sw-muted'},'No gem packs are available from the App Store right now.')),swElement('button',{className:'text-button',disabled:working||online.busy,onClick:()=>run('restorePurchases')},'Check pending purchases'),swElement('p',{className:'sw-muted'},'Apple shows the final price and confirmation before any charge.')),
  message&&swElement('p',{className:'sw-account-message',role:'status'},message));
}
function SWOnlineFrontierGate() {
 const online=SWUseOnline(),navigate=C.useContext(SWNavigationContext);
 return swElement('section',{className:'rivals-surface sw-online-frontier'},swElement('div',{className:'sw-account-card'},swElement(De,{size:28}),swElement('h2',null,'Player kingdoms'),swElement('p',null,online.configured?'Challenge saved player defenses in your separate Online Kingdom. Your current local city stays safe.':'Player battles need a connected online service. Campaigns, provinces, and computer raids are ready to play on this iPhone.'),swElement('button',{className:'primary',onClick:()=>navigate('account')},online.configured?'Open Account':'View online availability')),swElement('div',{className:'sw-online-features'},swElement('span',null,swElement(be,{size:18}),'Publish your saved defenses'),swElement('span',null,swElement(we,{size:18}),'Scout player kingdoms'),swElement('span',null,swElement(ve,{size:18}),'Review shared battle replays')));
}
function SWSettings(props) {
 const [tab,setTab]=C.useState(props.initialTab||'Audio');
 C.useEffect(()=>{if(props.open)setTab(props.initialTab||'Audio')},[props.open,props.initialTab]);
 const range=(label,value,set)=>swElement('label',{className:'sw-slider'},swElement('span',null,label,swElement('strong',null,Math.round(value*100)+'%')),swElement('input',{'aria-label':label,type:'range',min:0,max:100,value:Math.round(value*100),onChange:e=>set(Number(e.target.value)/100)}));
 const toggle=(label,value,set)=>swElement('div',{className:'sw-setting'},swElement('span',null,label),swElement('button',{'aria-label':label,'aria-pressed':value,className:'sw-toggle',onClick:set},value?'On':'Off'));
 return swElement(SWDialog,{open:props.open,onClose:props.onClose,title:'Settings',subtitle:'Tune your kingdom.',className:'sw-settings'},
  swElement('nav',{className:'sw-tabs','aria-label':'Settings sections'},['Audio','Kingdom','Account','Help'].map(t=>swElement('button',{key:t,'aria-pressed':tab===t,onClick:()=>setTab(t)},t))),
  tab==='Audio'?swElement('div',{className:'sw-settings-grid'},
    swElement('section',null,toggle('Sound effects',props.sound,props.onSound),range('Effects volume',props.volume,props.onVolume),swElement('button',{className:'secondary',disabled:!props.sound,onClick:props.onTest},'Test sound')),
    swElement('section',null,toggle('Background music',props.music,props.onMusic),range('Village music',props.musicVolume,props.onMusicVolume),range('Battle music',props.battleMusicVolume??.14,props.onBattleMusicVolume||props.onMusicVolume),swElement('p',{className:'sw-muted'},'Music stays quiet behind the game and pauses when you leave.'))):
  tab==='Kingdom'?swElement('div',{className:'sw-settings-grid'},
    swElement('section',null,swElement('label',{className:'sw-field'},'Kingdom name',swElement('input',{value:props.name,maxLength:24,onChange:e=>props.onName(e.target.value)})),swElement('button',{className:'primary',disabled:props.busy||props.name.trim().length<2,onClick:props.onSaveName},'Save name')),
    swElement('section',null,toggle('Haptics',props.haptics,props.onHaptics),toggle('Reduced effects',props.reducedEffects,props.onReducedEffects),toggle('Reduced motion',props.reduced,props.onMotion),swElement('p',{className:'sw-muted'},props.onlineMode?'Online changes are saved to your account. Your local kingdom remains separate.':'This local kingdom stays on this iPhone. Account settings provide cloud backup when online services are connected.'))):
  tab==='Account'?swElement(SWAccountPanel,{onBackup:props.onBackup,onRestoreBackup:props.onRestoreBackup,onEnterOnline:props.onEnterOnline,onReturnLocal:props.onReturnLocal,onlineMode:props.onlineMode,onlineBattle:props.onlineBattle}):
  swElement('div',{className:'sw-help'},swElement('p',null,'Drag to explore. Tap a building to upgrade it. Open Menu for construction, your army, the fleet, and campaign.'),swElement('p',null,'Gems finish active construction, shipbuilding, or research. The cost is shown before you spend.'),swElement('button',{className:'secondary',onClick:props.onGuide},'How to play')));
}
function SWArmy({open,onClose,state,act,busy,onFrontier,onCommander}) {
 const [selected,setSelected]=C.useState('infantry'),[count,setCount]=C.useState(1),[showLocked,setShowLocked]=C.useState(false),[mode,setMode]=C.useState('Train');
 const troop=J[selected],level=Ml(state),owned=Nl(state.army),capacity=Pl(state);
 const cost=Object.fromEntries(xl.map(key=>[key,troop.cost[key]*count]));
 const barracks=state.buildings.some(b=>b.kind==='barracks'&&b.level>0);
 const locked=level<troop.unlock||(selected==='cannon'&&!state.buildings.some(b=>b.kind==='forge'&&b.level>0));
 return swElement(SWDialog,{open,onClose,title:'Army · '+owned+' / '+capacity,subtitle:'Keep '+level,className:'sw-army'},
  swElement('div',{className:'sw-army-layout'},
   swElement('section',{className:'sw-unit-list'},swElement('div',{className:'sw-list-heading'},'Troops',swElement('button',{'aria-pressed':showLocked,onClick:()=>setShowLocked(!showLocked)},showLocked?'Available':'Show locked')),
    Object.entries(J).filter(([key,t])=>showLocked||t.unlock<=level).map(([key,t])=>swElement('button',{key,'aria-pressed':selected===key,className:'sw-unit-choice',onClick:()=>{setSelected(key);setMode('Train')}},swElement(lu,{kind:key,level:state.unitLevels?.[key]||1}),swElement('span',null,t.name,swElement('small',null,level<t.unlock?'Keep '+t.unlock:'Level '+(state.unitLevels?.[key]||1))),swElement('strong',null,state.army[key]||0)))),
   swElement('section',{className:'sw-unit-detail'},swElement('div',{className:'sw-unit-heading'},swElement(lu,{kind:selected,level:state.unitLevels?.[selected]||1}),swElement('div',null,swElement('h3',null,troop.name,swElement('small',{className:'sw-unit-level'},'Lv '+(state.unitLevels?.[selected]||1))),swElement('p',null,troop.description))),
    swElement('div',{className:'sw-stats'},swElement('span',null,'Health ',swElement('strong',null,Math.round(troop.hp*(1+0.16*((state.unitLevels?.[selected]||1)-1))))),swElement('span',null,troop.heal?'Heal ': 'Attack ',swElement('strong',null,troop.heal?Math.round(troop.heal*(1+0.14*((state.unitLevels?.[selected]||1)-1))):Math.round(troop.damage*(1+0.14*((state.unitLevels?.[selected]||1)-1))))),swElement('span',null,'Owned ',swElement('strong',null,state.army[selected]||0))),
    swElement('nav',{className:'sw-training-tabs','aria-label':'Troop actions'},['Train','Upgrade'].map(tab=>swElement('button',{key:tab,'aria-pressed':mode===tab,onClick:()=>setMode(tab)},tab))),
    mode==='Train'?swElement('div',{className:'sw-training-content'},swElement('div',{className:'sw-train-row'},swElement('select',{'aria-label':'Training quantity',value:count,onChange:e=>setCount(Number(e.target.value))},[1,5,10].map(n=>swElement('option',{key:n,value:n},'Train '+n))),swElement(Ku,{cost,available:state.resources})),
     swElement('button',{className:'primary wide',disabled:busy||locked||!barracks||owned+count>capacity||!Z(state,cost)||!!state.activeBattle,onClick:()=>act({type:'recruit',kind:selected,count},count+' '+troop.name+' ready')},!barracks?'Build a barracks first':locked?'Locked at this keep level':'Train '+count+' '+troop.name)):
     swElement('div',{className:'sw-research-content'},swElement(mu,{kind:selected,state,act,busy})),
    swElement(SWAbilitySummary,{key:selected,kind:selected,level:state.unitLevels?.[selected]||1}),
    swElement('div',{className:'sw-footer-actions'},swElement('button',{className:'secondary',onClick:onCommander},'Commander'),swElement('button',{className:'secondary',disabled:owned<3,onClick:onFrontier},'Go to frontier')))));
}
function SWScout({open,onClose,scout,state,busy,onAttack,onTrain,navalId,onNavalChange}) {
 if(!scout)return null;
 const supplied=!!scout.fixedArmy,hold=scout.previewInput?.saga?.mode==='hold';
 const weapons=scout.defense.buildings.filter(b=>Cc.includes(b.kind)).length;
 const navalEligible=typeof SWNavalEligible==='function'&&SWNavalEligible(scout),ships=navalEligible&&typeof SWNavalShips==='function'?SWNavalShips(state):[],enemyShips=scout.kind==='player'?(scout.defense.navalDefense||[]):typeof SWEnemyNavy==='function'?SWEnemyNavy(scout.defense):[];
 return swElement(SWDialog,{open,onClose,title:scout.title||scout.defense.name,subtitle:supplied?'A supplied expedition. Your home army and fleet stay safe.':'Scout the defenses, then choose your attack.',className:'sw-scout'},
  swElement('div',{className:'sw-scout-layout'},swElement('div',{className:'scout-map'},swElement(Eu,{buildings:scout.defense.buildings,provinces:scout.defense.provinces,livery:scout.defense.livery,appearance:scout.defense.appearance,enemy:true})),
   swElement('section',{className:'sw-scout-info'},swElement('div',{className:'sw-stats'},swElement('span',null,'Keep ',swElement('strong',null,scout.defense.level)),swElement('span',null,'Weapons ',swElement('strong',null,weapons)),swElement('span',null,hold?'Raiders ':'Army ',swElement('strong',null,Nl(supplied?scout.army:state.army)))),
    swElement('p',{className:supplied?'sw-mission-objective':''},supplied?scout.objective:'Breach a gate. Keep ranged troops behind the frontline. Select a troop, then tap, hold or drag outside the walls.'),hold&&swElement('p',null,'Your city defenses fight automatically. Watch your walls, towers, and keep hold the harbor.'),
    scout.kind==='campaign'&&swElement('div',{className:'sw-loot'},swElement('small',null,state.campaign>scout.campaignIndex?'Replay loot':'First victory loot · +25 gems'),swElement(Ku,{cost:state.campaign>scout.campaignIndex?{gold:35,wood:20,stone:15,food:25}:Tl[scout.campaignIndex].reward})),
    !supplied&&navalEligible&&swElement('label',{className:'sw-naval-choice'},swElement('span',null,'Naval support'+(enemyShips.length?' · '+enemyShips.length+' enemy '+(enemyShips.length===1?'ship':'ships'):'')),swElement('select',{'aria-label':'Naval support',value:navalId||'',disabled:busy||!ships.length,onChange:e=>onNavalChange?.(e.target.value||null)},swElement('option',{value:''},'No ship'),ships.map(ship=>swElement('option',{key:ship.id,value:ship.id},wc[ship.kind].name+' · level '+ship.level))),swElement('small',null,ships.length?(scout.kind==='player'?'Your ship fights, then bombards. Sunk attackers need repair; home defenders recover.':'Fight enemy ships, then bombard the coast. Ships can sink.'):'Return an armed ship, collect its cargo, and repair any damage first.')),
    swElement('button',{className:'primary wide',disabled:busy||(!supplied&&Nl(state.army)<3),onClick:onAttack},busy?'Preparing…':hold?'Defend harbor':supplied?'Begin expedition':'Attack'),!supplied&&Nl(state.army)<3&&swElement('button',{className:'secondary wide',onClick:onTrain},'Recruit 3 troops first'))));
}
function SWFleet({open,onClose,state,act,busy,onBuildPort,onViewCoast}) {
 const navigate=C.useContext(SWNavigationContext),[tab,setTab]=C.useState('Fleet'),[routes,setRoutes]=C.useState({}),port=rl(state),now=Date.now(),fleet=state.fleet||[];
 const shipwrightBusy=fleet.some(ship=>ship.readyAt||ship.repairReadyAt),berths=Math.min(8,port+1);
 return swElement(SWDialog,{open,onClose,title:'Fleet',subtitle:'Your coastal shipyard',className:'fleet-dialog sw-fleet'},
  swElement('nav',{className:'sw-tabs','aria-label':'Fleet sections'},['Fleet','Shipyard','Routes'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,onClick:()=>setTab(name)},name))),
  tab==='Fleet'?swElement(C.Fragment,null,
   swElement('div',{className:'fleet-overview'},swElement(xe,{size:25}),swElement('div',null,swElement('strong',null,fleet.length+' / '+berths+' berths'),swElement('span',null,port?'Shipyard '+port+' · '+(shipwrightBusy?'Shipwright working':'Shipwright ready'):'Build a shipyard on the coast')),swElement('button',{className:'secondary',onClick:()=>{onClose();onViewCoast()}},'View coast')),
   !port&&swElement('button',{className:'primary wide',onClick:()=>{onClose();onBuildPort()}},'Build coastal shipyard'),
   swElement('div',{className:'owned-fleet'},fleet.length?fleet.map(ship=>{
    const type=wc[ship.kind],power=Math.round(type.power*(1+.22*(ship.level-1))),routeId=routes[ship.id]||'coast',route=Ec.find(r=>r.id===routeId),repairCost=typeof SWShipRepairCost==='function'?SWShipRepairCost(ship):{},repairing=ship.repairReadyAt>now;
    const usableRoutes=Ec.filter(r=>port>=r.unlock&&power>=r.power),working=!!ship.readyAt||repairing,canCollect=!ship.voyage||typeof SWCanReceive!=='function'||SWCanReceive(state,ship.voyage.reward);
    return swElement('section',{key:ship.id,className:'vessel-card'+(ship.wrecked?' sw-vessel-wrecked':'')},swElement(uu,{kind:ship.kind,level:ship.level||1}),swElement('div',null,
     swElement('h3',null,type.name),swElement('span',null,'Level '+ship.level+' · Strength '+power),
     ship.repairReadyAt?swElement('p',{className:'sw-ship-status'},'Repairing · '+Qc(Math.max(0,(ship.repairReadyAt-now)/1000))):
     ship.wrecked?swElement(C.Fragment,null,swElement('p',{className:'sw-ship-status'},'Sunk in battle · Recover and repair at the shipyard.'),swElement(Ku,{cost:repairCost,available:state.resources}),swElement('button',{className:'primary',disabled:busy||shipwrightBusy||!Z(state,repairCost),onClick:()=>act({type:'repairShip',id:ship.id},'Ship repair started')},shipwrightBusy?'Shipwright busy':'Repair ship')):
     ship.combatBattleId?swElement('p',{className:'sw-ship-status'},'Supporting your army in battle'):
     working?swElement('p',{className:'sw-ship-status'},'Shipwright working · '+Qc(Math.max(0,(ship.readyAt-now)/1000))):
     ship.voyage?swElement(C.Fragment,null,swElement('p',{className:'sw-ship-status'},(Ec.find(r=>r.id===ship.voyage.route)?.name||'At sea')+' · '+(ship.voyage.readyAt>now?Qc((ship.voyage.readyAt-now)/1000):'Cargo ready')),swElement('button',{className:'primary',disabled:busy||ship.voyage.readyAt>now||!canCollect,onClick:()=>act({type:'collectVoyage',id:ship.id},'Cargo delivered')},canCollect?'Collect cargo':'Make room for cargo'),!canCollect&&swElement('button',{className:'secondary',onClick:()=>navigate?.('storage')},'Manage storage')):
     swElement(C.Fragment,null,swElement('p',{className:'sw-ship-status'},['galley','bombard'].includes(ship.kind)?'Ready for voyages or battle support':'Ready for a trading voyage'),
      swElement('select',{'aria-label':'Route for '+type.name,value:routeId,onChange:e=>setRoutes({...routes,[ship.id]:e.target.value})},Ec.map(r=>swElement('option',{key:r.id,value:r.id,disabled:!usableRoutes.includes(r)},r.name+' · '+Qc(r.duration)))),
      swElement('div',{className:'vessel-actions'},swElement('button',{className:'primary',disabled:busy||!route||!usableRoutes.includes(route),onClick:()=>act({type:'voyage',id:ship.id,kind:routeId},'Ship has set sail')},'Set sail'),swElement('button',{className:'secondary',disabled:busy||ship.level>=10||ship.level>=port||shipwrightBusy||!Z(state,nl(ship.kind,ship.level+1)),onClick:()=>act({type:'upgradeShip',id:ship.id},'Ship upgrade started')},ship.level>=10?'Mastered':ship.level>=port?'Upgrade shipyard':'Upgrade to '+(ship.level+1))),ship.level<10&&swElement(Ku,{cost:nl(ship.kind,ship.level+1),available:state.resources}))));
   }):swElement('p',{className:'sw-empty'},'No ships yet. Open Shipyard to build your first vessel.'))):
  tab==='Shipyard'?swElement('div',{className:'ship-catalog'},Object.entries(wc).map(([kind,type])=>swElement('button',{key:kind,className:'ship-card',disabled:busy||port<type.unlock||shipwrightBusy||fleet.length>=berths||!Z(state,nl(kind)),onClick:()=>act({type:'buildShip',kind},'Ship construction started')},swElement(uu,{kind}),swElement('strong',null,type.name),swElement('p',null,type.description),swElement(Ku,{cost:nl(kind),available:state.resources}),swElement('span',null,port<type.unlock?'Shipyard '+type.unlock+' required':shipwrightBusy?'Shipwright busy':fleet.length>=berths?'All berths occupied':'Build · '+Qc(type.time))))):
  swElement('div',{className:'sea-route-detail'},Ec.map(route=>swElement('section',{key:route.id},swElement('strong',null,route.name),swElement('span',null,Qc(route.duration)+' · Strength '+route.power+' · Shipyard '+route.unlock),swElement(Ku,{cost:route.reward})))));
}
function SWGems({open,onClose,state,act,busy,onlineMode,onOnlineGame}) {
 const [confirm,setConfirm]=C.useState(null);
 C.useEffect(()=>{if(!open)setConfirm(null)},[open]);
 const projects=GemProjects(state),selected=confirm&&projects.find(p=>p.target===confirm.target&&p.id===confirm.id);
 return swElement(SWDialog,{open,onClose,title:'Gems · '+(state.gems||0),subtitle:'Your gem wallet',className:'sw-gems'},
   swElement('div',{className:'sw-gem-intro'},swElement('span',{className:'sw-gem-symbol'},'◆'),swElement('div',null,swElement('strong',null,'Finish a project instantly'),swElement('p',null,'1 gem per minute remaining. Existing resources and progress are kept.'))),
   selected?swElement('section',{className:'sw-confirm'},swElement('h3',null,'Finish '+selected.name+'?'),swElement('p',null,'Spend '+GemCost(selected.readyAt)+' gems. This cannot be undone.'),swElement('div',{className:'sw-footer-actions'},swElement('button',{className:'secondary',onClick:()=>setConfirm(null)},'Cancel'),swElement('button',{className:'primary',disabled:busy||state.gems<GemCost(selected.readyAt),onClick:async()=>{const result=await act({type:'speedup',target:selected.target,id:selected.id,maxCost:GemCost(selected.readyAt)},'Project finished');if(result)setConfirm(null)}},'Spend '+GemCost(selected.readyAt)+' gems'))):
   swElement('div',{className:'sw-projects'},projects.length?projects.map(p=>swElement('div',{className:'sw-project',key:p.target+p.id},swElement('div',null,swElement('strong',null,p.name),swElement('small',null,Qc(Math.max(0,(p.readyAt-Date.now())/1000))+' remaining')),swElement('button',{className:'secondary',disabled:busy||state.gems<GemCost(p.readyAt),onClick:()=>setConfirm(p)},'Finish · '+GemCost(p.readyAt)+' ◆'))):swElement('p',{className:'sw-empty'},'No projects are running. Start a building upgrade, research, or a ship to use gems.')),
   swElement('div',{className:'sw-gem-earn'},swElement('strong',null,'Earn gems'),swElement('p',null,'100 starter gems · 8 per objective · 15 per achievement · 25 for each first campaign victory.'),swElement('small',null,'Earned gems stay with the kingdom where you earned them.')),swElement(SWGemStore,{onlineMode,onOnlineGame}));
}

function SWNotice({event,onDismiss}) {
 if(!event)return null;
 const Icon=Iu[event.icon||'trophy'];
 return swElement('aside',{className:'sw-notice',role:'status','aria-live':'polite'},
   swElement(Icon,{size:19}),swElement('span',{className:'sw-notice-copy'},swElement('strong',null,event.title),event.reward&&swElement(Ku,{cost:event.reward})),
   swElement('button',{'aria-label':'Dismiss celebration',onPointerDown:e=>e.stopPropagation(),onClick:e=>{e.preventDefault();e.stopPropagation();onDismiss();}},swElement(je,{size:18})));
}
function SWAchievements({open,onClose,state,act,busy,embedded=false}) {
 const navigate=C.useContext(SWNavigationContext),ready=Dl.filter(a=>Ol(state,a)>=a.target&&!state.honors?.includes(a.id));
 const [tab,setTab]=C.useState('Ready');
 C.useEffect(()=>{if(open)setTab(ready.length?'Ready':'In progress')},[open]);
 const earned=Dl.filter(a=>state.honors?.includes(a.id));
 const entries=Dl.filter(a=>tab==='Ready'?Ol(state,a)>=a.target&&!state.honors?.includes(a.id):tab==='Earned'?state.honors?.includes(a.id):Ol(state,a)<a.target);
 return swElement(embedded?'section':SWDialog,embedded?{className:'sw-achievements sw-journal-section14'}:{open,onClose,title:'Achievements',subtitle:earned.length+' collected · '+ready.length+' rewards ready',className:'sw-achievements'},
  swElement('nav',{className:'sw-tabs','aria-label':'Achievement sections'},['Ready','In progress','Earned'].map(t=>swElement('button',{key:t,'aria-pressed':tab===t,onClick:()=>setTab(t)},t==='Ready'?'Ready ('+ready.length+')':t))),
  tab==='Ready'&&ready.some(a=>typeof SWCanReceive==='function'&&!SWCanReceive(state,a.reward))&&swElement('button',{className:'sw-storage-warning',onClick:()=>navigate?.('storage')},'Make room for rewards · Manage storage'),
  swElement('div',{className:'sw-achievement-list'},entries.length?entries.map(a=>{const Icon=Iu[a.icon],progress=Math.min(a.target,Ol(state,a));return swElement('section',{key:a.id,className:'sw-achievement'},swElement(Icon,{size:24}),swElement('div',null,swElement('h3',null,a.title),swElement('p',null,a.description),tab==='In progress'?swElement('div',{className:'sw-achievement-progress'},swElement('progress',{max:a.target,value:progress}),swElement('small',null,progress+' / '+a.target)):swElement(Ku,{cost:a.reward})),tab==='Ready'?swElement('button',{className:'primary','aria-label':'Collect reward for '+a.title,disabled:busy||(typeof SWCanReceive==='function'&&!SWCanReceive(state,a.reward)),onClick:()=>act({type:'claimAchievement',id:a.id})},typeof SWCanReceive==='function'&&!SWCanReceive(state,a.reward)?'Storage full':'Collect',swElement('small',null,'+15 ◆')):tab==='Earned'?swElement(O,{size:17}):null)}):swElement('p',{className:'sw-empty'},tab==='Ready'?'All rewards collected. Your next milestones are in In progress.':'No medals here yet.')));
}
function SWBattleControls({input,frame,navalHull,selected,onSelect,onRetreat,disabled,replay,speed,onSpeed,onRally,onAbility,onNaval}) {
 const reserves=hl(input),rail=C.useRef(null),total=Object.values(reserves).reduce((sum,n)=>sum+(Number(n)||0),0);
 const kinds=Object.keys(J).filter(kind=>input.army[kind]>0);
 const enemyShips=frame?.units.filter(unit=>unit.naval&&unit.side==='defend'&&unit.hp>0).length??input.enemyNavy?.length??0;
 const canRally=input.rallyAt===undefined&&frame?.units.some(u=>u.side==='attack'&&u.hp>0);
 const canAbility=input.commander&&input.heroAt===undefined&&frame?.units.some(u=>u.kind==='hero'&&u.hp>0);
 C.useEffect(()=>{const root=rail.current,card=root?.querySelector('[data-troop="'+selected+'"]');if(!root||!card)return;const left=card.offsetLeft,right=left+card.offsetWidth;if(left<root.scrollLeft)root.scrollLeft=left;else if(right>root.scrollLeft+root.clientWidth)root.scrollLeft=right-root.clientWidth;},[selected]);
 const card=(kind,name,art)=>swElement('button',{key:kind,'data-troop':kind,'aria-label':'Deploy '+name+', '+(reserves[kind]||0)+' remaining','aria-description':selected===kind?'Selected. Tap, hold or drag on the battlefield outside enemy walls.':'Select this troop, then deploy on the battlefield.','aria-pressed':selected===kind,className:'sw-troop-card'+(selected===kind?' selected':'')+(!reserves[kind]?' empty':''),disabled:disabled||!reserves[kind],onClick:()=>onSelect(kind)},art,selected===kind&&swElement(O,{className:'sw-troop-selected',size:12,'aria-hidden':true}),swElement('span',{className:'sw-troop-name'},name),swElement('strong',{className:'sw-troop-count'},'×'+(reserves[kind]||0)));
 return swElement('div',{className:'sw-battle-controls sw-persistent-deploy'+(replay?' sw-replay-controls':'')},
  !replay&&swElement('section',{className:'sw-troop-strip','aria-label':'Troops to deploy. Swipe horizontally to see more.',ref:rail,tabIndex:0,onKeyDown:event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const choices=[...kinds,...(input.commander?['hero']:[])].filter(kind=>reserves[kind]>0);if(!choices.length)return;event.preventDefault();const index=choices.indexOf(selected),next=event.key==='Home'?0:event.key==='End'?choices.length-1:Math.max(0,Math.min(choices.length-1,index+(event.key==='ArrowRight'?1:-1)));onSelect(choices[next]);}},kinds.map(kind=>card(kind,J[kind].name,swElement(lu,{kind,level:input.unitLevels?.[kind]||1}))),input.commander&&card('hero','Commander',swElement(nu,{id:input.commander.id}))),
  swElement('div',{className:'sw-battle-secondary'},
   !replay&&swElement('span',{className:'sw-deployment-status',role:'status','aria-live':'polite',title:'Select a troop, then tap, hold or drag outside the walls.'},total===0?'All troops deployed':reserves[selected]>0?(selected==='hero'?'Commander':J[selected]?.name||'Troops')+' · '+reserves[selected]+' left':(selected==='hero'?'Commander':J[selected]?.name||'Troops')+' deployed · choose another'),
   swElement('div',{className:'sw-battle-actions'},
    swElement('button',{className:'secondary sw-speed','aria-label':'Battle speed '+speed+' times',onClick:onSpeed,disabled:!onSpeed,title:!onSpeed?'Online battles run in real time':undefined},speed+'×'),
    !replay&&swElement('button',{className:'primary sw-rally',disabled:disabled||!canRally,onClick:onRally,'aria-label':input.rallyAt===undefined?'Rally troops':'Rally used'},swElement(se,{size:16}),input.rallyAt===undefined?'Rally':'Used'),
    !replay&&input.commander&&swElement('button',{className:'primary sw-ability',disabled:disabled||!canAbility,onClick:onAbility,'aria-label':input.heroAt===undefined?Oc[input.commander.id].ability:'Commander ability used'},swElement(oe,{size:16}),input.heroAt===undefined?'Ability':'Used'),
    !replay&&input.navalSupport&&(input.navalVersion>=2?swElement('div',{className:'sw-naval-status'+(navalHull?.hp===0?' sunk':''),'aria-label':'Naval support '+(navalHull?.hp===0?'sunk':'active')+', '+enemyShips+' enemy ships afloat'},swElement(xe,{size:15}),swElement('span',null,navalHull?.hp===0?'Sunk':enemyShips?enemyShips+' enemy':'Naval',swElement('progress',{'aria-label':'Ship hull',max:navalHull?.maxHp||1,value:navalHull?.hp??1}))):swElement('button',{className:'primary sw-naval-button',disabled:disabled||input.navalAt!==undefined||!onNaval,onClick:onNaval,'aria-label':input.navalAt===undefined?'Fire naval broadside':'Naval broadside used'},swElement(xe,{size:16}),input.navalAt===undefined?'Broadside':'Used')),
    !replay&&swElement('button',{className:'secondary sw-retreat',onClick:onRetreat,disabled,'aria-label':'Retreat'},'Retreat'))));
}

function SWBuildingPanel({children}) {
 const parts=C.Children.toArray(children);
 return swElement('aside',{className:'building-detail panel sw-building-panel'},swElement('div',{className:'sw-building-header'},parts.slice(0,2)),swElement('div',{className:'sw-building-body'},parts.slice(2)));
}

function SWLegacyContent({className,children,...props}) {
 const parts=C.Children.toArray(children),heading=parts.find(part=>part.type===Ps);
 return swElement(Ns,{...props,className:className+' sw-dialog sw-legacy-content'},heading,swElement('div',{className:'sw-body'},parts.filter(part=>part!==heading)));
}
function SWResultContent({className,children,defenseReport,objective,earnedGems,onRetry,seaResult,storesFull=false,onRepair,...props}) {
 const parts=C.Children.toArray(children?.type===C.Fragment?children.props.children:children),heading=parts.find(part=>part.type===Ps),footer=parts.findLast(part=>part.type==='button'&&part.props.className?.includes('primary'));
 const content=parts.filter(part=>part!==heading&&part!==footer&&!['victory-rays','victory-seal'].some(name=>part.props.className?.includes(name))),metrics=content.filter(part=>['stars','result-stats'].includes(part.props.className)),loot=content.find(part=>part.props.className==='victory-loot'),summary=content.filter(part=>!metrics.includes(part)&&part!==loot),repairs=Object.values(seaResult?.navalSurvivors||{}).filter(v=>!v).length;
 return swElement(Ns,{...props,className:className+' sw-dialog sw-result-content'},heading,
  swElement('div',{className:'sw-body'},swElement('div',{className:'sw-result-overview'},swElement('div',{className:'sw-result-metrics'},swElement(SWIllustration13,{index:7,className:'sw-victory-art13'}),metrics),
   swElement('div',{className:'sw-result-rewards14'},objective&&swElement('div',{className:'sw-result-objective'},swElement(objective.won?O:be,{size:23}),swElement('strong',null,objective.label),objective.escortHealth!=null&&swElement('span',null,'Escort health · '+Math.round(objective.escortHealth*100)+'%')),loot,earnedGems>0&&swElement('b',{className:'sw-result-gems14'},'◆ +'+earnedGems+' gems'),storesFull&&swElement('p',{className:'sw-result-capacity14'},'Stores full. Resource spoils could not be collected. Expand storage before your next raid.'))),
   swElement('div',{className:'sw-result-summary'},seaResult&&swElement('div',{className:'sw-sea-summary14'},swElement('strong',null,seaResult.landedTroops+' '+(seaResult.landedTroops===1?'troop landed':'troops landed')+' · '+seaResult.rescuedTroops+' rescued aboard'),swElement('p',null,repairs?repairs+' '+(repairs===1?'ship needs':'ships need')+' repairs. Your fleet remains yours.':'All ships returned safely.')),summary,defenseReport&&swElement(SWDefenseReportSummary,{report:defenseReport,compact:true}))),
  swElement('div',{className:'sw-result-footer'},onRetry&&swElement('button',{className:'secondary',onClick:onRetry},'Retry expedition'),repairs>0&&onRepair&&swElement('button',{className:'secondary',onClick:onRepair},'Repair fleet'),footer));
}
