// Stonewake premium interface. Keep this block synchronized with the bundled module.
const SWWardrobeCategories=[['appearance','Kingdom',ne],['banners','Banners',se],['sails','Sails',xe],['roads','Roads',_e],['monuments','Monuments',Ee],['outfits','Outfits',oe]];
function SWPremiumRewardView({reward,className=''}) {
 if(!reward)return null;
 const cosmetics=(reward.cosmetics||[]).map(id=>SWPremiumCatalog.find(item=>item.id===id)).filter(Boolean);
 return swElement('div',{className:'sw-premium-reward '+className},reward.resources&&xl.some(key=>reward.resources[key]>0)&&swElement(Ku,{cost:reward.resources}),reward.gems>0&&swElement('strong',{className:'sw-reward-gems'},'◆ '+reward.gems),cosmetics.map(item=>swElement('span',{className:'sw-reward-piece',key:item.id},swElement(Ee,{size:14}),item.name)));
}
function SWStoryLines({lines,compact=false}) {
 const [speaking,setSpeaking]=C.useState(false),[unavailable,setUnavailable]=C.useState(false),eventId=C.useRef(''),sequence=C.useRef(0),text=(lines||[]).map(line=>line.speaker+'. '+line.text).join(' '),native=!!window.webkit?.messageHandlers?.stonewake;
 const stop=()=>{window.webkit?.messageHandlers?.stonewake?.postMessage({kind:'narration',action:'stop'});setSpeaking(false)};
 C.useEffect(()=>{setSpeaking(false);setUnavailable(false);return()=>window.webkit?.messageHandlers?.stonewake?.postMessage({kind:'narration',action:'stop'})},[text]);
 C.useEffect(()=>{const status=event=>{if(event.detail?.eventId&&event.detail.eventId!==eventId.current)return;setSpeaking(event.detail?.status==='speaking');setUnavailable(event.detail?.status==='unavailable')};window.addEventListener('stonewake-narration-status',status);return()=>window.removeEventListener('stonewake-narration-status',status)},[]);
 const listen=()=>{if(speaking){stop();return}eventId.current='story-'+Date.now()+'-'+(++sequence.current);setSpeaking(true);setUnavailable(false);window.webkit?.messageHandlers?.stonewake?.postMessage({kind:'narration',action:'speak',text:text.slice(0,3000),speaker:lines?.[0]?.speaker,eventId:eventId.current})};
 if(!lines?.length)return null;
 return swElement('div',{className:'sw-story-lines'+(compact?' compact':'')},lines.map((line,index)=>{const id=Object.keys(Oc).find(id=>Oc[id].name===line.speaker);return swElement('blockquote',{key:index},swElement('div',{className:'sw-story-speaker'},id&&swElement(nu,{id,className:'sw-story-portrait'}),swElement('strong',null,line.speaker)),swElement('p',null,line.text))}),native&&swElement('div',{className:'sw-story-narration'},swElement('button',{className:'text-button','aria-label':speaking?'Stop narration':'Listen to dialogue',onClick:listen},swElement(speaking?ke:Oe,{size:14}),speaking?'Stop':'Listen'),swElement('small',null,unavailable?'Voice unavailable. Check sound settings.':'Optional system narration')));
}
function SWStoreProduct({product,owned,busy,onlineMode,onPurchase,onAccount}) {
 return swElement('button',{className:'sw-store-product',disabled:busy||owned,onClick:()=>onlineMode?onPurchase(product):onAccount()},swElement('span',null,swElement('strong',null,product.name),swElement('small',null,product.gems?product.gems.toLocaleString()+' gems':product.description||'Permanent cosmetic collection')),swElement('b',null,owned?'Owned':onlineMode?product.displayPrice:'Open Account'));
}
function SWPremiumStore({open,onClose,state,act,busy,onlineMode,onOnlineGame,initialTab='Wardrobe',ownedOnly=false,onPlace,onProjects}) {
 const navigate=C.useContext(SWNavigationContext),online=SWUseOnline();
 const [tab,setTab]=C.useState(initialTab),[category,setCategory]=C.useState('appearance'),[owned,setOwned]=C.useState(ownedOnly),[selected,setSelected]=C.useState(null),[confirm,setConfirm]=C.useState(false),[working,setWorking]=C.useState(false),[message,setMessage]=C.useState('');
 const catalog=typeof SWPremiumCatalog!=='undefined'?SWPremiumCatalog:[],collections=typeof SWPremiumCollections!=='undefined'?SWPremiumCollections:[];
 const items=catalog.filter(item=>item.category===category&&(!owned||SWCosmeticStatus(state,item.id).owned));
 const item=items.find(item=>item.id===selected)||items[0],quote=item?SWCosmeticStatus(state,item.id):null;
 const purchasing=busy||working,products=online.products||[],nativeReady=online.configured&&online.signedIn&&onlineMode;
 C.useEffect(()=>{if(open){setTab(initialTab);setOwned(ownedOnly);setConfirm(false);setMessage('')}},[open,initialTab,ownedOnly]);
 C.useEffect(()=>{setConfirm(false)},[item?.id,category,tab]);
 C.useEffect(()=>{if(open&&online.configured&&online.signedIn)window.SWOnline.call('products').catch(error=>setMessage(error.message))},[open,online.configured,online.signedIn]);
 const purchase=async product=>{setWorking(true);setMessage('');try{const result=await window.SWOnline.call('purchase',{productId:product.id});if(result.game)await onOnlineGame?.(result.game);setMessage(result.status==='granted'?'Purchase verified. Your online collection is ready.':result.status==='revoked'?'Apple updated this purchase. Your verified ownership is now current.':result.status==='pending'?'Waiting for Apple to confirm. Your balance has not been changed.':'Purchase cancelled. Nothing was added.')}catch(error){setMessage(error.message||'The purchase could not be completed.')}finally{setWorking(false)}};
 const restore=async()=>{setWorking(true);setMessage('');try{const result=await window.SWOnline.call('restorePurchases');if(result.game)await onOnlineGame?.(result.game);setMessage('Verified purchases have been checked for this Online Kingdom.')}catch(error){setMessage(error.message||'Purchases could not be checked.')}finally{setWorking(false)}};
 const buy=async()=>{const result=await act({type:'buyCosmetic',id:item.id,maxPrice:quote.priceGems},item.name+' added to your wardrobe');if(result){setConfirm(false);setMessage(item.name+' is yours. Equip it when you are ready.')}};
 const categoryIcon=id=>SWWardrobeCategories.find(category=>category[0]===id)?.[2]||ne;
 return swElement(SWDialog,{open,onClose,title:ownedOnly?'Customize your kingdom':'Shop',subtitle:(onlineMode?'Online':'Local')+' collection · '+state.gems.toLocaleString()+' gems',className:'sw-premium-store'},
  swElement('nav',{className:'sw-tabs','aria-label':'Store sections'},['Wardrobe','Collections','Gems'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,onClick:()=>setTab(name)},name))),
  tab==='Wardrobe'&&swElement('div',{className:'sw-wardrobe'},
   swElement('div',{className:'sw-wardrobe-browser'},
    swElement('nav',{className:'sw-wardrobe-categories','aria-label':'Cosmetic categories'},SWWardrobeCategories.map(([id,name,Icon])=>swElement('button',{key:id,'aria-pressed':category===id,onClick:()=>{setCategory(id);setSelected(null)}},swElement(Icon,{size:16}),name))),
    swElement('div',{className:'sw-catalog-heading'},swElement('span',null,items.length+' '+(items.length===1?'piece':'pieces')),swElement('button',{className:'sw-owned-filter','aria-pressed':owned,onClick:()=>setOwned(!owned)},swElement(owned?O:oe,{size:14}),owned?'Owned only':'All pieces')),
    swElement('div',{className:'sw-catalog-grid','aria-label':'Cosmetic pieces'},items.map(piece=>{const status=SWCosmeticStatus(state,piece.id),Icon=categoryIcon(piece.category);return swElement('button',{key:piece.id,className:'sw-catalog-item'+(item?.id===piece.id?' selected':''),'aria-pressed':item?.id===piece.id,onClick:()=>setSelected(piece.id)},swElement('span',{className:'sw-catalog-emblem',style:{'--piece-color':piece.preview}},swElement(SWCatalogArt13,{item:piece}),status.equipped&&swElement(O,{className:'sw-equipped-mark',size:14})),swElement('strong',null,piece.name),swElement('small',null,status.equipped?'Equipped':status.owned?'Owned':piece.priceGems!=null?'◆ '+piece.priceGems:piece.unlockLabel||'Earn in Adventures'))})),
    !items.length&&swElement('div',{className:'sw-empty'},swElement('p',null,'No owned pieces in this category yet.'),swElement('button',{className:'secondary',onClick:()=>setOwned(false)},'Browse all pieces'))),
   item&&swElement('section',{className:'sw-store-preview-pane','aria-label':'Selected appearance'},
    swElement('div',{className:'sw-cosmetic-preview'},swElement(SWCosmeticPreview,{state,item,appearance:SWAppearance(state,item.id)}),swElement('span',{className:'sw-preview-caption'},quote.equipped?'Equipped in your kingdom':'Live preview · no changes yet')),
    swElement('div',{className:'sw-store-detail'},swElement('span',{className:'sw-eyebrow'},SWWardrobeCategories.find(c=>c[0]===item.category)?.[1]),swElement('h3',null,item.name),swElement('p',null,item.description),swElement('p',{className:'sw-cosmetic-fairness'},'Appearance only. Battle strength stays the same.')),
    swElement('div',{className:'sw-store-actions'},confirm?swElement('div',{className:'sw-store-confirm',role:'group','aria-label':'Confirm cosmetic purchase'},swElement('p',null,'Spend ',swElement('strong',null,quote.priceGems+' gems'),' on '+item.name+'?'),swElement('div',null,swElement('button',{className:'secondary',disabled:purchasing,onClick:()=>setConfirm(false)},'Cancel'),swElement('button',{className:'primary',disabled:purchasing,onClick:buy},'Buy · '+quote.priceGems+' ◆'))):
      quote.owned&&item.slot==='ornament'?swElement(C.Fragment,null,swElement('button',{className:'primary',disabled:purchasing,onClick:()=>onPlace(item.id)},'Place in the city'),swElement('div',{className:'sw-placed-ornaments'},(state.premium?.ornaments||[]).filter(o=>o.itemId===item.id).map((placed,index)=>swElement('button',{className:'text-button',key:placed.id,disabled:purchasing,onClick:()=>act({type:'removeOrnament',placementId:placed.id},'Decoration returned to your wardrobe')},'Remove placement '+(index+1))))):quote.owned?swElement(C.Fragment,null,swElement('button',{className:'primary',disabled:purchasing||quote.equipped,onClick:()=>act({type:'equipCosmetic',id:item.id},item.name+' equipped')},quote.equipped?'Equipped':'Equip '+item.name),item.category==='monuments'&&onPlace&&swElement('button',{className:'secondary',disabled:purchasing,onClick:()=>onPlace(item.id)},'Place in the city')):
      swElement(C.Fragment,null,swElement('button',{className:'primary',disabled:purchasing||!quote.canBuy,onClick:()=>setConfirm(true)},quote.canBuy?'Buy · '+quote.priceGems+' ◆':quote.reason||quote.unlockLabel||'Earn in Adventures'),!quote.canBuy&&swElement('button',{className:'text-button',onClick:()=>navigate(item.priceGems!=null?'gems':'chronicle')},item.priceGems!=null?'Get gems':'Open Adventures'))))),
  tab==='Collections'&&swElement('div',{className:'sw-store-collections'},swElement('div',{className:'sw-store-intro'},swElement('h3',null,'Kingdom collections'),swElement('p',null,'Coordinated looks for your kingdom. Preview any piece.')),
   collections.map(collection=>{const pieces=(collection.items||[]).map(id=>catalog.find(item=>item.id===id)).filter(Boolean),product=products.find(product=>product.collectionId===collection.id),allOwned=pieces.length>0&&pieces.every(piece=>SWCosmeticStatus(state,piece.id).owned);return swElement('article',{className:'sw-collection-card',key:collection.id},swElement('div',{className:'sw-collection-title'},swElement(Ee,{size:27}),swElement('div',null,swElement(SWIllustration13,{index:collection.id==='mariner'?1:collection.id==='royal'?5:3,className:'sw-collection-cover13'}),swElement('h3',null,collection.name),swElement('p',null,collection.description))),swElement('div',{className:'sw-collection-pieces'},pieces.map(piece=>swElement('button',{key:piece.id,onClick:()=>{setOwned(false);setTab('Wardrobe');setCategory(piece.category);setSelected(piece.id)}},swElement(categoryIcon(piece.category),{size:16}),piece.name,swElement(re,{size:13})))),allOwned?swElement('span',{className:'sw-collection-owned'},swElement(O,{size:16}),'Collection owned'):product?swElement(SWStoreProduct,{product,busy:purchasing,onlineMode:nativeReady,onPurchase:purchase,onAccount:()=>navigate('account')}):swElement('p',{className:'sw-store-availability'},online.configured?'This collection is not available from the App Store right now.':'App Store collections are not connected yet.'))}),
   !collections.length&&swElement('p',{className:'sw-empty'},'New collections will appear here when available.')),
  tab==='Gems'&&swElement('div',{className:'sw-store-gems'},swElement('section',{className:'sw-gem-balance-card'},swElement('span',null,'◆'),swElement('div',null,swElement('strong',null,state.gems.toLocaleString()),swElement('p',null,(onlineMode?'Online':'Local')+' gems')),swElement('button',{className:'secondary',onClick:onProjects},'Active projects')),
   swElement('p',{className:'sw-store-intro'},'Earn gems from adventures and achievements. Spend them on appearance or finish an active project. Every gem cost is shown before you choose.'),
   !online.configured?swElement('section',{className:'sw-store-availability'},swElement('strong',null,'Purchases are not connected yet'),swElement('p',null,'You can keep earning and spending gems in your local kingdom.')):!nativeReady?swElement('section',{className:'sw-store-availability'},swElement('p',null,'Purchased gems belong to your separate Online Kingdom. Your local gems stay here.'),swElement('button',{className:'secondary',onClick:()=>navigate('account')},'Open Account')):
   swElement('div',{className:'sw-gem-packs'},products.filter(product=>product.gems>0).map(product=>swElement(SWStoreProduct,{key:product.id,product,busy:purchasing,onlineMode:true,onPurchase:purchase})),!products.some(product=>product.gems>0)&&swElement('p',{className:'sw-empty'},'No gem packs are available from the App Store right now.'))),
  tab!=='Wardrobe'&&nativeReady&&swElement('button',{className:'text-button sw-restore-purchases',disabled:purchasing,onClick:restore},'Restore purchases'),
  message&&swElement('p',{className:'sw-store-message',role:'status'},message));
}
function SWMissionPane({children,...props}) {
 const flatten=nodes=>C.Children.toArray(nodes).flatMap(child=>child?.type===C.Fragment?flatten(child.props.children):[child]),parts=flatten(children),footer=parts.filter(part=>['sw-adventure-actions'].includes(part?.props?.className)||part?.type==='button'&&part.props.className?.includes('primary'));
 return swElement('section',props,swElement('div',{className:'sw-mission-reading'},parts.filter(part=>!footer.includes(part)).sort((a,b)=>(a?.props?.className==='sw-adventure-requirements'?-1:0)-(b?.props?.className==='sw-adventure-requirements'?-1:0))),swElement('div',{className:'sw-mission-footer'},footer));
}
function SWChronicle({open,onClose,state,act,busy,onStart,onRequirement,initialTab='Chapter',onReplay,reports=[]}) {
 const navigate=C.useContext(SWNavigationContext),[tab,setTab]=C.useState(initialTab),[selected,setSelected]=C.useState(null),[storyId,setStoryId]=C.useState(null),[choice,setChoice]=C.useState(null),[message,setMessage]=C.useState('');
 const chapter=SWChapter(state),missions=chapter.missions,mission=missions.find(m=>m.id===selected)||missions.find(m=>m.status!=='complete')||missions.at(-1),trials=SWTrials(state),stories=SWResidentStories(state),story=stories.find(s=>s.id===storyId)||stories.find(s=>['available','building','claimable'].includes(s.status))||stories.at(-1),events=SWEvents(state);
 C.useEffect(()=>{if(open){setTab(initialTab);setMessage('')}},[open,initialTab]);
 C.useEffect(()=>setChoice(null),[story?.id]);
 C.useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(timer)},[message]);
 const perform=async(action,text)=>{const next=await act(action,text);if(next)setMessage(text);return next};
 const requirements=items=>items?.some(item=>!item.met)?swElement('ul',{className:'sw-adventure-requirements'},items.filter(requirement=>!requirement.met).map((requirement,index)=>swElement('li',{key:index,className:requirement.met?'met':''},swElement(requirement.met?O:be,{size:15}),swElement('span',null,requirement.label),!requirement.met&&requirement.action&&swElement('button',{className:'text-button',onClick:()=>onRequirement(requirement)},'View')))):null;
 const storyBusy=stories.some(s=>s.status==='building'||s.status==='claimable');
 const selectedChoice=story?.choices.find(c=>c.id===choice)||story?.choices[0];
 const finished=missions.every(m=>m.status==='complete'),era=SWMedievalFinale(state),viewingEra=selected==='era'||(!selected&&chapter.claimed);
 return swElement(SWDialog,{open,onClose,title:'Journal',subtitle:chapter.title+' · '+chapter.completed+' / '+missions.length+' missions',className:'sw-chronicle'},
  swElement('nav',{className:'sw-tabs','aria-label':'Journal sections'},['Chapter','Trials','Residents','Events','Achievements','Reports'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,onClick:()=>{setTab(name);setMessage('')}},name))),
  tab==='Achievements'&&swElement(SWAchievements,{open,embedded:true,state,act,busy}),
  tab==='Reports'&&swElement(SWJournalReports14,{reports,onReplay}),
  tab==='Chapter'&&swElement('div',{className:'sw-adventure-layout'},
   swElement('nav',{className:'sw-mission-list','aria-label':'Chapter missions'},missions.map((m,index)=>swElement('button',{key:m.id,'aria-pressed':!viewingEra&&mission.id===m.id,onClick:()=>{setSelected(m.id);setMessage('')},className:'sw-mission-choice '+m.status},swElement('span',{className:'sw-mission-number'},m.status==='complete'?swElement(O,{size:17}):index+1),swElement('span',null,swElement('strong',null,m.title),swElement('small',null,m.status==='locked'?(Ml(state)<m.keep?'Keep '+m.keep+' required':'Requirements needed'):m.status==='claimable'?'Reward ready':m.status==='complete'?'Completed':m.type==='city'?'City chapter':'Tactical expedition')))),swElement('button',{className:'sw-mission-choice '+era.status,'aria-pressed':viewingEra,onClick:()=>{setSelected('era');setMessage('')}},swElement('span',{className:'sw-mission-number'},swElement(oe,{size:17})),swElement('span',null,swElement('strong',null,era.title),swElement('small',null,era.status==='complete'?'Medieval age complete':'Keep 10 finale')))),
   viewingEra?swElement(SWMissionPane,{className:'sw-mission-detail sw-era-pane'},swElement('div',{className:'sw-adventure-heading'},swElement('span',{className:'sw-eyebrow'},'The medieval age'),swElement('h3',null,era.title),swElement('p',null,era.description)),era.status==='complete'?swElement(C.Fragment,null,swElement(SWStoryLines,{lines:era.storyAfter}),swElement('p',{className:'sw-mastery'},'Optional mastery: '+era.mastery.districts+'/'+era.mastery.districtTarget+' districts · '+era.mastery.stories+'/'+era.mastery.storyTarget+' stories · '+era.mastery.trials+'/'+era.mastery.trialTarget+' trials')):requirements(era.requirements),swElement('div',{className:'sw-adventure-reward'},swElement('small',null,era.status==='complete'?'Age reward collected':'Completion reward'),swElement(SWPremiumRewardView,{reward:era.reward})),era.status!=='complete'&&swElement('div',{className:'sw-adventure-actions'},swElement('button',{className:'primary',disabled:busy||era.status!=='claimable',onClick:()=>perform({type:'claimEraFinale'},'The medieval age is complete')},era.status==='claimable'?'Complete the age':'Continue your kingdom'))):swElement(SWMissionPane,{className:'sw-mission-detail'},
    swElement('div',{className:'sw-adventure-heading'},swElement(SWIllustration13,{index:mission.id==='blockade'||mission.id==='escort'?1:mission.id==='rescue'?2:mission.id==='harbor'?3:0,className:'sw-mission-cover13'}),swElement('span',{className:'sw-eyebrow'},Oc[mission.characterId]?.name||'The Broken Beacon'),swElement('h3',null,mission.title),swElement('p',null,mission.summary)),
    swElement('div',{className:'sw-mission-objective'},swElement(j,{size:18}),swElement('strong',null,mission.objective)),mission.id==='causeway'&&swElement('p',{className:'sw-muted'},'Connect a road from the Keep to the promenade at the western edge.'),requirements(mission.requirements),
    swElement('details',{className:'sw-mission-lore14'},swElement('summary',null,'Story & dialogue'),swElement(SWStoryLines,{lines:mission.status==='complete'||mission.status==='claimable'?mission.storyAfter:mission.storyBefore})),
    mission.record&&swElement('p',{className:'sw-record'},'Completed'+(mission.record.bestSeconds?' · Best '+Math.round(mission.record.bestSeconds)+'s':'')),
    swElement('div',{className:'sw-adventure-reward'},swElement('small',null,mission.status==='complete'?'Reward collected':'Mission reward'),mission.status==='complete'?swElement('span',{className:'sw-collected-brief'},mission.reward.gems+' gems'+(mission.reward.cosmetics?.length?' · '+mission.reward.cosmetics.length+' wardrobe pieces':'')):swElement(SWPremiumRewardView,{reward:mission.reward})),
    swElement('div',{className:'sw-adventure-actions'},mission.status==='claimable'?swElement('button',{className:'primary',disabled:busy,onClick:()=>perform({type:'claimMission',id:mission.id},'Mission rewards collected')},'Claim reward'):
      mission.status==='locked'?swElement('button',{className:'primary',disabled:true},'Complete the requirements'):
      mission.type==='battle'?swElement('button',{className:'primary',disabled:busy||!!state.activeBattle,onClick:()=>onStart(SWMissionScout(state,mission.id))},mission.status==='complete'?'Replay expedition':'Prepare expedition'):
      mission.status==='available'?swElement('button',{className:'primary',disabled:busy||!!state.activeBattle,onClick:()=>perform({type:'advanceMission',id:mission.id},mission.title+' complete')},'Complete chapter'):swElement('span',{className:'sw-complete-label'},swElement(O,{size:16}),'Chapter complete'),
      mission.type==='city'&&mission.status==='available'&&mission.cost&&swElement(Ku,{cost:mission.cost,available:state.resources})),
    mission.type==='battle'&&swElement('p',{className:'sw-muted'},'A supplied expedition force. Your home army and fleet stay safe.'),
    finished&&swElement('section',{className:'sw-chapter-finale'},swElement(Ee,{size:24}),swElement('strong',null,chapter.claimed?'The beacon shines for your kingdom':'The coast is yours again'),swElement('p',null,'The restored lighthouse, veteran voyages, and new trials remain in your kingdom.'),!chapter.claimed&&swElement('button',{className:'primary',disabled:busy,onClick:()=>perform({type:'claimChapter'},'The Broken Beacon completed · 25 gems')},'Celebrate · claim 25 gems')),
    )),
  tab==='Trials'&&swElement('div',{className:'sw-adventure-cards'},swElement('p',{className:'sw-adventure-intro'},'Short, repeatable tests with a supplied army. Beat the objective to earn each reward once, then improve your best time.'),trials.map(trial=>{const report=reports.find(r=>r.input?.saga?.trialId===trial.id);return swElement('article',{className:'sw-trial-card',key:trial.id},swElement('div',{className:'sw-trial-heading'},swElement(Ee,{size:25}),swElement('div',null,swElement('h3',null,trial.title),swElement('p',null,trial.description))),swElement('strong',{className:'sw-trial-objective'},trial.objective),swElement('div',{className:'sw-trial-footer'},swElement('span',null,trial.status==='complete'?'Best '+Math.round(trial.best?.bestSeconds||0)+'s':trial.reason||'Reward · '+trial.reward.gems+' gems'),swElement('button',{className:'primary',disabled:busy||trial.status==='locked'||!!state.activeBattle,onClick:()=>onStart(SWMissionScout(state,trial.missionId,trial.id))},trial.status==='complete'?'Try again':'Begin trial'),report&&swElement('button',{className:'secondary',onClick:()=>onReplay(report)},'Replay')))})),
  tab==='Residents'&&swElement('div',{className:'sw-adventure-layout sw-resident-stories'},
   swElement('nav',{className:'sw-mission-list','aria-label':'Resident stories'},stories.map((s,index)=>swElement('button',{key:s.id,'aria-pressed':story.id===s.id,className:'sw-mission-choice '+s.status,onClick:()=>{setStoryId(s.id);setMessage('')}},swElement('span',{className:'sw-mission-number'},s.status==='complete'?swElement(O,{size:17}):index+1),swElement('span',null,swElement('strong',null,s.title),swElement('small',null,s.status==='building'?Qc(Math.max(0,(s.readyAt-Date.now())/1000)):s.status==='claimable'?'Ready to welcome':s.status==='locked'?'Keep '+s.keep:s.status==='complete'?'Story complete':'Choose an approach'))))),
   story&&swElement(SWMissionPane,{className:'sw-mission-detail'},swElement('span',{className:'sw-eyebrow'},Oc[story.characterId]?.name||'Your residents'),swElement('h3',null,story.title),swElement('p',null,story.description),requirements(story.requirements),
    story.status==='complete'?swElement('blockquote',{className:'sw-story-ending'},story.ending):story.status==='building'?swElement('div',{className:'sw-story-working'},swElement(k,{size:23}),swElement('strong',null,'Your residents are at work'),swElement('p',null,Qc(Math.max(0,(story.readyAt-Date.now())/1000))+' remaining. You can leave this page.')):story.status==='claimable'?swElement(C.Fragment,null,swElement('blockquote',{className:'sw-story-ending'},story.ending),swElement('button',{className:'primary',disabled:busy,onClick:()=>perform({type:'claimResidentStory',id:story.id},story.title+' completed')},'Welcome them home')):
    swElement(C.Fragment,null,swElement('div',{className:'sw-story-choices','aria-label':'Choose an approach'},story.choices.map(option=>swElement('button',{key:option.id,'aria-pressed':selectedChoice.id===option.id,onClick:()=>setChoice(option.id)},swElement('strong',null,option.label),swElement('p',null,option.description),swElement(Ku,{cost:option.cost,available:state.resources})))),swElement('button',{className:'primary wide',disabled:busy||story.status==='locked'||storyBusy||!Z(state,selectedChoice.cost),onClick:()=>perform({type:'startResidentStory',id:story.id,choice:selectedChoice.id},'Your residents have started')},story.status==='locked'?'Complete the requirements':storyBusy?'Finish the active story first':'Begin · '+Qc(story.duration))),
    swElement('div',{className:'sw-adventure-reward'},swElement('small',null,story.status==='complete'?'Reward collected':'Story reward'),swElement(SWPremiumRewardView,{reward:story.reward})))),
  tab==='Events'&&swElement('div',{className:'sw-event-tracks'},swElement('p',{className:'sw-adventure-intro'},'Finish these celebrations at your own pace. Earn each milestone once. Your progress stays yours.'),events.map(event=>swElement('article',{className:'sw-event-card',key:event.id},swElement(SWIllustration13,{index:event.id==='harbor-festival'?3:event.id==='siege-trials'?6:0,className:'sw-event-cover13'}),swElement('div',{className:'sw-event-heading'},swElement('div',null,swElement('span',{className:'sw-eyebrow'},event.completed?'Celebration complete':event.featured?'Featured this week':'Kingdom celebration'),swElement('h3',null,event.title)),swElement('strong',null,event.progress+' / '+event.target)),swElement('p',null,event.description),swElement('progress',{max:event.target,value:Math.min(event.progress,event.target),'aria-label':event.title+' progress'}),swElement('div',{className:'sw-event-tiers'},event.tiers.map(tier=>swElement('section',{key:tier.id,className:tier.claimed?'claimed':''},swElement('span',null,'Milestone '+tier.target),swElement(SWPremiumRewardView,{reward:tier.reward}),swElement('button',{className:tier.claimable?'primary':'secondary',disabled:busy||!tier.claimable,onClick:()=>perform({type:'claimEvent',id:event.id,tier:tier.id},'Celebration reward collected')},tier.claimed?'Collected':tier.claimable?'Claim reward':'In progress'))))))),
  message&&swElement('div',{className:'sw-adventure-feedback',role:'status'},swElement(O,{size:18}),swElement('span',null,message),swElement('button',{'aria-label':'Dismiss reward message',onClick:()=>setMessage('')},swElement(je,{size:16}))),
  swElement('div',{className:'sw-adventure-bottom'},swElement('button',{className:'text-button',onClick:()=>navigate('frontier')},'Campaign & provinces',swElement(re,{size:14})),swElement('button',{className:'text-button',onClick:()=>navigate('wardrobe')},'Your wardrobe',swElement(re,{size:14}))));
}
// End Stonewake premium interface.
