var J = {
    infantry: {
      name: `Infantry`,
      description: `Durable frontline soldiers.`,
      cost: { gold: 12, wood: 0, stone: 0, food: 18 },
      hp: 115,
      damage: 13,
      range: 0.85,
      speed: 1.1,
      cooldown: 1,
      unlock: 1,
      icon: `shield`,
    },
    archer: {
      name: `Archers`,
      description: `Attack safely behind the frontline.`,
      cost: { gold: 18, wood: 8, stone: 0, food: 20 },
      hp: 64,
      damage: 12,
      range: 2.65,
      speed: 1,
      cooldown: 1.2,
      unlock: 1,
      icon: `bow`,
    },
    cavalry: {
      name: `Cavalry`,
      description: `Fast, strong attackers for exposed defenses.`,
      cost: { gold: 38, wood: 0, stone: 0, food: 38 },
      hp: 170,
      damage: 21,
      range: 0.85,
      speed: 1.8,
      cooldown: 1.1,
      unlock: 2,
      icon: `horse`,
    },
    cannon: {
      name: `Cannons`,
      description: `Slow siege artillery. Double damage to structures.`,
      cost: { gold: 55, wood: 20, stone: 15, food: 25 },
      hp: 75,
      damage: 21,
      range: 3.5,
      speed: 0.58,
      cooldown: 2,
      unlock: 2,
      icon: `cannon`,
    },
    ...xc,
  };