// One compact screen language for preparation, progression and the harbor.
function SWPanelSwitcher(){return null;}
function iu({open,onOpenChange,state,act,busy}){
 const [id,setId]=C.useState(state.commander||'captain');C.useEffect(()=>{if(open)setId(state.commander||'captain')},[open]);
 const person=Oc[id],owned=Wc(state,id),level=owned?Math.min(10,1+Math.floor(owned.xp/160)):1,leading=(state.commander||'captain')===id,locked=Ml(state)<person.unlock;
 return swElement(SWDialog,{open,onClose:()=>onOpenChange(false),title:'Commanders',subtitle:'Choose one leader and their equipment.',className:'sw-commanders14'},swElement('nav',{className:'sw-commanders-list14','aria-label':'Commanders'},Object.keys(Oc).map(key=>swElement('button',{key,'aria-label':'View '+Oc[key].name,'aria-pressed':id===key,onClick:()=>setId(key)},swElement(nu,{id:key}),swElement('span',null,swElement('strong',null,Oc[key].name.split(' ')[0]),swElement('small',null,(state.commander||'captain')===key?'Leading':Ml(state)<Oc[key].unlock?'Keep '+Oc[key].unlock:Oc[key].title))))),swElement('div',{className:'sw-commander-columns14'},swElement('section',{className:'sw-commander-profile14'},swElement('div',{className:'sw-commander-reading14'},swElement('div',{className:'sw-commander-intro14'},swElement(nu,{id,action:true}),swElement('div',null,swElement('small',null,'LEVEL '+level+' · '+person.title),swElement('h3',null,person.name),swElement('strong',null,person.ability),swElement('p',null,person.description))),owned&&swElement('div',{className:'sw-commander-xp14'},swElement('span',null,level===10?'Medieval mastery':owned.xp%160+' / 160 XP to level '+(level+1)),swElement('progress',{max:160,value:level===10?160:owned.xp%160,'aria-label':'Commander experience'}))),swElement('button',{className:'primary wide',disabled:busy||!!state.activeBattle||locked||leading||(!owned&&!Z(state,{gold:200,wood:0,stone:0,food:80})),onClick:()=>act({type:'commander',id},person.name+' leads your army')},locked?'Keep '+person.unlock+' required':leading?'Leading your army':owned?'Make commander':'Recruit · 200 gold + 80 food')),swElement('section',{className:'sw-commander-gear14'},swElement('h3',null,'Equipment'),owned?Object.keys(kc).map(key=>{const item=kc[key],equipped=owned.gear===key,have=owned.owned.includes(key);return swElement('button',{key,'aria-pressed':equipped,disabled:busy||!!state.activeBattle||equipped||(!have&&!Z(state,item.cost)),onClick:()=>act({type:'gear',id,gear:key},item.name+' equipped')},swElement(key==='blade'?we:key==='armor'?be:se,{size:24}),swElement('span',null,swElement('strong',null,item.name),swElement('small',null,item.description)),swElement('span',null,equipped?'Equipped':have?'Equip':swElement(Ku,{cost:item.cost,available:state.resources})))}):swElement('p',null,'Recruit this commander to choose their equipment.'))));
}
function SWDialog({open,onClose,title,subtitle,className='',children}){
 const navigate=C.useContext(SWNavigationContext);
 return swElement(As,{open,onOpenChange:value=>{if(!value)onClose()}},open&&swElement(Ns,{className:'game-dialog sw-dialog sw-screen14 '+className},swElement(Ps,null,navigate?.canGoBack&&swElement('button',{className:'sw-back14','aria-label':'Back to previous screen',onClick:()=>navigate('back')},'‹ Back'),swElement(Fs,null,title),swElement(Is,{className:subtitle?'':'sr-only'},subtitle||title)),swElement('div',{className:'sw-body'},children)));
}
function SWMainMenu({state,navigate,battle,sound,onSound,rewards}){
 return swElement('aside',{className:'kingdom-menu sw-menu14','aria-label':'Kingdom navigation'},swElement('header',null,swElement('strong',null,state.name),swElement('span',null,'Keep '+Ml(state)+' · Medieval realm')),swElement('nav',{className:'sw-destinations14'},[['capital','Village',ne],['army','Army',we],['frontier','Battle',j],['fleet','Harbor',xe]].map(([id,name,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),disabled:battle},swElement(Icon,{size:23}),name))),swElement('nav',{className:'sw-utilities14'},[['chronicle','Journal',ve],['city','City life',Te],['plan','Layout mode',_e],['storage','Storage',A],['store','Shop',M],['wardrobe','Customize',oe],['settings','Settings',ye]].map(([id,name,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),disabled:battle&&['plan','city'].includes(id)},swElement(Icon,{size:17}),name,id==='chronicle'&&rewards>0&&swElement('small',null,rewards)))),swElement('button',{className:'sw-menu-sound',onClick:onSound},swElement(sound?Oe:ke,{size:16}),sound?'Sound on':'Sound off'));
}
function SWQuickNav({navigate,current,state}){
 return swElement('nav',{className:'sw-quick-nav sw-quick14','aria-label':'Village actions'},swElement('button',{'aria-label':'Build',onClick:()=>navigate('build')},swElement(N,{size:19}),'Build'),swElement('button',{className:'sw-battle-primary14','aria-label':'Battle',onClick:()=>navigate('frontier')},swElement(we,{size:19}),'Battle'));
}
function SWBuildMenu14({state,busy,category,onCategory,onBuild,onClose}){
 const groups={town:['cottage','market','well','workshop','tavern','harbor','builder','monument'],resources:['storehouse','farm','lumber','quarry'],army:['barracks','forge','tower','wall','gate',...Cc]},keep=state.buildings.find(b=>b.kind==='keep'),needsStorage=keep&&SWUpgradeQuote14(state,keep).requirements.some(r=>!r.met&&r.action?.kind==='storehouse');
 const kinds=Object.keys(Sl).filter(kind=>kind!=='keep'&&(category==='all'||groups[category]?.includes(kind))).sort((a,b)=>(needsStorage&&a==='storehouse'?-1:0)-(needsStorage&&b==='storehouse'?-1:0));
 return swElement(SWDialog,{open:true,onClose,title:'Build your village',subtitle:Rc(state)+' construction crews available',className:'sw-build-menu14'},swElement('nav',{className:'sw-tabs','aria-label':'Building categories'},[['all','All'],['town','Town'],['resources','Resources'],['army','Military']].map(([id,label])=>swElement('button',{key:id,'aria-pressed':category===id,onClick:()=>onCategory(id)},label))),needsStorage&&category==='all'&&swElement('p',{className:'sw-build-tip14'},'A second Storehouse makes room for your next Keep upgrade.'),swElement('div',{className:'sw-build-grid14'},kinds.map(kind=>swElement(SWBuildCard,{key:kind,kind,state,busy,onBuild}))));
}
function SWJournalReports14({reports,onReplay}){
 return swElement('section',{className:'sw-journal-reports14'},reports.length?reports.map(report=>swElement('button',{key:report.id,className:'sw-report14',onClick:()=>onReplay(report)},swElement(report.defending?be:report.kind==='sea'?xe:we,{size:25}),swElement('span',null,swElement('strong',null,report.input?.defense?.name||'Kingdom defense'),swElement('small',null,(report.defending?'Defense':report.kind==='sea'?'Sea campaign':report.input?.saga?'Chapter expedition':'Land battle')+' · '+Math.round(report.result?.destruction||0)+'% damage')),swElement('b',null,report.defending?(report.result?.won?'Breach':'Held'):(report.result?.won?'Victory':'Review')),swElement(re,{size:18}))):swElement('p',{className:'sw-empty'},'Your next battle will appear here with its replay.'));
}
function SWRequirements14({quote,onRequirement}){
 return swElement('ul',{className:'sw-requirements14'},quote.requirements.filter(r=>!r.met).map(r=>swElement('li',{key:r.id,className:r.met?'met':'needed'},swElement(r.met?O:be,{size:16}),swElement('span',null,r.text),!r.met&&r.action&&swElement('button',{className:'secondary',onClick:()=>onRequirement(r.action)},r.action.type==='build'?'Build storehouse':r.action.type==='storage'?'View supplies':r.action.type==='land'?'Land campaign':r.action.type==='projects'?'View projects':'Go to '+Sl[r.action.kind].name))));
}
function SWBuildingDetails14({state,building,busy,layout=false,act,onClose,onMove,onRequirement,onBack}){
 const q=SWUpgradeQuote14(state,building),level=building.level||building.targetLevel||1;
 if(layout)return swElement('aside',{className:'sw-building14 sw-layout-details14','aria-label':Sl[building.kind].name+' layout'},swElement('header',null,swElement('div',null,swElement('h2',null,Sl[building.kind].name),swElement('span',null,'Level '+level+' · Facing '+(building.facing||0)*90+'°')),swElement('button',{className:'icon-btn','aria-label':'Close building details',onClick:onClose},swElement(je,{size:20}))),swElement('footer',null,swElement('button',{className:'primary',onClick:onMove},'Move building'),swElement('button',{className:'secondary',onClick:()=>act({type:'rotate',id:building.id},'Building rotated')},'Rotate 90°')));
 return swElement('aside',{className:'sw-building14','aria-label':Sl[building.kind].name+' details'},swElement('header',null,onBack&&swElement('button',{className:'icon-btn','aria-label':'Back to previous building',onClick:onBack},'‹'),swElement('div',null,swElement('small',null,'VILLAGE'),swElement('h2',null,Sl[building.kind].name),swElement('span',null,'Level '+level+(building.readyAt?' · Developing':''))),swElement('button',{'aria-label':'Close building details',className:'icon-btn',onClick:onClose},swElement(je,{size:20}))),swElement('div',{className:'sw-building-scroll14'},swElement('div',{className:'sw-evolution14'},swElement('div',null,swElement(qu,{kind:building.kind,level,large:true}),swElement('strong',null,'Now · '+level)),level<10&&swElement(C.Fragment,null,swElement(re,{size:20}),swElement('div',null,swElement(qu,{kind:building.kind,level:level+1,large:true}),swElement('strong',null,'Next · '+(level+1))))),swElement('p',{className:'sw-benefit14'},Bl(building)),building.readyAt?swElement('p',{className:'sw-project-status14'},'Ready in '+Qc(Math.max(0,(building.readyAt-Date.now())/1000))):level<q.max&&swElement(C.Fragment,null,swElement('p',null,swElement('strong',null,'Next: '),q.benefit),swElement(Ku,{cost:q.cost,available:state.resources}),swElement(SWRequirements14,{quote:q,onRequirement})),swElement('details',null,swElement('summary',null,'All ten visual stages'),swElement('div',{className:'sw-level-gallery14'},Array.from({length:10},(_,i)=>swElement('div',{key:i},swElement(qu,{kind:building.kind,level:i+1}),swElement('small',null,'Level '+(i+1))))))),swElement('footer',null,swElement('button',{className:'secondary',onClick:onMove},'Move'),swElement('button',{className:'secondary',onClick:()=>act({type:'rotate',id:building.id},'Building rotated')},'Rotate'),building.readyAt?swElement('button',{className:'primary',onClick:()=>onRequirement({type:'projects'})},'View project'):swElement('button',{className:'primary',disabled:busy||!q.allowed,onClick:()=>act({type:'upgrade',id:building.id},'Upgrade started')},level>=q.max?'Mastered':'Upgrade · '+Qc(q.duration))));
}
function SWCampaignBoard14({state,sea=false,onScout,onHarbor}){
 const items=sea?SWSeaChapters14:Tl,progress=sea?state.seaCampaign:state.campaign;
 const chapters=items.map((item,index)=>({item,index})).sort((a,b)=>(a.index<progress?1:0)-(b.index<progress?1:0)||a.index-b.index);
 return swElement('div',{className:'sw-campaign14'},swElement('div',{className:'sw-campaign-intro14'},swElement('div',null,swElement('span',{className:'sw-eyebrow'},sea?'THE TIDEBORN CAMPAIGN':'THE KING’S ROAD'),swElement('h2',null,sea?'Rule the coast':'Take the overland road'),swElement('p',null,sea?'Load your force. Choose your beaches. Keep your transports safe.':'Choose your force and deploy directly along the enemy perimeter.')),swElement('strong',null,progress+' / '+items.length),sea&&swElement('button',{className:'secondary',onClick:onHarbor},'Prepare fleet')),
 swElement('div',{className:'sw-chapter-grid14'},chapters.map(({item,index})=>{const done=index<progress,locked=index>progress||(sea&&Ml(state)<item.keep);return swElement('button',{key:index,className:'sw-chapter14'+(done?' complete':'')+(locked?' locked':''),'aria-label':item.name+(locked?', locked':done?', completed':''),onClick:()=>{if(!locked)onScout({kind:sea?'sea':'campaign',campaignIndex:index,defense:sea?SWSeaDefense14(index):Gl(index),objective:sea?item.objective:'Capture the keep.'})},disabled:locked},swElement('span',{className:'sw-chapter-number14'},done?swElement(O,{size:18}):index+1),swElement('div',null,swElement('strong',null,item.name),swElement('small',null,locked?(index>progress?'Complete the previous chapter':'Keep '+item.keep+' required'):done?'Captured · replay available':sea?'Next · '+item.title:'Next chapter · Land stronghold')),swElement(sea?xe:we,{size:23}));})));
}
function SWAbilitySummary({kind,level}){
 const all=SWTroopAbilities(kind),active=all.filter(a=>a.level<=level),next=all.find(a=>a.level>level);
 return swElement('section',{className:'sw-skills14'},active.map(a=>swElement('p',{key:a.name},swElement(O,{size:15}),swElement('span',null,swElement('strong',null,a.name+' · '),a.description))),next&&swElement('p',{className:'upcoming'},swElement(oe,{size:15}),swElement('span',null,swElement('strong',null,'Level '+next.level+': '+next.name+' · '),next.description)));
}
function SWArmy({open,onClose,state,act,busy,onFrontier,onCommander,onPractice}){
 const [familyId,setFamily]=C.useState('vanguard'),[selected,setSelected]=C.useState('infantry'),[mode,setMode]=C.useState('Force'),[count,setCount]=C.useState(1),[draft,setDraft]=C.useState(null);
 const family=SWFamilies14.find(f=>f.id===familyId),force=draft||SWLoadout14(state),kind=family.kinds.includes(selected)?selected:force.slots.find(k=>family.kinds.includes(k))||family.default,level=el(state,kind),stats=SWTroopStats14(state,kind,level),next=SWTroopStats14(state,kind,Math.min(10,level+1));
 const train=SWTrainQuote14(state,force),research=state.trainingResearch,cost=tl(state,kind),ready=force.slots.includes(kind),capacity=Pl(state),owned=Nl(state.army),keep=Ml(state),troop=J[kind],singleTrain=SWTrainQuote14(state,{slots:[kind],counts:{[kind]:(state.army[kind]||0)+count}});
 C.useEffect(()=>{if(open){setDraft(null);setSelected(SWLoadout14(state).slots.find(k=>SWFamily14(k)?.id===familyId)||family.default)}},[open]);
 const choose=type=>{setSelected(type);if(mode==='Force'){const existing=force.slots.find(k=>family.kinds.includes(k)),slots=existing?force.slots.map(k=>k===existing?type:k):[...force.slots,type];setDraft({...force,slots,counts:{...force.counts,[type]:force.counts[type]??Math.min(state.army[type]||0,6)}})}};
 const save=async()=>{const result=await act({type:'saveLoadout',loadout:force},'Force saved');if(result)setDraft(null);return result};
 const total=force.slots.reduce((n,k)=>n+(force.counts[k]||0),0);
 return swElement(SWDialog,{open,onClose,title:'Army',subtitle:owned+' / '+capacity+' troops · Six families, one chosen doctrine each',className:'sw-army14'},swElement('nav',{className:'sw-tabs','aria-label':'Army sections'},['Force','Train','Upgrade'].map(tab=>swElement('button',{key:tab,'aria-pressed':mode===tab,onClick:()=>setMode(tab)},tab))),swElement('div',{className:'sw-roster14'},swElement('nav',{className:'sw-family-list14','aria-label':'Troop families'},SWFamilies14.map(f=>swElement('button',{key:f.id,'aria-pressed':familyId===f.id,onClick:()=>{setFamily(f.id);setSelected(force.slots.find(k=>f.kinds.includes(k))||f.default)}},swElement(lu,{kind:force.slots.find(k=>f.kinds.includes(k))||f.default,level:el(state,force.slots.find(k=>f.kinds.includes(k))||f.default)}),swElement('strong',null,f.name),swElement('small',null,force.slots.filter(k=>f.kinds.includes(k)).reduce((n,k)=>n+(force.counts[k]||0),0)+' in force')))),swElement('section',{className:'sw-unit-pane14'},swElement('header',null,swElement('div',null,swElement('h3',null,family.name),swElement('p',null,family.role)),swElement('label',{className:'sw-field'},'Doctrine',swElement('select',{'aria-label':'Troop doctrine',value:kind,onChange:e=>choose(e.target.value)},family.kinds.map(k=>swElement('option',{key:k,value:k,disabled:J[k].unlock>keep},J[k].name+(J[k].unlock>keep?' · Keep '+J[k].unlock:'')))))),
 mode==='Upgrade'?swElement(C.Fragment,null,swElement('div',{className:'sw-troop-comparison14'},[level,...(level<10?[level+1]:[])].map(lv=>swElement('div',{key:lv},swElement(SWUnitPreview14,{kind,level:lv,animate:true}),swElement('strong',null,(lv===level?'Current':'Next')+' · '+lv),swElement('p',null,SWEquipmentName14(kind,lv))))),swElement('div',{className:'sw-stat-deltas14'},[['Health',stats.hp,next.hp],['healer'===kind?'Healing':'Attack',kind==='healer'?stats.heal:stats.damage,kind==='healer'?next.heal:next.damage],['Range',stats.range,next.range],['Attack interval',stats.cooldown,next.cooldown]].map(([label,a,b])=>swElement('div',{key:label},swElement('span',null,label),swElement('strong',null,(Math.round(a*10)/10)+(level<10?' → '+Math.round(b*10)/10:''))))),swElement('small',{className:'sw-muted'},'Attack includes '+Math.round((stats.townBonus-1)*100)+'% from your town.'),swElement(SWAbilitySummary,{kind,level}),swElement('div',{className:'sw-action-row14'},level<10&&swElement(Ku,{cost,available:state.resources}),swElement('button',{className:'primary',disabled:busy||!!research||level>=keep||level>=10||!Z(state,cost),onClick:()=>act({type:'researchUnit',kind},'Troop upgrade started')},research?'Research · '+Qc(Math.max(0,(research.readyAt-Date.now())/1000)):level>=10?'Medieval mastery':level>=keep?'Keep '+(level+1)+' needed':'Upgrade to '+(level+1)),onPractice&&swElement('button',{className:'secondary',onClick:()=>onPractice(kind)},'Practice'))):
 mode==='Train'?swElement(C.Fragment,null,swElement(SWUnitPreview14,{kind,level,animate:true}),swElement('h3',null,troop.name+' · Level '+level),swElement('p',null,SWEquipmentName14(kind,level)),swElement('div',{className:'sw-action-row14'},swElement('label',null,'Quantity ',swElement('select',{'aria-label':'Training quantity',value:count,onChange:e=>setCount(Number(e.target.value))},[1,5,10].map(n=>swElement('option',{key:n,value:n},n)))),swElement(Ku,{cost:Object.fromEntries(xl.map(k=>[k,troop.cost[k]*count])),available:state.resources})),swElement('button',{className:'primary wide',disabled:busy||!singleTrain.allowed,onClick:()=>act({type:'recruit',kind,count},'Troops ready')},singleTrain.reason||('Train '+count+' '+troop.name)),swElement(SWAbilitySummary,{kind,level})):
 swElement(C.Fragment,null,swElement('div',{className:'sw-force-summary14'},swElement('label',{className:'sw-field'},'Saved force',swElement('select',{'aria-label':'Saved force',value:force.id,onChange:e=>{setDraft(null);act({type:'selectLoadout',id:e.target.value})}},state.loadouts14.map(l=>swElement('option',{key:l.id,value:l.id},l.name)))),swElement('strong',null,total+' / '+capacity)),swElement('label',{className:'sw-field'},'Force name',swElement('input',{value:force.name,maxLength:24,onChange:e=>setDraft({...force,name:e.target.value})})),swElement('div',{className:'sw-force-count14'},swElement(lu,{kind,level}),swElement('div',null,swElement('strong',null,troop.name),swElement('p',null,(state.army[kind]||0)+' ready · '+SWTroopWeight14(kind)+' cargo space each')),swElement('input',{type:'number',min:0,max:capacity,'aria-label':troop.name+' in force',value:force.counts[kind]||0,onChange:e=>{const counts={...force.counts,[kind]:Math.max(0,Math.min(capacity,Math.trunc(Number(e.target.value)||0)))},existing=force.slots.find(k=>family.kinds.includes(k));setDraft({...force,counts,slots:existing?force.slots.map(k=>k===existing?kind:k):[...force.slots,kind]})}})),swElement('p',{className:'sw-muted'},'Unused troops stay home. Save a force, then train any missing troops together.'),swElement(Ku,{cost:train.cost,available:state.resources}),swElement('div',{className:'sw-action-row14'},swElement('button',{className:'primary',disabled:busy||!draft||total>capacity,onClick:save},'Save force'),swElement('button',{className:'secondary',disabled:busy||!!draft||!train.allowed,onClick:()=>act({type:'trainLoadout'},'Your force is ready')},train.count?'Train missing · '+train.count:'Force ready'),swElement('button',{className:'secondary',disabled:busy||state.loadouts14.length>=3,onClick:()=>setDraft({...force,id:'force-'+(state.loadouts14.length+1),name:'Force '+(state.loadouts14.length+1)})},'New force')),train.reason&&train.count>0&&swElement('p',{className:'sw-muted'},train.reason)),
 swElement('footer',{className:'sw-army-footer14'},swElement('button',{className:'secondary',onClick:onCommander},'Commander'),swElement('button',{className:'primary',disabled:!!draft||Nl(SWSelectedArmy14(state))<3,onClick:onFrontier},'Choose battle')))));
}
function SWUnitPreview14({kind,level=1,animate=false}){
 const ref=C.useRef(null);C.useEffect(()=>{let frame,live=true,start=performance.now();const draw=now=>{const canvas=ref.current;if(!live||!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,240,150);SWDrawTroopRig14(ctx,{kind,level,x:120,y:134,scale:2.7,heading:-.8,phase:((now-start)/1400)%1,state:animate?'attack':'idle',enemy:false});if(animate)frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>{live=false;cancelAnimationFrame(frame)}},[kind,level,animate]);return swElement('canvas',{ref,width:240,height:150,className:'sw-unit-preview14',role:'img','aria-label':J[kind]?.name+' level '+level+' · '+SWEquipmentName14(kind,level)});
}
function SWScout({open,onClose,scout,state,busy,onAttack,onTrain,onPreparation}){
 const sea=scout?.kind==='sea',supplied=!!scout?.fixedArmy,[ids,setIds]=C.useState([]),[army,setArmy]=C.useState(null),[cargo,setCargo]=C.useState(null),[view,setView]=C.useState('Force');
 C.useEffect(()=>{if(open&&scout){const force=SWSelectedArmy14(state),ships=SWReadyFleet14(state).sort((a,b)=>SWShipCapacity14(b)-SWShipCapacity14(a)).slice(0,SWFleetLimit14(state)).map(s=>s.id);setArmy(force);setIds(ships);setCargo(null);setView('Force')}},[open,scout?.kind,scout?.campaignIndex,scout?.missionId]);
 const chosen=army||SWSelectedArmy14(state),packed=SWPackCargo14(state,ids,chosen),manifest=cargo||packed.fleet,remaining=Object.keys(J).reduce((n,k)=>n+Math.abs((chosen[k]||0)-manifest.reduce((a,s)=>a+(s.cargo[k]||0),0)),0),selectedArmy=supplied?scout?.army:chosen;
 C.useEffect(()=>{onPreparation?.({army:chosen,fleet:manifest})},[army,ids,cargo,open]);
 if(!scout)return null;
 const ready=SWReadyFleet14(state),hold=scout.mode==='hold',total=Nl(selectedArmy||{}),seaBlocked=sea&&(!ids.length||remaining>0||manifest.some(s=>Object.entries(s.cargo).reduce((n,[k,v])=>n+v*SWTroopWeight14(k),0)>SWShipCapacity14(s))),chap=sea?SWSeaChapters14[scout.campaignIndex]:null;
 const setCount=(kind,value)=>{setArmy({...chosen,[kind]:Math.max(0,Math.min(state.army[kind]||0,Math.trunc(Number(value)||0)))});setCargo(null)};
 return swElement(SWDialog,{open,onClose,title:scout.defense.name,subtitle:sea?'Sea campaign · '+chap.title:supplied?'Supplied expedition':'Land campaign · Direct deployment',className:'sw-scout14'},swElement('div',{className:'sw-scout-layout14'},swElement('section',{className:'sw-scout-map14'},swElement(Eu,{buildings:scout.defense.buildings,enemy:true,navalSupport:sea?{id:'preview',kind:'cog',level:1}:null,battleInput14:sea?{campaignType:'sea',defense:scout.defense}:null}),swElement('p',null,scout.objective||'Capture the keep.')),swElement('section',{className:'sw-preparation14'},
 sea&&swElement('nav',{className:'sw-tabs'},['Force','Fleet','Cargo'].map(tab=>swElement('button',{key:tab,'aria-pressed':view===tab,onClick:()=>setView(tab)},tab))),
 sea&&swElement('div',{className:'sw-cargo-status14'},swElement('strong',null,packed.weight+' / '+packed.capacity+' cargo space'),swElement('span',null,remaining?remaining+' unassigned':'Ready to sail'),remaining>0&&swElement('button',{className:'secondary',onClick:()=>{setArmy(packed.army);setCargo(null)}},'Fit force to ships')),
 swElement('div',{className:'sw-prep-reading14'},
 (!sea||view==='Force')&&swElement(C.Fragment,null,swElement('h3',null,supplied?'Supplied force':SWLoadout14(state).name),swElement('div',{className:'sw-scout-troops14'},(supplied?Object.keys(J).filter(k=>scout.army?.[k]>0):SWLoadout14(state).slots).map(kind=>swElement('label',{key:kind},swElement(lu,{kind,level:state.unitLevels?.[kind]||1}),swElement('span',null,J[kind].name,swElement('small',null,sea?SWTroopWeight14(kind)+' space each':'Level '+el(state,kind))),supplied?swElement('strong',null,scout.army[kind]):swElement('input',{'aria-label':J[kind].name+' to deploy',type:'number',min:0,max:state.army[kind]||0,value:chosen[kind]||0,onChange:e=>setCount(kind,e.target.value)})))),!supplied&&swElement('button',{className:'secondary',onClick:onTrain},'Edit / train force')),
 sea&&view==='Fleet'&&swElement('div',{className:'sw-scout-fleet14'},swElement('p',null,'Choose up to '+SWFleetLimit14(state)+' ships. Transports carry more; escorts keep them alive.'),ready.map(ship=>swElement('button',{key:ship.id,'aria-pressed':ids.includes(ship.id),onClick:()=>{setIds(ids.includes(ship.id)?ids.filter(id=>id!==ship.id):ids.length<SWFleetLimit14(state)?[...ids,ship.id]:ids);setCargo(null)}},swElement(SWShipPreview14,{ship}),swElement('span',null,swElement('strong',null,SWShipRoles14[ship.kind].name),swElement('small',null,'Lv '+ship.level+' · '+SWShipCapacity14(ship)+' space')),swElement(ids.includes(ship.id)?O:xe,{size:18}))),!ready.length&&swElement('p',null,'Your fleet is away or needs repairs. Prepare a vessel in the Harbor.')),
 sea&&view==='Cargo'&&swElement('div',{className:'sw-cargo14'},swElement('p',null,'Assign each troop type to a transport. If it will not fit, split the type between ships below.'),manifest.map(ship=>swElement('section',{key:ship.id},swElement('strong',null,SWShipRoles14[ship.kind].name+' · '+Object.entries(ship.cargo).reduce((n,[k,v])=>n+v*SWTroopWeight14(k),0)+' / '+SWShipCapacity14(ship)),Object.keys(chosen).filter(k=>chosen[k]>0).map(kind=>swElement('label',{key:kind},J[kind].name,swElement('input',{'aria-label':J[kind].name+' on '+SWShipRoles14[ship.kind].name,type:'number',min:0,max:chosen[kind],value:ship.cargo[kind]||0,onChange:e=>setCargo(manifest.map(s=>s.id===ship.id?{...s,cargo:{...s.cargo,[kind]:Math.max(0,Math.min(chosen[kind],Math.trunc(Number(e.target.value)||0)))}}:s))})))))),

 swElement('div',{className:'sw-prep-reward14'},swElement('small',null,'Victory supplies'),swElement(Ku,{cost:sea?(state.seaCampaign>scout.campaignIndex?{gold:35,wood:30,stone:15,food:20}:chap.reward):scout.kind==='campaign'?(state.campaign>scout.campaignIndex?{gold:35,wood:20,stone:15,food:25}:Tl[scout.campaignIndex].reward):{gold:0,wood:0,stone:0,food:0}}))),swElement('div',{className:'sw-prep-footer14'},swElement('button',{className:'primary wide sw-launch14',disabled:busy||(!supplied&&total<3)||seaBlocked,onClick:onAttack},busy?'Preparing…':hold?'Defend harbor':sea?'Sail with '+total+' troops':supplied?'Begin expedition':'Attack with '+total+' troops')))));
}
function SWShipPreview14({ship}){
 const ref=C.useRef(null);C.useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,200,130);SWDrawShipRig14(ctx,{...ship,x:100,y:105,scale:1.4,heading:.4,time:0,side:'attack',hp:1,maxHp:1})},[ship.kind,ship.level]);return swElement('canvas',{ref,width:200,height:130,className:'sw-ship-preview14',role:'img','aria-label':SWShipRoles14[ship.kind]?.name+' level '+ship.level});
}
function SWFleet({open,onClose,state,act,busy,onBuildPort,onViewCoast}){
 const navigate=C.useContext(SWNavigationContext),[tab,setTab]=C.useState('Fleet'),[selected,setSelected]=C.useState(null),[routeId,setRoute]=C.useState('coast'),now=Date.now(),port=rl(state),berths=Math.min(8,port+1),fleet=[...(state.fleet||[])].sort((a,b)=>(a.wrecked?-4:a.voyage?.readyAt<=now?-3:a.repairReadyAt?-2:0)-(b.wrecked?-4:b.voyage?.readyAt<=now?-3:b.repairReadyAt?-2:0)),ship=fleet.find(s=>s.id===selected)||fleet[0],working=fleet.some(s=>s.readyAt||s.repairReadyAt),cost=ship?nl(ship.kind,ship.level+1):{},power=ship?Math.round(wc[ship.kind].power*(1+.22*(ship.level-1))):0,route=Ec.find(r=>r.id===routeId),collectable=fleet.some(s=>s.voyage?.readyAt<=now&&xl.some(k=>s.voyage.reward[k]>0&&state.resources[k]<SWCapacity(state)));
 return swElement(SWDialog,{open,onClose,title:'Harbor',subtitle:port?'Shipyard '+port+' · '+fleet.length+' / '+berths+' berths':'Build your coastal shipyard',className:'sw-harbor14'},swElement('nav',{className:'sw-tabs','aria-label':'Harbor sections'},['Fleet','Shipyard','Routes'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,onClick:()=>setTab(name)},name))),!port&&swElement('button',{className:'primary',onClick:()=>{onClose();onBuildPort()}},'Build shipyard on the coast'),
 tab==='Fleet'?swElement(C.Fragment,null,swElement('div',{className:'sw-harbor-actions14'},swElement('button',{className:'secondary',onClick:()=>{onClose();onViewCoast()}},'View coast'),swElement('button',{className:'secondary',disabled:busy||!collectable,onClick:()=>act({type:'collectFleet'},'Cargo received. Overflow stays aboard.')},'Collect ready cargo'),swElement('button',{className:'primary',onClick:()=>navigate('sea')},'Sea campaign')),
 swElement('div',{className:'sw-harbor-layout14'},swElement('nav',{className:'sw-vessel-list14','aria-label':'Your ships'},fleet.map(s=>swElement('button',{key:s.id,'aria-pressed':s.id===ship?.id,onClick:()=>setSelected(s.id)},swElement(SWShipPreview14,{ship:{...s,level:s.level||1}}),swElement('span',null,swElement('strong',null,SWShipRoles14[s.kind].name),swElement('small',null,s.wrecked?'Needs repair':s.voyage?.readyAt<=now?'Cargo ready':s.voyage?'At sea':s.readyAt?'Upgrading':s.repairReadyAt?'Repairing':'Ready · Level '+s.level))))),ship?swElement('section',{className:'sw-vessel-detail14'},swElement('h3',null,SWShipRoles14[ship.kind].name),swElement('p',null,SWShipRoles14[ship.kind].role),swElement('div',{className:'sw-ship-comparison14'},swElement(SWShipPreview14,{ship:{...ship,level:ship.level||1}}),ship.level<10&&!ship.wrecked&&swElement(SWShipPreview14,{ship:{...ship,level:ship.level+1}})),swElement('div',{className:'sw-stat-deltas14'},[['Cargo',SWShipCapacity14(ship),ship.level<10?SWShipCapacity14({...ship,level:ship.level+1}):null],['Hull',Math.round(SWShipRoles14[ship.kind].hp*(1+.14*(ship.level-1))),ship.level<10?Math.round(SWShipRoles14[ship.kind].hp*(1+.14*ship.level)):null]].map(([label,value,next])=>swElement('div',{key:label},swElement('span',null,label),swElement('strong',null,value+(next?' → '+next:''))))),
 ship.repairReadyAt||ship.readyAt?swElement('p',{className:'sw-project-status14'},(ship.repairReadyAt?'Repairing':'Developing')+' · '+Qc(Math.max(0,((ship.repairReadyAt||ship.readyAt)-now)/1000))):ship.wrecked?swElement(C.Fragment,null,swElement('p',null,'Your ship was recovered. Repair the hull to sail again.'),swElement(Ku,{cost:SWShipRepairCost(ship),available:state.resources}),swElement('button',{className:'primary',disabled:busy||working||!Z(state,SWShipRepairCost(ship)),onClick:()=>act({type:'repairShip',id:ship.id},'Ship repair started')},working?'Shipwright busy':'Repair ship')):ship.combatBattleId?swElement('p',null,'Fighting with your expedition.'):ship.voyage?swElement(C.Fragment,null,swElement('p',null,ship.voyage.readyAt>now?'Returns in '+Qc((ship.voyage.readyAt-now)/1000):'Cargo ready. Any overflow stays safely aboard.'),swElement(Ku,{cost:ship.voyage.reward}),swElement('button',{className:'primary',disabled:busy||ship.voyage.readyAt>now||!xl.some(k=>ship.voyage.reward[k]>0&&state.resources[k]<SWCapacity(state)),onClick:()=>act({type:'collectVoyage',id:ship.id},'Cargo received')},'Collect what fits')):swElement(C.Fragment,null,swElement('div',{className:'sw-action-row14'},swElement('select',{'aria-label':'Voyage route',value:routeId,onChange:e=>setRoute(e.target.value)},Ec.map(r=>swElement('option',{key:r.id,value:r.id,disabled:port<r.unlock||power<r.power},r.name+' · '+Qc(r.duration)))),swElement('button',{className:'secondary',disabled:busy||!route||power<route.power||port<route.unlock,onClick:()=>act({type:'voyage',id:ship.id,kind:routeId},'Ship set sail')},'Trading voyage')),ship.level<10&&swElement(Ku,{cost,available:state.resources}),swElement('button',{className:'primary wide',disabled:busy||working||ship.level>=port||ship.level>=10||!Z(state,cost),onClick:()=>act({type:'upgradeShip',id:ship.id},'Ship upgrade started')},ship.level>=10?'Medieval mastery':ship.level>=port?'Shipyard '+(ship.level+1)+' needed':'Upgrade to level '+(ship.level+1))),ship.level>=port&&ship.level<10&&swElement('button',{className:'text-button',onClick:()=>navigate('harborUpgrade')},'Go to shipyard')):swElement('p',{className:'sw-empty'},'Build a vessel in the Shipyard. A cutter is enough for your first landing.'))):
 tab==='Shipyard'?swElement('div',{className:'sw-ship-catalog14'},Object.entries(SWShipRoles14).map(([kind,type])=>swElement('article',{key:kind},swElement(SWShipPreview14,{ship:{kind,level:1}}),swElement('h3',null,type.name),swElement('p',null,type.role+' · '+type.capacity+' cargo space'),swElement(Ku,{cost:nl(kind),available:state.resources}),swElement('button',{className:'primary wide',disabled:busy||port<wc[kind].unlock||working||fleet.length>=berths||!Z(state,nl(kind)),onClick:()=>act({type:'buildShip',kind},'Ship construction started')},port<wc[kind].unlock?'Shipyard '+wc[kind].unlock+' needed':working?'Shipwright busy':fleet.length>=berths?'More berths needed':'Build · '+Qc(wc[kind].time))))):swElement('div',{className:'sw-route-grid14'},Ec.map(r=>swElement('article',{key:r.id},swElement('h3',null,r.name),swElement('p',null,Qc(r.duration)+' · Strength '+r.power+' · Shipyard '+r.unlock),swElement(Ku,{cost:r.reward})))));
}
function SWBattleControls({input,frame,selected,onSelect,onRetreat,onExitReplay,disabled,replay,speed,onSpeed,onRally,onAbility,onShipCommand,selectedShip14,onSelectShip14,navalTool14,onCancelShipCommand}){
 const reserves=hl(input),kinds=Object.keys(J).filter(k=>input.army[k]>0),sea=input.campaignType==='sea',canRally=input.rallyAt===undefined&&frame?.units.some(u=>u.side==='attack'&&!u.naval&&u.hp>0),hero=frame?.units.find(u=>u.kind==='hero'&&u.hp>0),[fleetOpen,setFleetOpen]=C.useState(false);
 const card=(kind,name,art)=>swElement('button',{key:kind,'data-troop':kind,'aria-label':'Deploy '+name+', '+reserves[kind]+' remaining','aria-pressed':selected===kind,className:'sw-deploy-card14'+(selected===kind?' selected':'')+(!reserves[kind]?' empty':''),disabled:disabled||!reserves[kind],onPointerDown:event=>{if(!disabled&&reserves[kind])SWStartTrayDrag14(event,kind,onSelect)},onClick:()=>onSelect(kind)},art,swElement('span',null,name),swElement('strong',null,'×'+reserves[kind]));
 const ships=frame?.units.filter(u=>u.naval&&u.side==='attack'&&!u.sagaEscort)||[],ship=ships.find(s=>s.shipId===selectedShip14)||ships[0];
 return swElement('div',{className:'sw-battle14'},sea&&swElement('div',{className:'sw-fleet-battle14'},swElement('button',{className:'secondary','aria-expanded':fleetOpen,onClick:()=>setFleetOpen(!fleetOpen)},swElement(xe,{size:17}),'Fleet',swElement(re,{size:14})),ships.map(s=>swElement('button',{key:s.id,'aria-label':SWShipRoles14[s.kind].name+' '+Math.round(s.hp/s.maxHp*100)+'% hull','aria-pressed':s.shipId===ship?.shipId,disabled:s.hp<=0,onClick:()=>{onSelectShip14(s.shipId);setFleetOpen(true)}},swElement('span',null,SWShipRoles14[s.kind].name),swElement('progress',{max:s.maxHp,value:s.hp}))),fleetOpen&&ship&&swElement('div',{className:'sw-fleet-orders14'},swElement('strong',null,SWShipRoles14[ship.kind].name),[['move','Move'],['focus','Focus fire'],['withdraw','Withdraw'],['ability',['cutter','cog'].includes(ship.kind)?'Repair & cover':'Rapid volley']].map(([type,name])=>swElement('button',{key:type,className:'secondary',disabled:replay||disabled||ship.hp<=0||(type==='ability'&&ship.abilityUsed),onClick:()=>{onShipCommand({shipId:ship.shipId,type});setFleetOpen(false)}},name)),swElement('button',{className:'icon-btn','aria-label':'Close fleet orders',onClick:()=>setFleetOpen(false)},swElement(je,{size:18})))),
 !replay&&swElement('div',{className:'sw-deployment-hint14',role:'status'},navalTool14?swElement('span',null,navalTool14.type==='move'?'Tap water for a sailing destination.':'Tap an enemy ship or defense to focus fire.',swElement('button',{className:'sw-cancel-order14',onClick:onCancelShipCommand},'Cancel order')):Object.values(reserves).some(n=>n>0)?(sea?'Drag a troop to the beach. Ships sail over and unload.':'Drag a troop onto the edge. Hold or paint to deploy.'):'All troops deployed'),swElement('div',{className:'sw-deploy-row14'},!replay&&swElement('div',{className:'sw-deploy-strip14','aria-label':'Your selected force'},kinds.map(k=>card(k,J[k].name,swElement(lu,{kind:k,level:input.unitLevels?.[k]||1}))),input.commander&&card('hero','Commander',swElement(nu,{id:input.commander.id}))),swElement('div',{className:'sw-battle-actions14'},swElement('button',{className:'secondary','aria-label':'Battle speed '+speed+' times',disabled:!onSpeed,onClick:onSpeed},speed+'×'),!replay&&canRally&&swElement('button',{className:'primary',disabled,onClick:onRally},'Rally'),!replay&&hero&&input.heroAt===undefined&&swElement('button',{className:'primary',disabled,onClick:onAbility},Oc[input.commander.id].ability),replay?swElement('button',{className:'secondary',onClick:onExitReplay},'Exit replay'):swElement('button',{className:'secondary',disabled,onClick:onRetreat},'Retreat'))));
}
function SWLayoutBar14({tool,onTool,overlay,onOverlay,onUndo,onRedo,onCancel,onCommit,canUndo,canRedo,count,busy,onBuildings}){
 return swElement('aside',{className:'sw-layout-bar14','aria-label':'Layout mode'},swElement('div',{className:'sw-layout-tools14'},[['road','Road'],['clear','Erase'],['tree','Tree'],['rock','Rock'],['garden','Garden']].map(([id,label])=>swElement('button',{key:id,'aria-pressed':tool===id,onClick:()=>onTool(id)},label)),swElement('button',{onClick:onBuildings},'Move buildings'),swElement('select',{'aria-label':'Layout overlay',value:overlay,onChange:e=>onOverlay(e.target.value)},[['plots','Buildable plots'],['roads','Connected roads'],['defense','Defense range'],['harbor','Harbor access']].map(([id,name])=>swElement('option',{key:id,value:id},name)))),swElement('div',{className:'sw-layout-actions14'},swElement('span',null,count+' edits'),swElement('button',{disabled:!canUndo,onClick:onUndo},'Undo'),swElement('button',{disabled:!canRedo,onClick:onRedo},'Redo'),swElement('button',{className:'secondary',onClick:onCancel},'Cancel'),swElement('button',{className:'primary',disabled:busy||!count,onClick:onCommit},'Save layout')));
}
