// @ts-nocheck
// Recovered as an ES module for build 15. Preserve saved-state and replay semantics.
import { A, As, C, Fs, Is, M, N, Ns, O, Oe, Ps, Te, _e, be, j, je, ke, ne, oe, re, se, ve, we, xe, ye } from "../../frontend/vendor/runtime.js";
import { Cc, Ec, Gl, J, Ml, Nl, Oc, Pl, Rc, SWCapacity, SWShipRepairCost, SWTroopAbilities, Sl, Tl, Wc, Z, el, hl, kc, nl, rl, tl, wc, xl } from "../../frontend/core/rules.js";
import { SWBuildCard, SWNavigationContext, swElement } from "../interface.js";
import { Ku, Qc, nu, qu } from "../../frontend/legacy/presentation.js";
import { Bl, SWFamilies14, SWFamily14, SWLoadout14, SWDepotStatus17, SWSelectedArmy14, SWTrainQuote14, SWTroopStats14, SWUpgradeQuote14 } from "./rules.js";
import { SWFleetLimit14, SWPackCargo14, SWPreparationArmy14, SWRecommendSeaPreparation14, SWValidateCargo14, SWReadyFleet14, SWSeaChapters14, SWSeaDefense14, SWShipCapacity14, SWShipRoles14, SWTroopWeight14 } from "./naval.js";
import { SWDrawShipRig14, SWDrawTroopRig14, SWLoadPresentationAssets15, lu } from "./render.js";
import { Eu } from "./Eu.js";
import { SWStartTrayDrag14 } from "./gestures.js";
import { SWPreparationIdentity16, SWMoveCargo16, SWShipReadiness16, SWSwapCargo16, SWCargoSwapOptions16 } from "../build15/preparation.js";
// One compact screen language for preparation, progression and the harbor.
function SWPanelSwitcher(){return null;}
function iu({open,onOpenChange,state,act,busy}){
 const [id,setId]=C.useState(state.commander||'captain');C.useEffect(()=>{if(open)setId(state.commander||'captain')},[open]);
 const person=Oc[id],owned=Wc(state,id),level=owned?Math.min(10,1+Math.floor(owned.xp/160)):1,leading=(state.commander||'captain')===id,locked=Ml(state)<person.unlock;
 return swElement(SWDialog,{open,onClose:()=>onOpenChange(false),title:'Commanders',subtitle:'Choose one leader and their equipment.',className:'sw-commanders14'},swElement('nav',{className:'sw-commanders-list14','aria-label':'Commanders'},Object.keys(Oc).map(key=>swElement('button',{key,'aria-label':'View '+Oc[key].name,'aria-pressed':id===key,onClick:()=>setId(key)},swElement(nu,{id:key}),swElement('span',null,swElement('strong',null,Oc[key].name.split(' ')[0]),swElement('small',null,(state.commander||'captain')===key?'Leading':Ml(state)<Oc[key].unlock?'Keep '+Oc[key].unlock:Oc[key].title))))),swElement('div',{className:'sw-commander-columns14'},swElement('section',{className:'sw-commander-profile14'},swElement('div',{className:'sw-commander-reading14'},swElement('div',{className:'sw-commander-intro14'},swElement(nu,{id,action:true}),swElement('div',null,swElement('small',null,'LEVEL '+level+' · '+person.title),swElement('h3',null,person.name),swElement('strong',null,person.ability),swElement('p',null,person.description))),owned&&swElement('div',{className:'sw-commander-xp14'},swElement('span',null,level===10?'Medieval mastery':owned.xp%160+' / 160 XP to level '+(level+1)),swElement('progress',{max:160,value:level===10?160:owned.xp%160,'aria-label':'Commander experience'}))),swElement('button',{className:'primary wide',disabled:busy||!!state.activeBattle||locked||leading||(!owned&&!Z(state,{gold:200,wood:0,stone:0,food:80})),onClick:()=>act({type:'commander',id},person.name+' leads your army')},locked?'Keep '+person.unlock+' required':leading?'Leading your army':owned?'Make commander':'Recruit · 200 gold + 80 food')),swElement('section',{className:'sw-commander-gear14'},swElement('h3',null,'Equipment'),owned?Object.keys(kc).map(key=>{const item=kc[key],equipped=owned.gear===key,have=owned.owned.includes(key);return swElement('button',{key,'aria-pressed':equipped,disabled:busy||!!state.activeBattle||equipped||(!have&&!Z(state,item.cost)),onClick:()=>act({type:'gear',id,gear:key},item.name+' equipped')},swElement(key==='blade'?we:key==='armor'?be:se,{size:24}),swElement('span',null,swElement('strong',null,item.name),swElement('small',null,item.description)),swElement('span',null,equipped?'Equipped':have?'Equip':swElement(Ku,{cost:item.cost,available:state.resources})))}):swElement('p',null,'Recruit this commander to choose their equipment.'))));
}
function SWDialog({open,onClose,onBack,title,subtitle,className='',headerActions,footer,children}){
 const navigate=C.useContext(SWNavigationContext),canBack=!!onBack||navigate?.canGoBack;
 return swElement(As,{open,onOpenChange:value=>{if(!value)onClose()}},open&&swElement(Ns,{className:'game-dialog sw-dialog sw-screen14 sw-panel17 '+className},
  swElement(Ps,null,canBack&&swElement('button',{className:'sw-back14','aria-label':'Back to previous screen',onClick:onBack||(()=>navigate('back'))},'‹ Back'),swElement(Fs,null,title),swElement(Is,{className:subtitle?'':'sr-only'},subtitle||title),headerActions&&swElement('div',{className:'sw-panel-head-actions17'},headerActions)),
  swElement('div',{className:'sw-body'},children),footer));
}
function SWMainMenu({state,navigate,battle,sound,onSound,rewards}){
 const primary=[['army','Army','Prepare your company',we],['fleet','Harbor','Ships, cargo & voyages',xe],['chronicle','Goals','Chapters & challenges',ve],['store','Collection','Make the kingdom yours',oe]];
 return swElement('aside',{className:'kingdom-menu sw-menu14 sw-command17','aria-label':'Kingdom navigation'},
  swElement('header',null,swElement('div',null,swElement('small',null,'YOUR KINGDOM'),swElement('strong',null,state.name)),swElement('span',{className:'sw-keep-seal17'},'KEEP '+Ml(state))),
  swElement('nav',{className:'sw-command-primary17'},primary.map(([id,name,detail,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),disabled:battle},swElement(Icon,{size:25}),swElement('span',null,swElement('strong',null,name),swElement('small',null,detail)),id==='chronicle'&&rewards>0?swElement('b',{className:'sw-command-count17'},rewards):swElement(re,{size:18})))),
  swElement('nav',{className:'sw-command-tools17','aria-label':'Village tools'},[['city','City life',Te],['plan','Layout',_e],['storage','Storage',A],['settings','Settings',ye]].map(([id,name,Icon])=>swElement('button',{key:id,onClick:()=>navigate(id),disabled:battle&&['plan','city'].includes(id)},swElement(Icon,{size:19}),name))),
  swElement('footer',null,swElement('button',{className:'secondary',onClick:()=>navigate('capital')},swElement(ne,{size:18}),'Village'),swElement('button',{className:'sw-command-sound17 secondary','aria-label':sound?'Mute sound':'Enable sound','aria-pressed':sound,onClick:onSound},swElement(sound?Oe:ke,{size:19})),swElement('button',{className:'primary',disabled:battle,onClick:()=>navigate('frontier')},swElement(we,{size:18}),'Choose battle')));
}
function SWQuickNav({navigate,current,state}){
 return swElement('nav',{className:'sw-quick-nav sw-quick14','aria-label':'Village actions'},swElement('button',{'aria-label':'Build',onClick:()=>navigate('build')},swElement(N,{size:19}),'Build'),swElement('button',{className:'sw-battle-primary14','aria-label':'Battle',onClick:()=>navigate('frontier')},swElement(we,{size:19}),'Battle'));
}
function SWBuildMenu14({state,busy,category,onCategory,onBuild,onClose}){
 const groups={town:['cottage','market','well','workshop','tavern','harbor','builder','monument'],resources:['storehouse','farm','lumber','quarry'],army:['barracks','forge','tower','wall','gate',...Cc]},keep=state.buildings.find(b=>b.kind==='keep'),needsStorage=keep&&SWUpgradeQuote14(state,keep).requirements.some(r=>!r.met&&r.action?.kind==='storehouse');
 const kinds=Object.keys(Sl).filter(kind=>kind!=='keep'&&(category==='all'||groups[category]?.includes(kind))).sort((a,b)=>(needsStorage&&a==='storehouse'?-1:0)-(needsStorage&&b==='storehouse'?-1:0));
 return swElement(SWDialog,{open:true,onClose,title:'Build your village',subtitle:Rc(state)+' construction crews available',className:'sw-build-menu14'},swElement('nav',{className:'sw-tabs','aria-label':'Building categories'},[['all','All'],['town','Town'],['resources','Resources'],['army','Military']].map(([id,label])=>swElement('button',{key:id,'aria-pressed':category===id,onClick:()=>onCategory(id)},label))),needsStorage&&category==='all'&&swElement('p',{className:'sw-build-tip14'},'A second Storehouse makes room for your next Keep upgrade.'),swElement('div',{className:'sw-build-grid14'},kinds.map(kind=>swElement(SWBuildCard,{key:kind,kind,state,busy,onBuild}))));
}
function SWJournalReports14({reports,onReplay}){
 return swElement('section',{className:'sw-journal-reports14'},reports.length?reports.map(report=>swElement('button',{key:report.id,className:'sw-report14',onClick:()=>onReplay(report)},swElement(report.defending?be:report.kind==='sea'?xe:we,{size:25}),swElement('span',null,swElement('strong',null,report.input?.defense?.name||'Kingdom defense'),swElement('small',null,(report.defending?'Defense':report.kind==='sea'?'Sea campaign':report.input?.saga?'Chapter expedition':'Land battle')+' · '+Math.round(report.result?.destruction||0)+'% damage')),swElement('b',null,report.defending?(report.result?.won?'Breach':'Held'):(report.result?.won?'Victory':'Review')),swElement(re,{size:18}))):swElement('p',{className:'sw-empty'},'Your next battle will appear here with its replay.'));
}
function SWRequirements14({quote,onRequirement}){
 return swElement('ul',{className:'sw-requirements14 sw-requirements17'},quote.requirements.filter(r=>!r.met).map(r=>swElement('li',{key:r.id,className:'needed'},swElement(be,{size:16}),swElement('span',null,r.text),r.action&&swElement('button',{className:'secondary',onClick:()=>onRequirement(r.action)},r.action.type==='build'?'Build storage':r.action.type==='storage'?'Get supplies':r.action.type==='land'?'Campaign':r.action.type==='sea'?'Sea campaign':r.action.type==='projects'?'Projects':'View '+(Sl[r.action.kind]?.name||'requirement')))));
}
function SWBuildingDetails14({state,building,busy,layout=false,act,onClose,onMove,onRequirement,onBack}){
 const q=SWUpgradeQuote14(state,building),level=building.level||building.targetLevel||1,[showRequirements,setRequirements]=C.useState(false),[working,setWorking]=C.useState(false),gate=C.useRef(false),missing=q.requirements.filter(r=>!r.met),mastered=level>=q.max;
 C.useEffect(()=>setRequirements(false),[building.id]);
 const run=async(action,message)=>{if(gate.current||busy)return;gate.current=true;setWorking(true);try{return await act(action,message)}finally{gate.current=false;setWorking(false)}};
 const blocked=busy||working,remedy=missing.find(requirement=>requirement.action)?.action;
 const remedyLabel=remedy?.type==='build'?'Build storage':remedy?.type==='storage'?'Get supplies':remedy?.type==='land'?'Land campaign':remedy?.type==='sea'?'Sea campaign':remedy?.type==='projects'?'View projects':remedy?'View '+(Sl[remedy.kind]?.name||'requirement'):'View improvements';
 const primary=()=>{if(building.readyAt){onRequirement({type:'projects'});return}if(!q.allowed){if(showRequirements&&remedy)onRequirement(remedy);else setRequirements(!showRequirements);return}void run({type:'upgrade',id:building.id},Sl[building.kind].name+' upgrade started')};
 return swElement('aside',{className:'sw-building14 sw-building15 sw-building17'+(layout?' sw-layout-details14':''),'aria-label':Sl[building.kind].name+(layout?' layout':' details')},
  swElement('header',null,onBack&&swElement('button',{className:'icon-btn','aria-label':'Back to previous building',onClick:onBack},'‹'),swElement('div',null,swElement('h2',null,Sl[building.kind].name),swElement('span',null,'Level '+level+(layout?' · Facing '+(building.facing||0)*90+'°':building.readyAt?' · Under construction':''))),swElement('button',{'aria-label':'Close building details',className:'icon-btn',onClick:onClose},swElement(je,{size:20}))),
  !layout&&swElement('div',{className:'sw-building-scroll14 sw-building-content17'},
   swElement('div',{className:'sw-evolution14 sw-building-art17'},swElement('div',null,swElement(qu,{kind:building.kind,level,large:true}),swElement('strong',null,'Level '+level)),!mastered&&swElement(C.Fragment,null,swElement(re,{size:20}),swElement('div',null,swElement(qu,{kind:building.kind,level:level+1,large:true}),swElement('strong',null,'Level '+(level+1))))),
   swElement('section',{className:'sw-building-benefits17'},showRequirements&&!q.allowed?swElement(C.Fragment,null,swElement('h3',null,'Before you upgrade'),swElement(SWRequirements14,{quote:q,onRequirement}),q.trades?.length>0&&swElement('div',{className:'sw-requirement-trades17'},swElement('p',null,'Exchange surplus food'),q.trades.map(trade=>swElement('button',{key:trade.resource,className:'secondary',disabled:blocked,onClick:()=>run(trade.action,'Supplies exchanged')},trade.label))),swElement('button',{className:'text-button',onClick:()=>setRequirements(false)},'View improvements')):swElement(C.Fragment,null,
    swElement('h3',null,building.readyAt?'Your builders are at work':mastered?'Medieval mastery':'The next improvement'),
    q.deltas?.length?swElement('div',{className:'sw-upgrade-deltas17'},q.deltas.slice(0,3).map(row=>swElement('div',{key:row.label},swElement('span',null,row.label),swElement('strong',null,row.before+(row.unit||''),!mastered&&swElement('b',null,' → '+row.after+(row.unit||'')))))):swElement('p',null,mastered?Bl(building):q.benefit),
    building.readyAt?swElement('p',{className:'sw-project-status14'},'Ready in '+Qc(Math.max(0,(building.readyAt-Date.now())/1000))):!mastered&&swElement(C.Fragment,null,swElement(Ku,{cost:q.cost,available:state.resources}),missing.length>0&&swElement('button',{className:'sw-blocker-link17',onClick:()=>setRequirements(true)},swElement(be,{size:16}),swElement('span',null,q.reason,swElement('small',null,'View '+missing.length+' '+(missing.length===1?'requirement':'requirements'))),swElement(re,{size:17})))))),
  swElement('footer',null,swElement('button',{className:'secondary',disabled:blocked,onClick:onMove},'Move'),swElement('button',{className:'secondary',disabled:blocked,onClick:()=>run({type:'rotate',id:building.id},'Building rotated')},'Rotate'),!layout&&swElement('button',{className:'primary',disabled:blocked||mastered,onClick:primary},working?'Working…':building.readyAt?'View project':mastered?'Mastered':q.allowed?'Upgrade · '+Qc(q.duration):showRequirements?remedyLabel:'Resolve requirements')));
}
function SWCampaignView17(state,sea,requested){
 const items=sea?SWSeaChapters14:Tl,progress=Math.max(0,Math.min(items.length,sea?state.seaCampaign||0:state.campaign||0)),index=Math.max(0,Math.min(items.length-1,Number.isInteger(requested)?requested:progress)),item=items[index],complete=index<progress,reason=index>progress?'Complete '+items[index-1].name+' first':sea&&Ml(state)<item.keep?'Keep '+item.keep+' required':null,defense=sea?SWSeaDefense14(index):Gl(index);
 const reward=complete?(sea?{gold:35,wood:30,stone:15,food:20}:{gold:35,wood:20,stone:15,food:25}):item.reward,gems=complete?0:sea?item.gems:25;
 const objective=sea?(item.mode==='convoy'?'Escort the relief cutter safely through the channel.':item.mode==='blockade'?'Destroy the enemy fleet and capture the keep with landed troops.':'Land troops and capture the coastal keep.'):'Break through the defenses and capture the keep.';
 return {items,progress,index,item,complete,reason,defense,reward,gems,objective,storageLimited:xl.some(kind=>state.resources[kind]+reward[kind]>SWCapacity(state)),defenses:defense.buildings.filter(b=>b.kind==='tower'||Cc.includes(b.kind)).length};
}
function SWCampaignBoard14({state,sea=false,onScout,onHarbor}){
 const navigate=C.useContext(SWNavigationContext),[selected,setSelected]=C.useState({land:null,sea:null}),path=sea?'sea':'land',view=SWCampaignView17(state,sea,selected[path]),{items,progress,index,item,complete,reason,defense,reward,gems,objective,storageLimited}=view;
 const launch=()=>{if(reason)return;onScout({kind:sea?'sea':'campaign',campaignIndex:index,defense,objective})};
 return swElement('section',{className:'sw-campaign14 sw-campaign17','aria-label':sea?'Sea campaign':'Land campaign'},
  swElement('article',{className:'sw-campaign-hero17'},
   swElement('div',{className:'sw-campaign-scene17'},swElement('div',{className:'sw-campaign-map17','aria-hidden':true},swElement(Eu,{key:path+'-'+index,buildings:defense.buildings,enemy:true,staticPreview:true,navalSupport:sea?{id:'preview',kind:'cog',level:1}:null,battleInput14:sea?{campaignType:'sea',defense}:null})),
    swElement('div',{className:'sw-campaign-kicker17'},swElement(sea?xe:we,{size:17}),sea?'THE TIDEBORN COAST':'THE KING’S ROAD',swElement('span',null,progress+' / '+items.length)),
    swElement('header',{className:'sw-campaign-title17'},swElement('span',null,(complete?'CAPTURED':reason?'LOCKED':'NEXT CHAPTER')+' · '+(index+1)),swElement('h2',null,item.name),swElement('p',null,sea?item.title:item.subtitle))),
   swElement('div',{className:'sw-campaign-brief17'},swElement('div',{className:'sw-campaign-reading17'},
    swElement('div',{className:'sw-campaign-objective17'},swElement('small',null,sea&&item.mode==='convoy'?'ESCORT OBJECTIVE':'VICTORY OBJECTIVE'),swElement('p',null,objective)),
    swElement('div',{className:'sw-campaign-loot17'},swElement('div',null,swElement('small',null,complete?'Replay loot':'First-clear loot'),gems>0&&swElement('strong',null,'◆ '+gems)),swElement(Ku,{cost:reward}),storageLimited&&swElement('small',null,'Resources limited by your free Storage space.')),
    swElement('p',{className:'sw-campaign-hint17'},defense.tacticalHint17?.match(/^[^.!?]+[.!?]?/)?.[0]||view.defenses+' defensive emplacements'+(sea?' · Landing troops stay aboard until deployed.':' · Deploy along the stronghold perimeter.'))),
    swElement('footer',{className:'sw-campaign-action17'},sea&&swElement('button',{className:'secondary',onClick:onHarbor},'Harbor'),storageLimited&&!sea&&swElement('button',{className:'secondary',onClick:()=>navigate?.('storage')},'Storage'),swElement('button',{className:'primary',disabled:!!reason,onClick:launch},reason|| (complete?'Replay chapter':'Prepare attack'))))),
  swElement('nav',{className:'sw-campaign-rail17','aria-label':'Campaign chapters'},items.map((chapter,i)=>{const captured=i<progress,locked=i>progress||(sea&&Ml(state)<chapter.keep);return swElement('button',{key:chapter.id,className:(captured?'complete ':'')+(locked?'locked':''),'aria-label':'Chapter '+(i+1)+': '+chapter.name+(locked?', locked':captured?', captured':''),'aria-current':i===index?'step':undefined,'aria-pressed':i===index,onClick:()=>setSelected(previous=>({...previous,[path]:i}))},swElement('strong',null,i+1),swElement(locked?be:captured?O:sea?xe:we,{size:14}))})));
}
function SWAbilitySummary({kind,level}){
 const all=SWTroopAbilities(kind),active=all.filter(a=>a.level<=level),current=active.at(-1),next=all.find(a=>a.level>level);
 return swElement('section',{className:'sw-skills14 sw-skills17'},current&&swElement('div',{className:'sw-skill-current17'},swElement(O,{size:17}),swElement('div',null,swElement('strong',null,current.name),swElement('p',null,current.description))),next&&swElement('div',{className:'sw-skill-next17'},swElement(oe,{size:17}),swElement('div',null,swElement('small',null,'UNLOCKS AT LEVEL '+next.level),swElement('strong',null,next.name),swElement('p',null,next.description))),active.length>1&&swElement('details',null,swElement('summary',null,'Earlier abilities · '+(active.length-1)),active.slice(0,-1).map(a=>swElement('p',{key:a.name},swElement('strong',null,a.name+'. '),a.description))));
}
function SWArmyUpgradeView17(state,kind){
 const level=el(state,kind),nextLevel=Math.min(10,level+1),before=SWTroopStats14(state,kind,level),after=SWTroopStats14(state,kind,nextLevel),all=SWTroopAbilities(kind);
 const unlocks=all.filter(a=>a.level===nextLevel&&a.level>level),appearanceChanged=kind==='infantry'&&level<10&&[4,7,10].includes(nextLevel);
 const upgradeSummary=level===10?'Medieval mastery':unlocks.length?'New ability · stronger stats':appearanceChanged?'New guard appearance · stronger stats':'Stronger combat stats';
 const rows=[['Health',before.hp,after.hp,''],[kind==='healer'?'Healing':'Attack',kind==='healer'?before.heal:before.damage,kind==='healer'?after.heal:after.damage,''],['Attack interval',before.cooldown,after.cooldown,'s'],['Range',before.range,after.range,' tiles']];
 return {level,nextLevel,before,after,deltas:rows.filter(([,a,b])=>Math.abs(a-b)>.001).map(([label,a,b,unit])=>({label,before:Math.round(a*10)/10,after:Math.round(b*10)/10,unit})),unlocks,appearanceChanged,upgradeSummary,upcoming:all.find(a=>a.level>level)};
}
function SWQuantity17({label,value,min=0,max=80,disabled=false,onChange}){
 return swElement('div',{className:'sw-quantity17','aria-label':label},swElement('button',{className:'secondary','aria-label':'Fewer '+label,disabled:disabled||value<=min,onClick:()=>onChange(Math.max(min,value-1))},'−'),swElement('output',{'aria-label':label+' count'},value),swElement('button',{className:'secondary','aria-label':'More '+label,disabled:disabled||value>=max,onClick:()=>onChange(Math.min(max,value+1))},'+'));
}
function SWArmy({open,onClose,state,act,busy,onFrontier,onCommander,onPractice}){
 const navigate=C.useContext(SWNavigationContext),[familyId,setFamily]=C.useState('vanguard'),[selected,setSelected]=C.useState('infantry'),[mode,setMode]=C.useState('Force'),[count,setCount]=C.useState(5),[draft,setDraft]=C.useState(null),[specialists,setSpecialists]=C.useState(false),[leaving,setLeaving]=C.useState(null),[working,setWorking]=C.useState(false),gate=C.useRef(false);
 const family=SWFamilies14.find(f=>f.id===familyId)||SWFamilies14[0],force=draft||SWLoadout14(state),kind=family.kinds.includes(selected)?selected:force.slots.find(k=>family.kinds.includes(k))||family.default,model=SWArmyUpgradeView17(state,kind),level=model.level;
 const train=SWTrainQuote14(state,force),research=state.trainingResearch,cost=tl(state,kind),capacity=Pl(state),owned=Nl(state.army),keep=Ml(state),troop=J[kind],singleTrain=SWTrainQuote14(state,{slots:[kind],counts:{[kind]:(state.army[kind]||0)+count}}),total=force.slots.reduce((n,k)=>n+(force.counts[k]||0),0),locked=(troop.unlock||1)>keep,blocked=busy||working;
 C.useEffect(()=>{if(open){setDraft(null);setLeaving(null);setSpecialists(false);const loadout=SWLoadout14(state);setSelected(loadout.slots.find(k=>SWFamily14(k)?.id===familyId)||family.default)}},[open]);
 const run=async(action,message)=>{if(gate.current||busy)return null;gate.current=true;setWorking(true);try{return await act(action,message)}finally{gate.current=false;setWorking(false)}};
 const save=async()=>{const result=await run({type:'saveLoadout',loadout:force},'Company saved');if(result)setDraft(null);return result};
 const requestLeave=callback=>{if(draft)setLeaving(()=>callback);else callback?.()};
 const choose=type=>{if((J[type].unlock||1)>keep)return;setSelected(type);setSpecialists(false);if(mode==='Force'){const existing=force.slots.find(k=>family.kinds.includes(k)),other=force.slots.filter(k=>k!==existing).reduce((sum,k)=>sum+(force.counts[k]||0),0);setDraft({...force,slots:existing?force.slots.map(k=>k===existing?type:k):[...force.slots,type],counts:{...force.counts,[type]:Math.max(0,Math.min(80,capacity-other,force.counts[type]??6))}})}};
 const countChange=value=>{const existing=force.slots.find(k=>family.kinds.includes(k)),other=force.slots.filter(k=>k!==existing).reduce((sum,k)=>sum+(force.counts[k]||0),0);setDraft({...force,counts:{...force.counts,[kind]:Math.max(0,Math.min(80,capacity-other,value))},slots:existing?force.slots.map(k=>k===existing?kind:k):[...force.slots,kind]})};
 const researchReason=locked?'Keep '+troop.unlock+' needed':research?'Research in progress':level>=10?'Medieval mastery':level>=keep?'Upgrade your Keep to '+(level+1):!Z(state,cost)?'More research supplies needed':null;
 const remaining=research?Math.max(0,(research.readyAt-Date.now())/1000):0;
 const primaryLabel=working?'Working…':mode==='Force'?draft?'Save company':train.count?'Train missing · '+train.count:'Company ready':mode==='Train'?'Train '+count:research?'Research · '+Qc(remaining):level>=10?'Mastered':'Upgrade to level '+(level+1);
 const disabled=blocked||(mode==='Force'?(!draft&&!train.allowed||total>capacity):mode==='Train'?!singleTrain.allowed:!!researchReason);
 const primary=()=>mode==='Force'?draft?save():run({type:'trainLoadout'},'Your company is ready'):mode==='Train'?run({type:'recruit',kind,count},'Troops ready'):run({type:'researchUnit',kind},troop.name+' upgrade started');
 const footer=swElement('footer',{className:'sw-army-footer17'},leaving?swElement(C.Fragment,null,swElement('strong',null,'Keep your company changes?'),swElement('button',{className:'secondary',disabled:blocked,onClick:()=>{setDraft(null);const callback=leaving;setLeaving(null);callback()}},'Discard'),swElement('button',{className:'primary',disabled:blocked||total>capacity,onClick:async()=>{if(await save()){const callback=leaving;setLeaving(null);callback()}}},'Save & continue')):swElement(C.Fragment,null,swElement('div',{className:'sw-army-action17'},swElement('button',{className:'primary',disabled,onClick:primary},primaryLabel),swElement('span',{className:'sw-army-action-note17'},mode==='Force'?draft?'Changes are not saved':train.count?train.reason||'Fill the selected company':total+' assigned · '+(owned-Nl(SWSelectedArmy14(state)))+' stay home':mode==='Train'?singleTrain.reason||'Ready immediately':researchReason||model.upgradeSummary)),swElement('button',{className:'secondary',disabled:blocked,onClick:()=>requestLeave(onCommander)},'Commander'),swElement('button',{className:'secondary',disabled:blocked||!draft&&Nl(SWSelectedArmy14(state))<3,onClick:()=>requestLeave(onFrontier)},'Choose battle')));
 return swElement(SWDialog,{open,onClose:()=>requestLeave(onClose),onBack:()=>requestLeave(()=>navigate?.('back')),title:'Army',subtitle:owned+' / '+capacity+' troops · '+total+' assigned',className:'sw-army14 sw-army17',footer,headerActions:swElement('nav',{className:'sw-segment17','aria-label':'Army sections'},['Force','Train','Upgrade'].map(tab=>swElement('button',{key:tab,'aria-pressed':mode===tab,onClick:()=>{setMode(tab);setSpecialists(false)}},tab)))},
  swElement('div',{className:'sw-army-layout17'},swElement('nav',{className:'sw-army-families17','aria-label':'Troop families'},SWFamilies14.map(f=>{const unit=force.slots.find(k=>f.kinds.includes(k))||f.default;return swElement('button',{key:f.id,'aria-pressed':familyId===f.id,onClick:()=>{setFamily(f.id);setSelected(unit);setSpecialists(false)}},swElement(lu,{kind:unit,level:el(state,unit)}),swElement('span',null,swElement('strong',null,f.name),swElement('small',null,(force.counts[unit]||0)+' assigned')))})),
   swElement('section',{className:'sw-army-unit17'},swElement('header',null,swElement('div',null,swElement('h3',null,troop.name),swElement('p',null,family.role)),family.kinds.length>1&&swElement('button',{className:'secondary','aria-expanded':specialists,onClick:()=>setSpecialists(!specialists)},specialists?'Done':'Change type')),
    specialists?swElement('div',{className:'sw-army-specialists17'},family.kinds.map(type=>swElement('button',{key:type,'aria-pressed':kind===type,disabled:(J[type].unlock||1)>keep,onClick:()=>choose(type)},swElement(lu,{kind:type,level:el(state,type)}),swElement('strong',null,J[type].name),swElement('small',null,(J[type].unlock||1)>keep?'Keep '+J[type].unlock:'Level '+el(state,type))))):
    swElement('div',{className:'sw-army-reading17'},mode==='Force'?swElement('div',{className:'sw-company17'},swElement('div',{className:'sw-unit-display17'},swElement(SWUnitPreview14,{kind,level}),swElement('strong',null,'Level '+level),swElement('small',null,kind==='infantry'?'Guard rank '+(Math.floor((level-1)/3)+1):'Combat research')),swElement('div',{className:'sw-company-controls17'},swElement('label',{className:'sw-field'},'Saved company',swElement('select',{'aria-label':'Saved company',value:force.id,disabled:blocked||!!draft,onChange:event=>run({type:'selectLoadout',id:event.target.value},'Company selected')},(state.loadouts14||[force]).map(loadout=>swElement('option',{key:loadout.id,value:loadout.id},loadout.name)))),swElement('div',{className:'sw-company-count17'},swElement('span',null,'In this company'),swElement(SWQuantity17,{label:troop.name+' in company',value:force.counts[kind]||0,max:Math.min(80,capacity-total+(force.counts[kind]||0)),disabled:blocked||locked,onChange:countChange})),swElement('p',null,(state.army[kind]||0)+' ready · '+SWTroopWeight14(kind)+' ship '+(SWTroopWeight14(kind)===1?'space':'spaces')+' each'),train.count>0&&swElement(Ku,{cost:train.cost,available:state.resources}),locked&&swElement('p',{className:'sw-army-blocker17'},'Unlock this family at Keep '+troop.unlock))):
     mode==='Train'?swElement('div',{className:'sw-training17'},swElement('div',{className:'sw-unit-display17'},swElement(SWUnitPreview14,{kind,level}),swElement('strong',null,'Level '+level),swElement('small',null,kind==='infantry'?'Guard rank '+(Math.floor((level-1)/3)+1):'Combat research')),swElement('div',{className:'sw-training-controls17'},swElement('div',{className:'sw-training-quantity17'},swElement('span',null,'Troops to train'),swElement(SWQuantity17,{label:troop.name+' to train',value:count,min:1,max:Math.max(1,Math.min(80,capacity-owned)),disabled:blocked,onChange:setCount})),swElement('div',{className:'sw-training-presets17'},[1,5,10].map(n=>swElement('button',{key:n,className:'secondary','aria-pressed':count===n,disabled:n>capacity-owned,onClick:()=>setCount(n)},'×'+n))),swElement(Ku,{cost:singleTrain.cost,available:state.resources}),swElement(SWAbilitySummary,{kind,level}))):
     swElement('div',{className:'sw-upgrade17'},swElement('div',{className:'sw-rank-comparison17'},[level,...(level<10?[level+1]:[])].map(lv=>swElement('div',{key:lv},swElement(SWUnitPreview14,{kind,level:lv}),swElement('strong',null,(lv===level?'Now':'Next')+' · '+lv),swElement('small',null,kind==='infantry'?'Guard rank '+(Math.floor((lv-1)/3)+1):'Combat research')))),swElement('div',{className:'sw-rank-benefits17'},swElement('div',{className:'sw-upgrade-deltas17'},model.deltas.slice(0,3).map(row=>swElement('div',{key:row.label},swElement('span',null,row.label),swElement('strong',null,row.before+row.unit,swElement('b',null,' → '+row.after+row.unit))))),model.unlocks.length>0&&swElement('div',{className:'sw-unlock17'},swElement(oe,{size:20}),swElement('span',null,swElement('small',null,'NEW ABILITY'),swElement('strong',null,model.unlocks[0].name),swElement('p',null,model.unlocks[0].description))),!model.unlocks.length&&swElement(SWAbilitySummary,{kind,level}),level<10&&swElement(Ku,{cost,available:state.resources}),onPractice&&swElement('button',{className:'secondary',disabled:blocked,onClick:()=>requestLeave(()=>onPractice(kind))},'Practice '+troop.name)))))));
}
function SWUnitPreview14({kind,level=1,animate=false}){
 const ref=C.useRef(null);C.useEffect(()=>{let frame,live=true,start=performance.now();const draw=now=>{const canvas=ref.current;if(!live||!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,240,150);SWDrawTroopRig14(ctx,{kind,level,x:120,y:134,scale:kind==='infantry'?2.1:2.7,heading:-.8,phase:((now-start)/1400)%1,state:animate?'attack':'idle',enemy:false});if(animate)frame=requestAnimationFrame(draw)};void SWLoadPresentationAssets15().then(()=>{if(live)frame=requestAnimationFrame(draw)});return()=>{live=false;cancelAnimationFrame(frame)}},[kind,level,animate]);return swElement('canvas',{ref,width:240,height:150,className:'sw-unit-preview14',role:'img','aria-label':J[kind]?.name+' level '+level});
}
function SWScout(props){
 if(!props.open||!props.scout)return null;
 return swElement(SWPreparation16,{...props,key:SWPreparationIdentity16(props.scout)});
}
function SWPreparation16({onClose,scout,state,busy,onAttack,onTrain,onHarbor}){
 const sea=scout.kind==='sea',practice=!!scout.practiceKind,supplied=!!scout.fixedArmy||practice;
 const [draft,setDraft]=C.useState(()=>{
  const army=SWSelectedArmy14(state),recommended=sea?SWRecommendSeaPreparation14(state,army):null;
  return {army,ids:recommended?.ids||[],cargo:null};
 });
 const [view,setView]=C.useState('ready'),[replacement,setReplacement]=C.useState(null),[manifestId,setManifestId]=C.useState(null),[swapKind,setSwapKind]=C.useState(null),[cargoNote,setCargoNote]=C.useState('');
 const packed=sea?SWPackCargo14(state,draft.ids,draft.army):null;
 const selectedArmy=supplied?(practice?Object.fromEntries(Object.keys(J).map(k=>[k,k===scout.practiceKind?Math.min(12,Pl(state)):0])):scout.army):sea?packed.army:SWPreparationArmy14(state,draft.army);
 let manifest=packed?.fleet||[],cargoReset=false;
 if(sea&&draft.cargo){try{manifest=SWValidateCargo14(state,draft.cargo,selectedArmy)}catch{cargoReset=true}}
 const ids=manifest.map(ship=>ship.id),ready=SWReadyFleet14(state),readyIds=new Set(ready.map(ship=>ship.id)),total=Nl(selectedArmy||{}),limit=SWFleetLimit14(state);
 const chapter=sea?SWSeaChapters14[scout.campaignIndex]:null,hold=scout.previewInput?.saga?.mode==='hold';
 const occupied=manifest.reduce((sum,ship)=>sum+Object.entries(ship.cargo).reduce((n,[kind,count])=>n+count*SWTroopWeight14(kind),0),0);
 const capacity=manifest.reduce((sum,ship)=>sum+SWShipCapacity14(ship),0),blocked=!supplied&&(total<3||(sea&&!manifest.length));
 const kinds=Object.keys(J).filter(kind=>selectedArmy?.[kind]>0),slots=supplied?kinds:SWLoadout14(state).slots.filter(kind=>Object.hasOwn(J,kind));
 const shortFamily={vanguard:'Guard',rangers:'Ranged',riders:'Riders',breachers:'Breach',siege:'Siege',medics:'Medics'};
 const shortShip={cutter:'Cutter',cog:'Transport',galley:'Galley',bombard:'Siege barge'};
 const levels=supplied?scout.previewInput?.unitLevels||state.unitLevels:state.unitLevels;
 const homeCount=Object.keys(J).reduce((sum,kind)=>sum+Math.max(0,(SWSelectedArmy14(state)[kind]||0)-(selectedArmy?.[kind]||0)),0);
 const reward=sea?(state.seaCampaign>scout.campaignIndex?{gold:35,wood:30,stone:15,food:20}:chapter.reward):scout.kind==='campaign'?(state.campaign>scout.campaignIndex?{gold:35,wood:20,stone:15,food:25}:Tl[scout.campaignIndex].reward):null;
 const subtitle=sea?'Sea campaign · '+chapter.title:practice?'Training grounds':supplied?'Supplied expedition':scout.kind==='player'?'Rival kingdom':'Land battle · No ships needed';
 const updateArmy=(kind,delta)=>{
  const candidate={...selectedArmy,[kind]:(selectedArmy[kind]||0)+delta};
  if(candidate[kind]<0||candidate[kind]>(state.army[kind]||0)||Nl(candidate)>Pl(state))return;
  if(sea&&SWPackCargo14(state,ids,candidate).excludedCount)return;
  setDraft({army:candidate,ids,cargo:null});
 };
 const canAdd=kind=>{
  if((selectedArmy[kind]||0)>=(state.army[kind]||0)||total>=Pl(state)||(J[kind].unlock||1)>Ml(state))return false;
  if(sea&&occupied+SWTroopWeight14(kind)>capacity)return false;
  return !sea||SWPackCargo14(state,ids,{...selectedArmy,[kind]:(selectedArmy[kind]||0)+1}).excludedCount===0;
 };
 const chooseShip=id=>{
  if(!readyIds.has(id))return;
  if(ids.includes(id)){setDraft({...draft,ids:ids.filter(value=>value!==id),cargo:null});setReplacement(null)}
  else if(ids.length<limit){setDraft({...draft,ids:[...ids,id],cargo:null});setReplacement(null)}
  else setReplacement(id);
 };
 const useRecommended=()=>{const army=SWSelectedArmy14(state),suggestion=SWRecommendSeaPreparation14(state,army);setDraft({army,ids:suggestion.ids,cargo:null});setReplacement(null)};
 const focusedShip=manifest.find(ship=>ship.id===manifestId)||manifest[0];
 const transfer=(kind,incoming)=>{
  if(!focusedShip)return null;
  for(const other of manifest.filter(ship=>ship.id!==focusedShip.id)){
   const next=SWMoveCargo16(manifest,kind,incoming?other.id:focusedShip.id,incoming?focusedShip.id:other.id);
   if(next)return next;
  }
  return null;
 };
 const moveTroop=(kind,incoming)=>{const cargo=transfer(kind,incoming);if(cargo)setDraft({army:selectedArmy,ids,cargo})};
 const stepper=(kind,count,onLess,onMore,lessDisabled,moreDisabled,label,swap=false)=>swElement('div',{className:'sw-prep-stepper16'},
  swElement('button',{type:'button',className:'secondary','aria-label':label+' fewer '+J[kind].name,disabled:busy||lessDisabled,onClick:onLess},'−'),
  swElement('output',{'aria-label':J[kind].name+' count'},count),
  swElement('button',{type:'button',className:'secondary','aria-label':swap?'Choose swap for '+J[kind].name:label+' more '+J[kind].name,disabled:busy||moreDisabled,onClick:onMore},swap?'⇄':'+'));
 const prep={army:selectedArmy,fleet:sea?manifest:[]};
 const readiness=sea?(manifest.length?occupied+' / '+capacity+' cargo space':'No ships selected'):supplied?'Supplied force':total+' troops ready';
 const status=sea?(total<3?'At least 3 troops must fit aboard':manifest.length?'Loaded and ready':'Choose a ship to carry your force'):!supplied&&total<3?'Choose at least 3 troops':hold?'Hold the harbor':practice?'Practice without losing troops':'Choose your deployment on the battlefield';
 const launchLabel=busy?'Preparing…':hold?'Defend harbor':practice?'Begin practice':supplied?'Begin expedition':sea?'Sail · '+total+' troops':'Attack · '+total+' troops';
 return swElement(SWDialog,{open:true,onClose,title:scout.defense.name,subtitle,className:'sw-scout14 sw-prep16'},
  swElement('div',{className:'sw-prep-layout16'},
   swElement('section',{className:'sw-prep-scene16'},
    swElement('div',{className:'sw-prep-map16','aria-hidden':true},swElement(Eu,{buildings:scout.defense.buildings,enemy:true,navalSupport:sea?{id:'preview',kind:'cog',level:1}:null,battleInput14:sea?{campaignType:'sea',defense:scout.defense}:null})),
    swElement('div',{className:'sw-prep-brief16'},swElement('h3',null,scout.objective||'Capture the keep.'),swElement('p',null,hold?'Your walls and garrison fight automatically. Hold the harbor.':scout.defense.tacticalHint17?.match(/^[^.!?]+[.!?]?/)?.[0]||(sea?'Land along the beach. Ships provide covering fire.':'Hold and drag along the perimeter to deploy.')),
     !supplied&&homeCount>0&&swElement('p',{className:'sw-prep-note16'},homeCount+' from your saved force stay home.'),
     cargoReset&&swElement('p',{className:'sw-prep-note16'},'Fleet availability changed. Loading updated.')),
    reward&&swElement('div',{className:'sw-prep-rewards16'},swElement('small',null,'Victory supplies'),swElement(Ku,{cost:reward}))),
   swElement('section',{className:'sw-prep-controls16'},
    swElement('div',{className:'sw-prep-content16'},
     view==='ready'&&swElement(C.Fragment,null,
      sea&&swElement('section',{className:'sw-prep-section16'},swElement('header',{className:'sw-prep-section-head16'},swElement('h3',null,manifest.length+' ships'),swElement('button',{className:'secondary',onClick:()=>setView('ships')},'Change ships')),
       swElement('div',{className:'sw-prep-fleet-strip16'},manifest.length?manifest.map(ship=>swElement('button',{key:ship.id,onClick:()=>setView('ships'),'aria-label':SWShipRoles14[ship.kind].name+', level '+ship.level+', '+SWShipCapacity14(ship)+' cargo space. Change ships.'},swElement(SWShipPreview14,{ship}),swElement('strong',null,shortShip[ship.kind]),swElement('small',null,'Lv '+ship.level+' · '+SWShipCapacity14(ship)+' space'))):swElement('div',{className:'sw-prep-blocker16'},swElement('p',null,ready.length?'Select a vessel for this landing.':'Your ships are away, carrying cargo, or need repairs.'),swElement('button',{className:'secondary',onClick:ready.length?()=>setView('ships'):onHarbor},ready.length?'Choose ships':'Open Harbor')))),
      swElement('section',{className:'sw-prep-section16'},swElement('header',{className:'sw-prep-section-head16'},swElement('h3',null,total+' troops'),!supplied&&swElement('button',{className:'secondary',onClick:()=>setView('army')},'Change army')),
       swElement('div',{className:'sw-prep-troop-strip16',style:{'--sw-prep-types':Math.max(1,Math.min(6,kinds.length))}},kinds.length?kinds.map(kind=>swElement('div',{key:kind,role:'img','aria-label':selectedArmy[kind]+' '+J[kind].name+', level '+(levels?.[kind]||1),title:J[kind].name},swElement(lu,{kind,level:levels?.[kind]||1}),swElement('strong',null,'×'+selectedArmy[kind]),swElement('small',null,supplied?J[kind].name:shortFamily[SWFamily14(kind).id]))):swElement('div',{className:'sw-prep-blocker16'},swElement('p',null,sea&&ready.length&&!manifest.length?'Choose ships to load your force.':'No troops selected for this mission.'),swElement('button',{className:'secondary',onClick:()=>setView('army')},'Choose troops'))))),
     view==='army'&&swElement(C.Fragment,null,
      swElement('header',{className:'sw-prep-editor-head16'},swElement('h3',null,'Choose your troops'),swElement('button',{className:'secondary',onClick:()=>setDraft({...draft,army:SWSelectedArmy14(state),cargo:null})},'Use saved force')),
      swElement('div',{className:'sw-prep-troop-grid16'},slots.map(kind=>swElement('div',{className:'sw-prep-troop-row16',key:kind},swElement(lu,{kind,level:el(state,kind)}),swElement('div',null,swElement('strong',null,J[kind].name),swElement('small',null,Math.max(0,(state.army[kind]||0)-(selectedArmy[kind]||0))+' at home'+(sea?' · '+SWTroopWeight14(kind)+' space each':''))),stepper(kind,selectedArmy[kind]||0,()=>updateArmy(kind,-1),()=>updateArmy(kind,1),!selectedArmy[kind],!canAdd(kind),'Deploy')))),
      swElement('p',{className:'sw-prep-note16'},sea?'Only troops that fit can be added. Change ships for more room.':'Unselected troops stay safely at home.'),
      swElement('button',{className:'secondary',onClick:onTrain},'Train or change troop types')),
     sea&&view==='ships'&&swElement(C.Fragment,null,
      swElement('header',{className:'sw-prep-editor-head16'},swElement('h3',null,'Choose up to '+limit+' ships'),swElement('button',{className:'secondary',onClick:useRecommended},'Recommend')),
      replacement&&swElement('div',{className:'sw-prep-replace16'},swElement('p',null,'Replace which ship?'),ids.map(id=>{const ship=manifest.find(s=>s.id===id);return swElement('button',{key:id,className:'secondary',onClick:()=>{setDraft({...draft,ids:ids.map(value=>value===id?replacement:value),cargo:null});setReplacement(null)}},shortShip[ship.kind]+' · Lv '+ship.level)}),swElement('button',{className:'secondary',onClick:()=>setReplacement(null)},'Cancel replacement')),
      swElement('div',{className:'sw-prep-ship-grid16'},(state.fleet||[]).filter(ship=>SWShipRoles14[ship.kind]).map((ship,index)=>swElement('button',{key:ship.id,'aria-label':SWShipRoles14[ship.kind].name+' '+(index+1)+', level '+ship.level+', '+SWShipReadiness16(ship),'aria-pressed':ids.includes(ship.id),disabled:!readyIds.has(ship.id),onClick:()=>chooseShip(ship.id)},swElement(SWShipPreview14,{ship}),swElement('div',null,swElement('strong',null,SWShipRoles14[ship.kind].name),swElement('small',null,'Lv '+ship.level+' · '+SWShipCapacity14(ship)+' space'),swElement('small',null,ids.includes(ship.id)?'Selected':SWShipReadiness16(ship)))))),
      swElement('button',{className:'secondary',onClick:onHarbor},'Manage ships in Harbor'),
      manifest.length>1&&swElement('button',{className:'text-button sw-prep-advanced16',onClick:()=>setView('cargo')},'Arrange ship cargo')),
     sea&&view==='cargo'&&swElement(C.Fragment,null,
      swElement('header',{className:'sw-prep-editor-head16'},swElement('h3',null,'Arrange your landing groups'),swElement('button',{className:'secondary',onClick:()=>setDraft({...draft,army:selectedArmy,cargo:null})},'Auto load')),
      swElement('nav',{className:'sw-prep-manifest-tabs16','aria-label':'Ship manifests'},manifest.map((ship,index)=>swElement('button',{key:ship.id,className:'secondary','aria-pressed':focusedShip?.id===ship.id,onClick:()=>{setManifestId(ship.id);setSwapKind(null);setCargoNote('')}},shortShip[ship.kind]+' '+(index+1)))),
      focusedShip&&swElement('p',{className:'sw-prep-note16'},Object.entries(focusedShip.cargo).reduce((sum,[kind,count])=>sum+count*SWTroopWeight14(kind),0)+' / '+SWShipCapacity14(focusedShip)+' space. Move troops freely into spare space, or choose an equal-size swap.'),
      cargoNote&&swElement('p',{className:'sw-prep-note16',role:'status'},cargoNote),
      focusedShip&&swElement('div',{className:'sw-prep-troop-grid16'},kinds.map(kind=>{
       const incoming=transfer(kind,true),swaps=incoming?[]:SWCargoSwapOptions16(manifest,kind,focusedShip.id);
       return swElement('section',{key:kind,className:'sw-prep-cargo-group16'},swElement('div',{className:'sw-prep-troop-row16'},swElement(lu,{kind,level:el(state,kind)}),swElement('div',null,swElement('strong',null,J[kind].name),swElement('small',null,selectedArmy[kind]+' across the fleet')),stepper(kind,focusedShip.cargo[kind]||0,()=>moveTroop(kind,false),()=>{if(incoming){moveTroop(kind,true);setSwapKind(null)}else setSwapKind(kind)},!transfer(kind,false),!incoming&&!swaps.length,'Move aboard',!!swaps.length)),
        swapKind===kind&&swaps.length>0&&swElement('div',{className:'sw-prep-replace16'},swElement('p',null,'Bring '+J[kind].name+' aboard. Choose a troop to exchange:'),swaps.map(option=>{const donor=manifest.find(ship=>ship.id===option.fromId),number=manifest.indexOf(donor)+1;return swElement('button',{key:option.fromId+':'+option.returnKind,className:'secondary',onClick:()=>{const result=SWSwapCargo16(manifest,option.kind,option.fromId,option.toId,option.returnKind);if(result){setDraft({army:selectedArmy,ids,cargo:result.fleet});setCargoNote(J[kind].name+' aboard; '+J[option.returnKind].name+' moved to '+shortShip[donor.kind]+' '+number+'.');setSwapKind(null)}}},'Send '+J[option.returnKind].name+' to '+shortShip[donor.kind]+' '+number)}),swElement('button',{className:'secondary',onClick:()=>setSwapKind(null)},'Cancel swap')));
      })))),
    swElement('footer',{className:'sw-prep-footer16'},swElement('div',{'aria-live':'polite'},swElement('strong',null,readiness),swElement('small',null,status)),
     view!=='ready'?swElement('button',{className:'primary',onClick:()=>{setView('ready');setReplacement(null)}},'Done'):
     blocked?swElement('button',{className:'primary',onClick:sea&&!manifest.length?()=>setView('ships'):()=>setView('army')},sea&&!manifest.length?'Choose ships':'Choose troops'):
     swElement('button',{className:'primary sw-launch14',disabled:busy,onClick:()=>onAttack(prep)},launchLabel)))));
}
function SWShipPreview14({ship}){
 const ref=C.useRef(null);C.useEffect(()=>{let live=true;void SWLoadPresentationAssets15().then(()=>{const ctx=ref.current?.getContext('2d');if(!live||!ctx)return;ctx.clearRect(0,0,200,130);SWDrawShipRig14(ctx,{...ship,x:100,y:112,scale:1.4,fitHeight:96,heading:.4,time:0,side:'attack',hp:1,maxHp:1})});return()=>{live=false}},[ship.kind,ship.level]);return swElement('canvas',{ref,width:200,height:130,className:'sw-ship-preview14',role:'img','aria-label':SWShipRoles14[ship.kind]?.name+' level '+ship.level});
}
function SWFleet({open,onClose,state,act,busy,onBuildPort,onViewCoast}){
 const navigate=C.useContext(SWNavigationContext),[tab,setTab]=C.useState('Fleet'),[selected,setSelected]=C.useState(null),[routeId,setRoute]=C.useState('coast'),[depotOpen,setDepot]=C.useState(false),[working,setWorking]=C.useState(false),gate=C.useRef(false);
 const now=Date.now(),port=rl(state),fleet=state.fleet||[],berths=Math.min(8,port+1),ship=fleet.find(s=>s.id===selected)||fleet[0],depot=SWDepotStatus17(state),arrived=fleet.filter(s=>s.voyage?.readyAt<=now),hasDepot=xl.some(k=>depot.resources[k]>0),shipwright=fleet.some(s=>s.readyAt||s.repairReadyAt),cost=ship?nl(ship.kind,ship.level+1):{},power=ship?Math.round(wc[ship.kind].power*(1+.22*(ship.level-1))):0,route=Ec.find(r=>r.id===routeId),blocked=busy||working;
 const run=async(action,message)=>{if(gate.current||busy)return;gate.current=true;setWorking(true);try{return await act(action,message)}finally{gate.current=false;setWorking(false)}};
 const voyageReason=!route?'Choose a route':power<route.power?'Stronger ship needed':port<route.unlock?'Shipyard '+route.unlock+' needed':xl.some(k=>(route.reward[k]||0)>depot.available[k])?'Make room in the depot':null;
 let action=null,label='Choose a ship',disabled=true;
 if(ship){
  if(ship.combatBattleId)label='In battle';
  else if(ship.readyAt||ship.repairReadyAt)label=(ship.repairReadyAt?'Repairing':'Upgrading')+' · '+Qc(Math.max(0,((ship.repairReadyAt||ship.readyAt)-now)/1000));
  else if(ship.wrecked){label=shipwright?'Shipwright busy':'Repair ship';disabled=shipwright||!Z(state,SWShipRepairCost(ship));action={type:'repairShip',id:ship.id};}
  else if(ship.voyage){label=ship.voyage.readyAt<=now?'Unload & free ship':'Returns in '+Qc((ship.voyage.readyAt-now)/1000);disabled=ship.voyage.readyAt>now;action={type:'collectVoyage',id:ship.id};}
  else{label=ship.level>=10?'Medieval mastery':ship.level>=port?'Upgrade shipyard':shipwright?'Shipwright busy':'Upgrade to level '+(ship.level+1);disabled=ship.level>=10||shipwright||ship.level<port&&!Z(state,cost);action=ship.level>=port?null:{type:'upgradeShip',id:ship.id};}
 }
 const footer=swElement('footer',{className:'sw-harbor-footer17'},swElement('button',{className:'secondary',onClick:()=>{onClose();onViewCoast()}},'View coast'),tab==='Fleet'&&ship&&!depotOpen&&swElement('button',{className:'primary',disabled:blocked||disabled,onClick:()=>action?run(action,action.type==='collectVoyage'?'Cargo unloaded. Your ship is ready.':'Shipwright work started'):navigate('harborUpgrade')},working?'Working…':label),depotOpen&&swElement('button',{className:'primary',disabled:blocked||!depot.canClaim,onClick:()=>run({type:'claimHarborDepot'},'Depot supplies moved into storage')},depot.canClaim?'Move supplies into storage':'Storage is full'),swElement('button',{className:'secondary',onClick:()=>navigate('sea')},'Sea campaign'));
 return swElement(SWDialog,{open,onClose,title:'Harbor',subtitle:port?'Shipyard '+port+' · '+fleet.length+' / '+berths+' berths':'Build your coastal shipyard',className:'sw-harbor14 sw-harbor17',footer,headerActions:swElement('nav',{className:'sw-segment17','aria-label':'Harbor sections'},['Fleet','Shipyard','Routes'].map(name=>swElement('button',{key:name,'aria-pressed':tab===name,onClick:()=>{setTab(name);setDepot(false)}},name)))},
  !port?swElement('div',{className:'sw-empty-state17'},swElement(xe,{size:34}),swElement('h3',null,'Your coast is the gateway'),swElement('p',null,'Build a shipyard on the waterfront to launch transports, escorts and trading voyages.'),swElement('button',{className:'primary',onClick:()=>{onClose();onBuildPort()}},'Place coastal shipyard')):
  tab==='Fleet'?swElement('div',{className:'sw-harbor-main17'},swElement('nav',{className:'sw-vessels17','aria-label':'Your ships'},fleet.map(s=>swElement('button',{key:s.id,'aria-pressed':s.id===ship?.id&&!depotOpen,onClick:()=>{setSelected(s.id);setDepot(false)}},swElement(SWShipPreview14,{ship:s}),swElement('span',null,swElement('strong',null,SWShipRoles14[s.kind].name),swElement('small',null,'Lv '+s.level+' · '+(s.wrecked?'Needs repair':s.voyage?.readyAt<=now?'Cargo ready':s.voyage?'Trading':s.readyAt?'Upgrading':s.repairReadyAt?'Repairing':s.combatBattleId?'In battle':'Ready'))))),hasDepot&&swElement('button',{className:'sw-depot-tab17','aria-pressed':depotOpen,onClick:()=>setDepot(true)},swElement(A,{size:25}),swElement('span',null,swElement('strong',null,'Harbor depot'),swElement('small',null,'Supplies waiting'))),arrived.length>1&&swElement('button',{className:'secondary',disabled:blocked,onClick:()=>run({type:'collectFleet'},'All cargo unloaded')},'Unload '+arrived.length+' arrivals')),
   depotOpen?swElement('section',{className:'sw-depot17'},swElement('h3',null,'Your ships keep moving'),swElement('p',null,'Cargo that cannot fit in Storage waits here. New voyages reserve depot space before sailing.'),swElement(Ku,{cost:depot.resources}),swElement('small',null,Math.floor(depot.capacity).toLocaleString()+' depot capacity per resource'),!depot.canClaim&&swElement('button',{className:'secondary',onClick:()=>navigate('storage')},'Make room in Storage')):
   ship?swElement('section',{className:'sw-vessel17'},swElement('header',null,swElement('h3',null,SWShipRoles14[ship.kind].name),swElement('p',null,SWShipRoles14[ship.kind].role)),swElement('div',{className:'sw-vessel-body17'},swElement('div',{className:'sw-hull-comparison17'},[ship.level,...(!ship.wrecked&&ship.level<10?[ship.level+1]:[])].map(level=>swElement('div',{key:level},swElement(SWShipPreview14,{ship:{...ship,level}}),swElement('strong',null,(level===ship.level?'Current':'Next')+' · '+level)))),swElement('div',{className:'sw-vessel-reading17'},
    swElement('div',{className:'sw-upgrade-deltas17'},[['Troop capacity',SWShipCapacity14(ship),SWShipCapacity14({...ship,level:Math.min(10,ship.level+1)})],['Hull strength',Math.round(SWShipRoles14[ship.kind].hp*(1+.14*(ship.level-1))),Math.round(SWShipRoles14[ship.kind].hp*(1+.14*Math.min(9,ship.level)))]] .map(([name,before,after])=>swElement('div',{key:name},swElement('span',null,name),swElement('strong',null,before,ship.level<10&&swElement('b',null,' → '+after))))),
    ship.wrecked?swElement(C.Fragment,null,swElement('p',null,'The crew recovered this hull. Repair it to return to sea.'),swElement(Ku,{cost:SWShipRepairCost(ship),available:state.resources})):ship.voyage?swElement(C.Fragment,null,swElement('h4',null,ship.voyage.readyAt<=now?'Voyage complete':'Trading at sea'),swElement(Ku,{cost:ship.voyage.reward}),swElement('p',null,'Unload to make the ship available for battle. Overflow moves to the Harbor depot.')):!ship.readyAt&&!ship.repairReadyAt&&!ship.combatBattleId&&swElement(C.Fragment,null,ship.level<port&&ship.level<10&&swElement(Ku,{cost,available:state.resources}),swElement('div',{className:'sw-voyage17'},swElement('label',{className:'sw-field'},'Trading voyage',swElement('select',{'aria-label':'Voyage route',value:routeId,onChange:event=>setRoute(event.target.value)},Ec.map(r=>swElement('option',{key:r.id,value:r.id,disabled:port<r.unlock||power<r.power},r.name+' · '+Qc(r.duration))))),swElement('button',{className:'secondary',disabled:blocked||!!voyageReason,onClick:()=>run({type:'voyage',id:ship.id,kind:routeId},'Trading voyage started')},'Send voyage')),voyageReason&&swElement('p',{className:'sw-army-blocker17'},voyageReason))))):swElement('div',{className:'sw-empty-state17'},swElement('h3',null,'Launch your first vessel'),swElement('p',null,'A cutter can carry the first landing force. Add larger transports as your kingdom grows.'),swElement('button',{className:'primary',onClick:()=>setTab('Shipyard')},'Choose a ship'))):
  tab==='Shipyard'?swElement('div',{className:'sw-shipyard17'},Object.entries(SWShipRoles14).map(([kind,type])=>{const reason=port<wc[kind].unlock?'Shipyard '+wc[kind].unlock+' needed':shipwright?'Shipwright busy':fleet.length>=berths?'More berths needed':!Z(state,nl(kind))?'More supplies needed':null;return swElement('article',{key:kind},swElement(SWShipPreview14,{ship:{kind,level:1}}),swElement('div',null,swElement('h3',null,type.name),swElement('p',null,type.role),swElement('strong',null,type.capacity+' troop spaces'),swElement(Ku,{cost:nl(kind),available:state.resources})),swElement('button',{className:'primary',disabled:blocked||!!reason,onClick:()=>run({type:'buildShip',kind},'Your shipwright has started')},reason||'Build · '+Qc(wc[kind].time)))})):
  swElement('div',{className:'sw-routes17'},swElement('section',{className:'sw-depot17'},swElement('h3',null,'Trade without tying up the fleet'),swElement('p',null,'Choose a vessel in Fleet to send a voyage. Returned cargo goes into Storage, then the Harbor depot.'),hasDepot&&swElement(C.Fragment,null,swElement(Ku,{cost:depot.resources}),swElement('button',{className:'secondary',disabled:blocked||!depot.canClaim,onClick:()=>run({type:'claimHarborDepot'},'Depot supplies collected')},'Collect from depot'))),Ec.map(r=>swElement('article',{key:r.id},swElement('h3',null,r.name),swElement('p',null,Qc(r.duration)+' · Strength '+r.power+' · Shipyard '+r.unlock),swElement(Ku,{cost:r.reward}),swElement('button',{className:'secondary',onClick:()=>{setRoute(r.id);setTab('Fleet')}},'Choose a vessel')))));
}
function SWBattleControls({input,frame,selected,onSelect,onRetreat,onExitReplay,disabled,replay,speed,onSpeed,onRally,onAbility,onShipCommand,selectedShip14,onSelectShip14,navalTool14,onCancelShipCommand}){
 const reserves=hl(input),kinds=Object.keys(J).filter(k=>input.army[k]>0),sea=input.campaignType==='sea',canRally=input.rallyAt===undefined&&frame?.units.some(u=>u.side==='attack'&&!u.naval&&u.hp>0),hero=frame?.units.find(u=>u.kind==='hero'&&u.hp>0),[fleetOpen,setFleetOpen]=C.useState(false);
 const card=(kind,name,art)=>swElement('button',{key:kind,'data-troop':kind,'aria-label':'Deploy '+name+', '+reserves[kind]+' remaining','aria-pressed':selected===kind,className:'sw-deploy-card14'+(selected===kind?' selected':'')+(!reserves[kind]?' empty':''),disabled:disabled||!reserves[kind],onPointerDown:event=>{if(!disabled&&reserves[kind])SWStartTrayDrag14(event,kind,onSelect)},onClick:()=>onSelect(kind)},art,swElement('span',null,name),swElement('strong',null,'×'+reserves[kind]));
 const ships=frame?.units.filter(u=>u.naval&&u.side==='attack'&&!u.sagaEscort)||[],ship=ships.find(s=>s.shipId===selectedShip14)||ships[0];
 return swElement('div',{className:'sw-battle14'},sea&&swElement('div',{className:'sw-fleet-battle14'},swElement('button',{className:'secondary','aria-expanded':fleetOpen,onClick:()=>setFleetOpen(!fleetOpen)},swElement(xe,{size:17}),'Fleet',swElement(re,{size:14})),ships.map(s=>swElement('button',{key:s.id,'aria-label':SWShipRoles14[s.kind].name+' '+Math.round(s.hp/s.maxHp*100)+'% hull','aria-pressed':s.shipId===ship?.shipId,disabled:s.hp<=0,onClick:()=>{onSelectShip14(s.shipId);setFleetOpen(true)}},swElement('span',null,SWShipRoles14[s.kind].name),swElement('progress',{max:s.maxHp,value:s.hp}))),fleetOpen&&ship&&swElement('div',{className:'sw-fleet-orders14'},swElement('strong',null,SWShipRoles14[ship.kind].name),[['move','Move'],['focus','Focus fire'],['withdraw','Withdraw'],['ability',['cutter','cog'].includes(ship.kind)?'Repair & cover':'Rapid volley']].map(([type,name])=>swElement('button',{key:type,className:'secondary',disabled:replay||disabled||ship.hp<=0||(type==='ability'&&ship.abilityUsed),onClick:()=>{onShipCommand({shipId:ship.shipId,type});setFleetOpen(false)}},name)),swElement('button',{className:'icon-btn','aria-label':'Close fleet orders',onClick:()=>setFleetOpen(false)},swElement(je,{size:18})))),
 !replay&&swElement('div',{className:'sw-deployment-hint14',role:'status'},navalTool14?swElement('span',null,navalTool14.type==='move'?'Tap water for a sailing destination.':'Tap an enemy ship or defense to focus fire.',swElement('button',{className:'sw-cancel-order14',onClick:onCancelShipCommand},'Cancel order')):Object.values(reserves).some(n=>n>0)?(sea?'Drag a troop to the beach. Ships sail over and unload.':'Drag a troop onto the edge. Hold or paint to deploy.'):'All troops deployed'),swElement('div',{className:'sw-deploy-row14'},!replay&&swElement('div',{className:'sw-deploy-strip14','aria-label':'Your selected force'},kinds.map(k=>card(k,J[k].name,swElement(lu,{kind:k,level:input.unitLevels?.[k]||1}))),input.commander&&card('hero','Commander',swElement(nu,{id:input.commander.id}))),swElement('div',{className:'sw-battle-actions14'},swElement('button',{className:'secondary','aria-label':'Battle speed '+speed+' times',disabled:!onSpeed,onClick:onSpeed},speed+'×'),!replay&&canRally&&swElement('button',{className:'primary',disabled,onClick:onRally},'Rally'),!replay&&hero&&input.heroAt===undefined&&swElement('button',{className:'primary',disabled,onClick:onAbility},Oc[input.commander.id].ability),replay?swElement('button',{className:'secondary',onClick:onExitReplay},'Exit replay'):swElement('button',{className:'secondary',disabled,onClick:onRetreat},'Retreat'))));
}
function SWLayoutBar14({tool,onTool,overlay,onOverlay,onUndo,onRedo,onCancel,onCommit,canUndo,canRedo,count,busy,onBuildings}){
 return swElement('aside',{className:'sw-layout-bar14','aria-label':'Layout mode'},swElement('div',{className:'sw-layout-tools14'},[['road','Road'],['clear','Erase'],['tree','Tree'],['rock','Rock'],['garden','Garden']].map(([id,label])=>swElement('button',{key:id,'aria-pressed':tool===id,onClick:()=>onTool(id)},label)),swElement('button',{onClick:onBuildings},'Move buildings'),swElement('select',{'aria-label':'Layout overlay',value:overlay,onChange:e=>onOverlay(e.target.value)},[['plots','Buildable plots'],['roads','Connected roads'],['defense','Defense range'],['harbor','Harbor access']].map(([id,name])=>swElement('option',{key:id,value:id},name)))),swElement('div',{className:'sw-layout-actions14'},swElement('span',null,count+' edits'),swElement('button',{disabled:!canUndo,onClick:onUndo},'Undo'),swElement('button',{disabled:!canRedo,onClick:onRedo},'Redo'),swElement('button',{className:'secondary',onClick:onCancel},'Cancel'),swElement('button',{className:'primary',disabled:busy||!count,onClick:onCommit},'Save layout')));
}

export { SWPanelSwitcher, iu, SWDialog, SWMainMenu, SWQuickNav, SWBuildMenu14, SWJournalReports14, SWRequirements14, SWBuildingDetails14, SWCampaignBoard14, SWAbilitySummary, SWArmy, SWUnitPreview14, SWScout, SWShipPreview14, SWFleet, SWBattleControls, SWLayoutBar14 };
