const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
(async()=>{
 const R=await require('./load-rules11.cjs')(['SWSeaObjective14','SWMigrate14','SWFamilies14','SWLoadout14','SWSelectedArmy14','SWUpgradeQuote14','SWTrainQuote14','SWValidateLoadout14','SWCreateBattle14','SWPackCargo14','SWValidateCargo14','SWShipCapacity14','SWSeaDefense14','SWSeaChapters14','SWOrders14','SWDeploymentOrder14','SWValidateShipOrders14','SWTroopStats14','SWTroopWeight14','wl','Nl','hl','el','Tc']);
 let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++},bad=(f,m)=>{assert.throws(f,m);checks++};
 const now=1800000000000,clone=x=>structuredClone(x);
 function kingdom(level=7){const s=R.Y(R.Al(),now);s.buildings=s.buildings.filter(b=>b.kind!=='keep');s.buildings.push({id:'keep',kind:'keep',x:4,y:4,level},{id:'barracks-test',kind:'barracks',x:3,y:4,level},{id:'quarry-test',kind:'quarry',x:5,y:4,level},{id:'forge-test',kind:'forge',x:4,y:5,level},{id:'harbor-test',kind:'harbor',x:-2,y:3,level});s.campaign=10;s.seaCampaign=10;s.lastTick=now;s.resources={gold:0,wood:0,stone:0,food:0};for(let i=0;i<R.SWBuildingLimit(s,'storehouse');i++)s.buildings.push({id:'store-'+i,kind:'storehouse',x:6+i,y:6,level});for(const k of Object.keys(s.resources))s.resources[k]=R.SWCapacity(s);s.fleet=[{id:'transport',kind:'cog',level},{id:'escort',kind:'galley',level},{id:'siege',kind:'bombard',level}];s.army={...R.wl(),infantry:10,archer:8,cavalry:4,ram:2,trebuchet:2,healer:4};s.unitLevels=Object.fromEntries(Object.keys(R.J).map(k=>[k,level]));delete s.activeBattle;delete s.nextRaidAt;return s;}
 const fixture=JSON.parse(fs.readFileSync('/Users/chrismozer/Library/Developer/Stonewake-review/usability-audit13/phone-save.json'));const raw=fixture.state, migrated=R.Y(raw,raw.lastTick);
 for(const key of ['army','unitLevels','fleet','buildings','gems','campaign','premium'])eq(migrated[key],raw[key],'migration changed '+key);
 eq(R.Y(migrated,migrated.lastTick),migrated,'migration not idempotent');eq(migrated.seaCampaign,0);ok(migrated.loadouts14[0].slots.length<=6);ok(migrated.gems<raw.gems+1000,'gem grant repeated');
 const keep=migrated.buildings.find(b=>b.kind==='keep'),quote=R.SWUpgradeQuote14(migrated,keep);ok(!quote.allowed);ok(quote.requirements.some(r=>r.id==='storage'&&!r.met&&r.action.type==='build'));ok(quote.requirements.some(r=>r.id==='quarry'&&!r.met));bad(()=>R.Ul(migrated,{type:'upgrade',id:keep.id},migrated.lastTick));
 const economy=[];for(let level=1;level<=10;level++){const s=kingdom(level),q=R.SWUpgradeQuote14(s,s.buildings.find(b=>b.kind==='keep'));economy.push({level,capacity:R.SWCapacity(s),storeLimit:R.SWBuildingLimit(s,'storehouse'),armyCapacity:R.Pl(s),keepCost:q.cost,allowed:q.allowed});if(level<10){ok(q.allowed,'Keep '+(level+1)+' has a capacity/progression deadlock');ok(R.Ul(s,{type:'upgrade',id:'keep'},now).buildings.find(b=>b.id==='keep').readyAt>now)}else ok(!q.allowed);for(const kind of ['barracks','quarry','lumber','farm','storehouse','harbor'])ok(Number.isFinite(R.SWBuildingLimit(s,kind))&&R.SWBuildingLimit(s,kind)>0,kind+' has no finite limit');for(const kind of Object.keys(R.J)){const a=R.SWTroopStats14(s,kind,Math.max(1,level-1)),b=R.SWTroopStats14(s,kind,level);ok(b.hp>=a.hp&&b.damage>=a.damage,'troop stats regressed')}}
 let s=kingdom(),force={id:'assault',name:'Shoreguard',slots:['infantry','archer','healer'],counts:{infantry:8,archer:6,healer:3}};s=R.Ul(s,{type:'saveLoadout',loadout:force},now);eq(R.SWLoadout14(s),force);eq(R.Nl(R.SWSelectedArmy14(s)),17);bad(()=>R.SWValidateLoadout14(s,{...force,slots:['infantry','shieldbearer'],counts:{infantry:2,shieldbearer:2}}));bad(()=>R.SWValidateLoadout14(s,{...force,counts:{...force.counts,infantry:100}}));s.army.healer=0;const training=R.SWTrainQuote14(s),trained=R.Ul(s,{type:'trainLoadout'},now);eq(trained.army.healer,3);eq(Math.round(s.resources.gold-trained.resources.gold),training.cost.gold);const poor=clone(s);poor.resources={gold:0,wood:0,stone:0,food:0};bad(()=>R.Ul(poor,{type:'trainLoadout'},now));eq(poor.army.healer,0);
 const land=R.SWCreateBattle14(s,{kind:'campaign',defense:R.Gl(0)},{army:R.SWSelectedArmy14(s)},123);eq(land.fleet14,[]);eq(land.navalVersion,0);eq(s.army.infantry,10);bad(()=>R.SWCreateBattle14(s,{kind:'campaign',defense:R.Gl(0)},{army:{...land.army,archer:-1}},1));bad(()=>R.SWCreateBattle14(s,{kind:'campaign',defense:R.Gl(0)},{army:{...land.army,unknown:1}},1));
 const pack=R.SWPackCargo14(s,s.fleet.map(v=>v.id),s.army);const sea=R.SWCreateBattle14(s,{kind:'sea',campaignIndex:0},{army:pack.army,fleet:pack.fleet},123);eq(sea.campaignType,'sea');ok(sea.fleet14.length===3);eq(sea.fleet14.map(v=>v.kind),['cog','galley','bombard']);bad(()=>R.SWValidateCargo14(s,[pack.fleet[0],pack.fleet[0]],pack.army));bad(()=>R.SWValidateCargo14(s,[{id:'transport',kind:'cog',level:99,cargo:{trebuchet:80}}],s.army));bad(()=>R.SWValidateCargo14(s,[{id:'not-owned',cargo:{}}],s.army));const forged=clone(pack.fleet);forged[0].level=100;eq(R.SWValidateCargo14(s,forged,pack.army)[0].level,7);bad(()=>R.SWOrders14(sea,[{kind:'infantry',x:4,y:4,time:0,shipId:'transport'}]));bad(()=>R.SWOrders14(sea,[{kind:'infantry',x:-1,y:4,time:0,shipId:'not-owned'}]));bad(()=>R.SWValidateShipOrders14(sea,[{type:'move',shipId:'transport',x:4,y:4,time:0}]));bad(()=>R.SWValidateShipOrders14(sea,[{type:'move',shipId:'transport',x:-4,y:4,time:-1}]));
 for(const ship of sea.fleet14)for(const [kind,n]of Object.entries(ship.cargo))for(let k=0;k<n;k++)sea.orders.push({kind,shipId:ship.id,x:-1,y:ship.id==='escort'?6:2,time:0});const simulated=R.Kl(sea);eq(simulated,R.Kl(sea),'sea replay is not deterministic');ok(simulated.frames[0].units.filter(u=>!u.naval&&!u.building&&u.side==='attack').length===0,'troops teleported before ship arrival');ok(simulated.landedTroops>0,'no troops landed');eq(simulated.landedTroops+simulated.rescuedTroops,R.Nl(sea.army));ok(Object.keys(simulated.navalSurvivors).length===3);ok(simulated.frames.some(f=>f.shots.some(s=>s.kind==='naval')),'ships never fired');
 const destroyedKeep={kind:'keep',building:true,side:'defend',hp:0,maxHp:100};eq(R.SWSeaObjective14(sea,[destroyedKeep]).won,false,'bombardment won without landing');eq(R.SWSeaObjective14(sea,[destroyedKeep,{side:'attack',naval:false,building:false,hp:50}]).won,true);eq(R.SWSeaObjective14({...sea,seaMode:'blockade'},[destroyedKeep,{side:'attack',hp:50},{side:'defend',naval:true,hp:20}]).won,false);
 const emptyOrders=R.Kl({...sea,orders:[]});eq(emptyOrders.won,false,'fleet alone captured town');eq(emptyOrders.rescuedTroops,R.Nl(sea.army));
 const withdraw={...sea,shipOrders14:[{shipId:'transport',type:'withdraw',time:0}]},withdrawn=R.Kl(withdraw);ok(withdrawn.rescuedTroops>=simulated.rescuedTroops);ok(withdrawn.frames.at(-1).units.find(u=>u.shipId==='transport').x<-9,'withdraw command failed');
 for(let i=0;i<10;i++){const def=R.SWSeaDefense14(i);eq(new Set(def.buildings.map(b=>b.x+','+b.y)).size,def.buildings.length,'overlapping coastal structures');}
 const payout=clone(s);payout.seaCampaign=0;payout.resources={gold:0,wood:0,stone:0,food:0};const gems=payout.gems,landProgress=payout.campaign;R.Fu(payout,'sea',0,sea,{won:true},true,now);eq(payout.seaCampaign,1);eq(payout.campaign,landProgress);eq(payout.gems,gems+30);R.Fu(payout,'sea',0,sea,{won:true},true,now);eq(payout.gems,gems+30,'replay minted gems');
 const layout=kingdom(),before=clone(layout),action={type:'commitLayout',actions:[{type:'landscape',kind:'road',x:10,y:10},{type:'rotate',id:'keep'}]};const laid=R.Ul(layout,action,now);eq(layout,before,'layout mutated original');ok(laid.terrain.some(t=>t.x===10&&t.y===10&&t.kind==='road'));bad(()=>R.Ul(layout,{type:'commitLayout',actions:[...action.actions,{type:'upgrade',id:'keep'}]},now));eq(layout,before,'failed layout was not atomic');
 const legacy=JSON.parse(fs.readFileSync('scripts/fixtures/combat-legacy.json'));eq(crypto.createHash('sha256').update(JSON.stringify(R.Kl(legacy.input))).digest('hex'),legacy.sha256,'legacy replay changed');
 fs.mkdirSync('planning/build14',{recursive:true});fs.writeFileSync('planning/build14/rules-evidence.json',JSON.stringify({checks,economy,sea:{duration:simulated.duration,won:simulated.won,landed:simulated.landedTroops,rescued:simulated.rescuedTroops},timestamp:new Date().toISOString()},null,2));console.log('PASS '+checks+' build 14 checks: migration, capacity graph, shared upgrades, loadouts, cargo, landings, ship orders, rewards, layout rollback and exact replay.');
})().catch(e=>{console.error(e.name+': '+e.message);process.exitCode=1});
