const {chromium}=require('/opt/homebrew/lib/node_modules/openclaw/node_modules/playwright-core');
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');const root=path.resolve(__dirname,'..'),legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/combat-legacy.json'),'utf8'));
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/assets/index-BPhrguZ3.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'Stonewake/Web/assets/index-BPhrguZ3.js'),'utf8')+'\nwindow.__combat9={Kl,Al,Ul,Y,wl,J,Gl,Tl,SWBattleWorker,SWApplyTroopStats,SWTroopDamageFactor,SWTroopIncomingFactor,SWTroopSplash,SWMedicHeals,SWTroopAbilities,SWTroopAbility,SWNavalShips,SWNavalEligible};'}));await page.addInitScript(()=>{window.__STONEWAKE_INTRO_SEEN__=true;window.webkit={messageHandlers:{stonewake:{postMessage(){}}}}});await page.goto('http://localhost:8768');await page.waitForFunction(()=>window.__combat9);
const old=await page.evaluate(input=>window.__combat9.Kl(input),legacy.input);assert.equal(crypto.createHash('sha256').update(JSON.stringify(old)).digest('hex'),legacy.sha256,'old replay changed after new troop/naval flags');
const result=await page.evaluate(input=>{const t=window.__combat9,check=(x,m)=>{if(!x)throw Error(m)},unit=(kind,level)=>t.SWApplyTroopStats({id:kind,kind,level,side:'attack',hp:100,maxHp:100,damage:20,range:2,speed:1,cooldown:2,x:0,y:0});
check(t.J.trebuchet.unlock===5&&t.J.trebuchet.maxLevel===10&&t.wl().trebuchet===0,'trebuchet catalog/default');
for(const kind of Object.keys(t.J)){const milestones=t.SWTroopAbilities(kind);check(milestones.length===3&&milestones.map(m=>m.level).join()==='3,6,9','milestones missing '+kind);check(!t.SWTroopAbility(kind,2)&&t.SWTroopAbility(kind,99).level===9,'milestone cap '+kind)}
const enemy={id:'enemy',side:'defend',kind:'tower',building:true,hp:100,maxHp:100,x:1,y:0},near={...enemy,id:'near',x:1.5};
check(unit('archer',6).cooldown===1.6&&unit('archer',3).range===2.35,'archer range/fire rate');check(t.SWTroopDamageFactor(unit('cavalry',6),enemy)===1.75,'cavalry impact');check(t.SWTroopIncomingFactor(unit('infantry',9),[])===.75,'infantry armor');check(t.SWTroopDamageFactor(unit('trebuchet',1),enemy)===2.4,'trebuchet structure damage');check(t.SWTroopSplash(unit('trebuchet',6),enemy,[enemy,near])[0]?.fraction===.65,'trebuchet splash');check(t.SWTroopSplash(unit('grenadier',6),enemy,[enemy,near])[0]?.fraction===.9,'grenadier shrapnel');
const crossbow=unit('crossbow',9);crossbow.attackCount=2;check(Math.abs(t.SWTroopDamageFactor(crossbow,enemy)-2.45)<1e-9,'precision third shot');
check(t.SWTroopDamageFactor(unit('spearman',6),{kind:'cavalry'})===1.5,'spearman cavalry counter');check(t.SWTroopDamageFactor(unit('ram',6),{kind:'gate'})===1.5&&unit('ram',3).maxHp===120,'ram frame and gate breaker');check(t.SWTroopDamageFactor(unit('scout',6),{kind:'farm'})===1.65&&unit('scout',9).cooldown===1.4,'scout raids');check(t.SWTroopDamageFactor(unit('knight',6),enemy)===1.5&&t.SWTroopIncomingFactor(unit('knight',9),[])===.75,'knight fortress combat');const shield=unit('shieldbearer',9),ally=unit('infantry',1);check(Math.abs(shield.maxHp-115)<1e-9&&Math.abs(t.SWTroopIncomingFactor(shield,[])-.455)<1e-9&&t.SWTroopIncomingFactor(ally,[ally,shield])===.88,'shield cover and bulwark');check(t.SWTroopDamageFactor(unit('cannon',9),enemy)===1.35&&t.SWTroopSplash(unit('cannon',6),enemy,[enemy,near])[0]?.fraction===.45,'cannon siege ammunition and splash');check(t.SWTroopSplash(unit('archer',9),enemy,[enemy,near]).length===1&&t.SWTroopSplash(unit('infantry',6),enemy,[enemy,near])[0].fraction===.35,'archer split volley and infantry cleave');
const medic=unit('healer',9),patient={id:'patient',side:'attack',kind:'infantry',hp:10,maxHp:100,x:1,y:0},patient2={...patient,id:'second',hp:40,x:1.4};const heals=t.SWMedicHeals(medic,patient,[medic,patient,patient2]);check(heals.length===2&&Math.abs(heals[0].amount-59.36)<1e-9&&heals[1].amount===heals[0].amount*.5,'triage/chain heal');
const base={...input,healerTacticsVersion:1,troopAbilitiesVersion:1,navalVersion:2,navalSupport:{id:'navy',kind:'galley',level:1},orders:[],army:t.wl()};
const weak={...base,defense:{name:'Coastal keep',level:1,buildings:[{id:'keep',kind:'keep',x:3,y:3,level:1}]}};
const living=t.Kl(weak),shots=living.frames.flatMap(f=>f.shots).filter(s=>s.kind==='naval');check(shots.length>=5,'navy did not sustain fire');const navy=living.frames[0].units.find(u=>u.naval);check(navy?.hp===navy.maxHp&&navy.shipId==='navy','live ship absent');check(living.frames.some(f=>f.shots.some(s=>s.side==='defend'&&s.tx===-3&&s.ty===3)),'defenders did not target ship');check(living.frames.at(-1).units.find(u=>u.naval).hp<navy.hp,'ship took no damage');check(JSON.stringify(living)===JSON.stringify(t.Kl(weak)),'naval battle nondeterministic');
const severe={...base,defense:{name:'Coastal batteries',level:6,buildings:[{id:'keep',kind:'keep',x:3,y:3,level:6},{id:'gun1',kind:'bastion',x:0,y:2,level:6},{id:'gun2',kind:'bastion',x:0,y:4,level:6}]}};const wreck=t.Kl(severe),death=wreck.frames.find(f=>f.units.some(u=>u.naval&&u.hp<=0));check(wreck.navalSurvivors.navy===false&&wreck.navalHealth.navy===0&&death,'ship cannot be destroyed');check(!wreck.frames.filter(f=>f.time>death.time).some(f=>f.shots.some(s=>s.kind==='naval')),'wreck kept firing');
check(t.SWNavalShips({fleet:[{id:'wreck',kind:'galley',level:1,wrecked:true},{id:'repair',kind:'galley',level:1,repairReadyAt:10},{id:'ready',kind:'galley',level:1}]}).map(s=>s.id).join()==='ready','wreck/repair selectable');check(t.SWNavalEligible({kind:'campaign',campaignIndex:0,defense:input.defense})&&t.SWNavalEligible({kind:'practice',defense:input.defense}),'all bases not naval eligible');
// Equal level and seed: milestone version changes combat outcome through its mechanics, not extra levels.
const veteran={...input,troopAbilitiesVersion:1,healerTacticsVersion:1,unitLevels:{shieldbearer:6,archer:6,healer:6}},oldVeteran={...veteran};delete oldVeteran.troopAbilitiesVersion;const improved=t.Kl(veteran),plain=t.Kl(oldVeteran);check(JSON.stringify(improved.survivors)!==JSON.stringify(plain.survivors)||improved.destruction!==plain.destruction||improved.duration!==plain.duration,'milestones have no actual battle effect');
let state=t.Al();state.buildings[0].level=4;state.buildings.push({id:'barracks-test',kind:'barracks',level:5,x:1,y:5});state.resources={gold:9999,wood:9999,stone:9999,food:9999};let locked=false;try{t.Ul(state,{type:'recruit',kind:'trebuchet',count:1})}catch{locked=true}check(locked,'trebuchet unlocked below Keep5');state.buildings[0].level=5;state=t.Ul(state,{type:'recruit',kind:'trebuchet',count:1});check(state.army.trebuchet===1,'trebuchet cannot recruit at Keep5');state.buildings[0].level=10;state.unitLevels.trebuchet=10;let capped=false;try{t.Ul(state,{type:'researchUnit',kind:'trebuchet'})}catch{capped=true}check(capped,'troop can exceed level10');
return {sustainedShots:shots.length,shipDamage:navy.hp-living.frames.at(-1).units.find(u=>u.naval).hp,wreckAt:death.time,plain:{destruction:plain.destruction,duration:plain.duration},milestones:{destruction:improved.destruction,duration:improved.duration},trebuchet:state.army.trebuchet};},legacy.input);
const fleetAudit=await page.evaluate(input=>{const t=window.__combat9;return t.Tl.map((stage,index)=>{const result=t.Kl({...input,defense:t.Gl(index),army:t.wl(),orders:[],healerTacticsVersion:1,troopAbilitiesVersion:1,navalVersion:2,navalSupport:{id:'coastal-test',kind:'galley',level:1}});const shots=result.frames.flatMap(f=>f.shots),defenderShots=shots.filter(s=>s.side==='defend'&&s.tx===-3&&s.ty===3);if(!defenderShots.length)throw Error('Campaign '+index+' cannot fire on ships');if(defenderShots.some(s=>s.kind==='infantry'))throw Error('Ground guard targeted a ship');return {stage:stage.name,level:stage.level,survived:result.navalSurvivors['coastal-test'],health:result.navalHealth['coastal-test'],wreckAt:result.frames.find(f=>f.units.some(u=>u.naval&&u.hp<=0))?.time,shots:shots.filter(s=>s.kind==='naval').length};});},legacy.input);
assert(fleetAudit.some(stage=>!stage.survived),'No actual campaign base can sink a ship');assert(fleetAudit.every(stage=>stage.health<1),'Some actual campaign defenses cannot damage ships');
const workerAudit=await page.evaluate(async input=>{const t=window.__combat9,worker=t.SWBattleWorker();try{if(!worker.threaded)throw Error('Worker failed to start');const battle={...input,healerTacticsVersion:1,troopAbilitiesVersion:1,navalVersion:2,navalSupport:{id:'worker-navy',kind:'bombard',level:3}},expected=t.Kl(battle);const result=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Worker timed out')),20000);worker.request(battle,r=>{clearTimeout(timeout);resolve(r)},e=>{clearTimeout(timeout);reject(Error(e))})});if(!worker.threaded)throw Error('Worker fell back to blocking simulation');if(JSON.stringify(result)!==JSON.stringify(expected))throw Error('Worker result differs from direct engine');const old=await new Promise((resolve,reject)=>worker.request(input,resolve,reject));if(JSON.stringify(old)!==JSON.stringify(t.Kl(input)))throw Error('Worker changed version4 legacy battle');const callbacks=[];const latest={...battle,navalSupport:{id:'worker-navy',kind:'bombard',level:4}};const queued=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Queued Worker timed out')),20000);worker.request({...battle,seed:17},()=>callbacks.push('obsolete'));worker.request({...battle,seed:19},()=>callbacks.push('superseded'));worker.request(latest,r=>{clearTimeout(timeout);callbacks.push('latest');resolve(r)},reject)});if(callbacks.join()!=='latest'||JSON.stringify(queued)!==JSON.stringify(t.Kl(latest)))throw Error('Rapid forecast requests lost newest input');return {threaded:worker.threaded,frames:result.frames.length,legacyFrames:old.frames.length,rapidRequests:3,callbacks};}finally{worker.close()}},legacy.input);
assert.deepEqual(errors,[],'application page errors');console.log('PASS actual campaign defenses sink unsupported ships without ground guard attacks, true background worker equals deterministic engine',fleetAudit,workerAudit);
console.log('PASS legacy hash, all 13 troop milestones, trebuchet unlock/cap, meaningful role effects, seeded live navy fire/damage/destruction and repair exclusion',result);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
