const {chromium}=require('/opt/homebrew/lib/node_modules/openclaw/node_modules/playwright-core');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),out='/Users/chrismozer/Library/Developer/Stonewake-review/build8';fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(fs.readFileSync('/Users/chrismozer/Library/Developer/Stonewake-backups/pre-build8-kingdom.json','utf8'));
fixture.battle=null;fixture.input=null;fixture.time=0;fixture.state.activeBattle=null;fixture.reports=[];
fixture.state.army=Object.fromEntries(Object.keys(fixture.state.army).map(k=>[k,0]));fixture.state.army.shieldbearer=4;fixture.state.army.healer=2;
for(const ship of fixture.state.fleet){delete ship.combatBattleId;ship.voyage={route:'coast',startedAt:Date.now()-181000,readyAt:Date.now()-1000,reward:{gold:25,wood:40,stone:0,food:120}};}
const warship=fixture.state.fleet.find(s=>s.kind==='galley');assert(warship,'fixture needs warship');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:840,height:360}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/assets/index-BPhrguZ3.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'Stonewake/Web/assets/index-BPhrguZ3.js'),'utf8')+'\nwindow.__navalTest={Kl,Y,Ul,SWNavalShips};'}));
 await page.addInitScript(save=>{window.__STONEWAKE_SAVE__=save;window.__STONEWAKE_INTRO_SEEN__=true;window.__saves=[];window.webkit={messageHandlers:{stonewake:{postMessage(m){if(m.kind==='save'){window.__lastSave=JSON.parse(m.payload);window.__saves.push(window.__lastSave);setTimeout(()=>window.dispatchEvent(new CustomEvent('stonewake-save-status',{detail:{saved:true}})),0)}}}}};},fixture);
 const menu=async name=>{await page.getByRole('button',{name:'Kingdom menu',exact:true}).click();await page.locator('.kingdom-menu').getByRole('button',{name,exact:true}).click()};
 const close=async()=>{await page.getByRole('button',{name:'Close',exact:true}).last().click()};
 await page.goto('http://localhost:8768');await page.waitForSelector('.map-holder canvas');
 await menu('Frontier');await page.locator('.campaign-node').filter({hasText:'Greyhaven'}).click();const support=page.getByRole('combobox',{name:'Naval support',exact:true});await support.waitFor();assert(await support.isDisabled(),'cargo-pending warship should not be available');await close();
 await menu('Fleet');const cargo=page.getByRole('button',{name:'Collect cargo',exact:true});assert.equal(await cargo.count(),2,'both returned ships must offer cargo');await cargo.first().click();await page.waitForTimeout(100);await cargo.first().click();await page.waitForFunction(()=>window.__lastSave.state.fleet.every(s=>!s.voyage));await close();
 await page.locator('.campaign-node').filter({hasText:'Greyhaven'}).click();await support.waitFor();assert(await support.isEnabled());assert.equal(await support.locator('option').count(),2,'only warship plus no-ship option allowed');await support.selectOption(warship.id);await page.screenshot({path:out+'/naval-scout-840.png'});await page.getByRole('button',{name:'Attack',exact:true}).click();await page.locator('.battle-world').waitFor();await page.waitForFunction(id=>window.__lastSave?.state?.fleet.find(s=>s.id===id)?.combatBattleId===window.__lastSave?.state?.activeBattle&&!!window.__lastSave?.input?.navalSupport,warship.id);
 const started=await page.evaluate(()=>window.__lastSave);assert.equal(started.input.navalSupport.id,warship.id);assert.equal(started.input.navalVersion,1);assert.equal(started.input.healerTacticsVersion,1);assert(started.state.activeBattle,'reservation missing active battle');
 const denied=await page.evaluate(id=>{const{Ul,SWNavalShips}=window.__navalTest,s=window.__lastSave.state;const reject=a=>{try{Ul(s,a);return false}catch{return true}};return !SWNavalShips(s).some(ship=>ship.id===id)&&reject({type:'voyage',id,kind:'coast'})&&reject({type:'upgradeShip',id})},warship.id);assert(denied,'reserved ship can still be selected or reused');
 await page.addInitScript(save=>window.__STONEWAKE_SAVE__=save,started);await page.reload();await page.locator('.battle-world').waitFor();await page.waitForFunction(id=>window.__lastSave?.state?.fleet.find(s=>s.id===id)?.combatBattleId===window.__lastSave?.state?.activeBattle,warship.id);
 const fire=page.getByRole('button',{name:'Fire naval broadside',exact:true});await fire.waitFor();assert(await fire.isEnabled(),'broadside unavailable after reload');await fire.click();const used=page.getByRole('button',{name:'Naval broadside used',exact:true});await used.waitFor();assert(await used.isDisabled(),'broadside reusable after firing');await page.waitForFunction(()=>Number.isFinite(window.__lastSave?.input?.navalAt));await page.waitForFunction(()=>window.__lastSave?.time>0.2);const fired=await page.evaluate(()=>window.__lastSave);const strikes=await page.evaluate(input=>window.__navalTest.Kl(input).frames.flatMap(f=>f.shots).filter(s=>s.kind==='naval').length,fired.input);assert.equal(strikes,1,'one broadside order yielded multiple shots');await page.screenshot({path:out+'/naval-battle-840.png'});
 await page.addInitScript(save=>window.__STONEWAKE_SAVE__=save,fired);await page.reload();await page.getByRole('button',{name:'Naval broadside used',exact:true}).waitFor();assert(await page.getByRole('button',{name:'Naval broadside used',exact:true}).isDisabled(),'reload restored broadside');
 await page.getByRole('button',{name:'Retreat',exact:true}).click();await page.waitForFunction(()=>window.__lastSave?.state?.activeBattle===null&&window.__lastSave?.reports?.length>0);const completed=await page.evaluate(()=>window.__lastSave);assert(!completed.state.fleet.find(s=>s.id===warship.id).combatBattleId,'ship not released on finish');assert.equal(completed.state.army.shieldbearer,4,'undeployed troops not returned');assert.equal(completed.state.army.healer,2,'undeployed medics not returned');assert.equal(completed.reports[0].input.navalAt,fired.input.navalAt,'report did not preserve broadside order');assert.equal(completed.reports[0].input.navalSupport.id,warship.id,'report lost supporting ship');
 const available=await page.evaluate(state=>window.__navalTest.SWNavalShips(window.__navalTest.Y(JSON.parse(JSON.stringify(state)))).map(s=>s.id),completed.state);assert(available.includes(warship.id),'released ship unavailable after save migration');assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS actual save clone: cargo collection, coastal scout warship selection, battle snapshot, reservation/reload, action rejection, one broadside/reload, retreat release, troop return and report persistence');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
