const {chromium}=require('/opt/homebrew/lib/node_modules/openclaw/node_modules/playwright-core');
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:932,height:430}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/assets/index-BPhrguZ3.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'Stonewake/Web/assets/index-BPhrguZ3.js'),'utf8')+'\nwindow.__naval10={Kl,Gl,wl,SWEnemyNavy,SWNavalStep,SWCreateNavalUnit,SWBattleWorker};'}));await page.addInitScript(()=>{window.__STONEWAKE_INTRO_SEEN__=true;window.webkit={messageHandlers:{stonewake:{postMessage(){}}}}});await page.goto('http://localhost:8768');await page.waitForFunction(()=>window.__naval10);
 for(const file of ['combat-legacy.json','naval-v2-legacy.json']){const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures',file))),result=await page.evaluate(input=>window.__naval10.Kl(input),fixture.input);assert.equal(crypto.createHash('sha256').update(JSON.stringify(result)).digest('hex'),fixture.sha256,'historical replay changed: '+file);}
 const result=await page.evaluate(async()=>{const t=window.__naval10,check=(value,message)=>{if(!value)throw Error(message)},army=t.wl();army.infantry=6;
 const base={defense:t.Gl(0),army,orders:[],bonus:1,front:'center',rulesVersion:4,healerTacticsVersion:1,troopAbilitiesVersion:1,navalVersion:3,navalSupport:{id:'own-galley',kind:'galley',level:1},enemyNavy:t.SWEnemyNavy(t.Gl(0)),seed:77193};
 const battle=t.Kl(base),shots=battle.frames.flatMap(f=>f.shots.map(s=>({...s,time:f.time}))),duelShots=shots.filter(s=>s.kind==='naval'&&s.impact==='ship'),own=battle.frames[0].units.find(u=>u.naval&&u.side==='attack'),enemy=battle.frames[0].units.find(u=>u.naval&&u.side==='defend');
 check(own&&enemy,'both fleets not instantiated');check(duelShots.some(s=>s.side==='attack')&&duelShots.some(s=>s.side==='defend'),'both ships must fire');check(battle.frames.some(f=>f.units.some(u=>u.id===own.id&&u.hp<own.hp)),'own ship never damaged');check(battle.frames.some(f=>f.units.some(u=>u.id===enemy.id&&u.hp<enemy.hp)),'enemy ship never damaged');check(battle.frames.some(f=>f.units.some(u=>u.id===own.id&&Math.hypot(u.x-own.x,u.y-own.y)>.4)),'own ship never sailed');check(battle.frames.some(f=>f.units.some(u=>u.id===enemy.id&&Math.hypot(u.x-enemy.x,u.y-enemy.y)>.2)),'enemy ship never sailed');check(battle.frames.every(f=>f.units.filter(u=>u.naval).every(u=>u.x<=-3&&Number.isFinite(u.heading))),'ships crossed onto land or lost heading');
 const sailingFrames=battle.frames.filter(f=>f.time>=5&&f.time<=20&&f.units.some(u=>u.naval&&u.side==='attack'&&Math.hypot(u.vx,u.vy)>.02)).length;check(sailingFrames>=12,'friendly ship stopped sailing throughout the duel');
 const sunkEnemy=battle.frames.flatMap(f=>f.units).find(u=>u.id===enemy.id&&u.hp===0);check(sunkEnemy&&Number.isFinite(sunkEnemy.sunkAt),'enemy sinking not recorded');check(!shots.some(s=>s.sourceId===enemy.id&&s.time>sunkEnemy.sunkAt+.5),'sunken enemy kept firing');const coastShots=shots.filter(s=>s.sourceId===own.id&&s.impact==='structure');check(coastShots.length&&coastShots.every(s=>s.time>sunkEnemy.sunkAt),'friendly fleet bombarded before winning sea lane');check(battle.enemyNavalSurvivors[enemy.shipId]===false,'enemy survival outcome missing');check(JSON.stringify(battle)===JSON.stringify(t.Kl(base)),'duel nondeterministic');
 const outmatched=t.Kl({...base,defense:t.Gl(9),enemyNavy:[{id:'heavy-patrol',kind:'bombard',level:10}],army:t.wl()});const wreck=outmatched.frames.flatMap(f=>f.units).find(u=>u.naval&&u.side==='attack'&&u.hp===0);check(wreck&&wreck.sunkAt>10&&outmatched.navalSurvivors['own-galley']===false,'strong enemy navy cannot sink ship or destroys it immediately');check(!outmatched.frames.some(f=>f.time>wreck.sunkAt+.5&&f.shots.some(s=>s.sourceId===wreck.id)),'friendly wreck kept firing');
 // With no friendly ship, the patrol can cover the nearby coast, not the whole ground battle.
 const patrol=t.SWCreateNavalUnit({id:'shore',kind:'galley',level:1},'defend');patrol.x=-3.2;patrol.y=.8;const near={id:'shore-soldier',side:'attack',kind:'infantry',x:0,y:1,hp:100,maxHp:100},center={...near,id:'inland-soldier',x:5,y:5};const hit=t.SWNavalStep(patrol,[patrol,near,center],10);check(hit?.target.id===near.id&&Math.abs(hit.damage-9.9)<1e-9,'shore support damage/range incorrect');check(!t.SWNavalStep(patrol,[patrol,center],20),'patrol can bombard central army');
 const shoreArmy=t.wl();shoreArmy.cannon=4;const noShip={...base,navalSupport:undefined,army:shoreArmy,orders:[0,1,2,3].map(i=>({kind:'cannon',x:-2,y:i,time:0}))};const coastal=t.Kl(noShip),friendlyGroundShots=coastal.frames.flatMap(f=>f.shots).filter(s=>s.side==='attack'&&s.kind==='cannon'&&s.tx< -2.6);check(friendlyGroundShots.length,'coastal ranged troops cannot fight enemy ships');check(!coastal.frames.flatMap(f=>f.shots).some(s=>s.side==='attack'&&s.kind==='infantry'&&s.tx< -2.6),'melee infantry attacked a ship');
 const worker=t.SWBattleWorker();let forecast;try{check(worker.threaded,'Worker unavailable');forecast=await new Promise((resolve,reject)=>worker.request(base,resolve,reject));check(worker.threaded,'Worker fell back');check(JSON.stringify(forecast)===JSON.stringify(battle),'Worker navy result differs');}finally{worker.close()}
 return {sailingFrames,duelShots:duelShots.length,enemySunkAt:sunkEnemy.sunkAt,coastalShots:coastShots.length,ownSunkAt:wreck.sunkAt,cannonShotsAtShips:friendlyGroundShots.length,workerFrames:forecast.frames.length,ownFinalHull:battle.navalHealth['own-galley']};
 });assert.deepEqual(errors,[]);console.log('PASS exact old/v2 replay hashes; moving two-sided fleet duel, shore transition, both sinking outcomes, coastal-only ground support and true Worker determinism',result);
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
