const {chromium}=require('/opt/homebrew/lib/node_modules/openclaw/node_modules/playwright-core');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),fixture=JSON.parse(fs.readFileSync('/Users/chrismozer/Library/Developer/Stonewake-backups/post-install-build10-kingdom.json','utf8'));
// A cloned phone save is the only state touched by this test.
fixture.state.activeBattle=null;fixture.battle=null;fixture.input=null;fixture.time=0;fixture.reports=[];fixture.state.city={jobs:0,crafted:0,raidWins:0,raidCount:0,requests:{}};fixture.state.resources={gold:2500,wood:2500,stone:2500,food:2500};
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:932,height:430}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/assets/index-BPhrguZ3.js',route=>{let source=fs.readFileSync(path.join(root,'Stonewake/Web/assets/index-BPhrguZ3.js'),'utf8');const needle='  let kn = z?.frames.reduce';assert(source.includes(needle));source=source.replace(needle,"  window.__defenseHooks={finish:xn,advance:ut,snapshot:()=>({state:r.current,act:mn,battle:L,input:R,result:B,replay:St,forecast:z,time:lt,reports:vt}),close:En};\n"+needle);return route.fulfill({contentType:'text/javascript',body:source+'\nwindow.__defense={Y,Al,Kl,SWDefenseInput,SWResolveDefense,SWCityRequest,Ul,SWCivicProject,SWCivicBonuses,SWRaidStatus};'});});
 await page.addInitScript(save=>{window.__clockOffset=0;const realNow=Date.now;Date.now=()=>realNow()+window.__clockOffset;window.__STONEWAKE_SAVE__=JSON.parse(sessionStorage.getItem('defense-test-save')||'null')||save;window.__STONEWAKE_INTRO_SEEN__=true;window.webkit={messageHandlers:{stonewake:{postMessage(m){if(m.kind==='save'){window.__lastSave=JSON.parse(m.payload);sessionStorage.setItem('defense-test-save',m.payload);setTimeout(()=>window.dispatchEvent(new CustomEvent('stonewake-save-status',{detail:{saved:true}})),0)}}}}}},fixture);
 await page.goto('http://localhost:8768');await page.waitForFunction(()=>window.__defense&&window.__defenseHooks&&document.querySelector('canvas'));
 // Start a real stage, inspect locked requirements, then claim only its completed reward.
 await page.locator('.sw-quick-nav').getByRole('button',{name:'City',exact:true}).click();await page.locator('.sw-city-dialog .sw-tabs').getByRole('button',{name:'Projects',exact:true}).click();
 const locked=page.locator('[data-project=market]');await locked.getByRole('button',{name:'View requirements',exact:true}).click();await locked.getByRole('button',{name:'Plan city',exact:true}).click();await page.locator('.sw-land-tools').waitFor();assert.equal(await page.locator('[role=dialog]').count(),0,'Requirement navigation stacked the project dialog');
 await page.getByRole('button',{name:'Close landscape tools',exact:true}).click();await page.locator('.sw-quick-nav').getByRole('button',{name:'City',exact:true}).click();await page.locator('.sw-city-dialog .sw-tabs').getByRole('button',{name:'Projects',exact:true}).click();
 const project=page.locator('[data-project=waterfront]'),before=await page.evaluate(()=>({gems:window.__defenseHooks.snapshot().state.gems,quote:window.__defense.SWCivicProject(window.__defenseHooks.snapshot().state,'waterfront')}));assert.equal(before.quote.status,'available');await project.getByRole('button',{name:/^Start /}).click();await page.waitForFunction(()=>window.__lastSave?.state.city.projects?.waterfront?.readyAt);const startedProject=await page.evaluate(()=>window.__lastSave.state.city.projects.waterfront);assert.equal(startedProject.siteId,fixture.state.buildings.find(b=>b.kind==='harbor').id);
 await page.evaluate(duration=>{window.__clockOffset=duration*1000+2000},before.quote.duration);await project.getByRole('button',{name:'Celebrate · +5 gems',exact:true}).waitFor();await project.getByRole('button',{name:'Celebrate · +5 gems',exact:true}).click();await page.waitForFunction(()=>window.__lastSave?.state.city.projects.waterfront.claimedStage===1);const claimed=await page.evaluate(()=>({state:window.__lastSave.state,bonus:window.__defense.SWCivicBonuses(window.__lastSave.state)}));assert.equal(claimed.state.gems,before.gems+5);assert.equal(claimed.state.city.projects.waterfront.stage,1);assert(claimed.bonus.voyageSpeed>0);await page.locator('[data-slot=dialog-close]').click();
 console.log('PASS real civic start/complete/claim, permanent bonus, single gem receipt and requirement-to-land navigation');
 const homeArmy=await page.evaluate(()=>window.__defenseHooks.snapshot().state.army);
 await page.locator('.sw-quick-nav').getByRole('button',{name:'City',exact:true}).click();await page.locator('.sw-city-dialog .sw-tabs').getByRole('button',{name:'Defense',exact:true}).click();await page.getByRole('button',{name:'Defend now',exact:true}).click();
 await page.waitForFunction(()=>window.__lastSave?.battle?.kind==='defense'&&window.__lastSave?.state?.activeBattle);const started=await page.evaluate(()=>window.__lastSave);assert.deepEqual(started.state.army,homeArmy,'defense reserved or removed the home army');
 // The whole battle snapshot survives reopening; the simulation must reproduce it exactly.
 await page.reload();await page.waitForFunction(()=>window.__defenseHooks?.snapshot().battle?.kind==='defense');const resumed=await page.evaluate(()=>window.__defenseHooks.snapshot());assert.equal(resumed.battle.id,started.battle.id);assert.deepEqual(resumed.input,started.input);assert.equal(resumed.state.activeBattle,started.state.activeBattle);assert.deepEqual(resumed.state.army,homeArmy);
 await page.evaluate(()=>{const h=window.__defenseHooks;h.advance(h.snapshot().forecast.duration)});await page.waitForFunction(()=>window.__defenseHooks.snapshot().result?.defense&&window.__lastSave?.state?.activeBattle===null);const settled=await page.evaluate(()=>window.__defenseHooks.snapshot());assert.equal(settled.state.city.raidCount,1);assert.equal(settled.state.city.raidSchedule.cycle,1);assert.equal(settled.result.defenseReport.id,started.battle.id);for(const key of ['towerDamage','wallDamageAbsorbed','wallDelaySeconds','attackersDefeated'])assert(Number.isFinite(settled.result.defenseReport[key]),'Missing measured '+key);assert(await page.locator('.sw-defense-report').count());for(const [width,height] of [[393,760],[430,800],[840,360],[740,320],[932,430],[874,409]]){await page.setViewportSize({width,height});await page.waitForTimeout(70);const bounds=await page.locator('.sw-result-content').evaluate(e=>{const r=e.getBoundingClientRect(),body=e.querySelector('.sw-body').getBoundingClientRect(),detail=e.querySelector('.sw-defense-report .sw-muted').getBoundingClientRect(),button=e.querySelector('.sw-result-footer button').getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,w:innerWidth,h:innerHeight,detailBottom:detail.bottom,bodyBottom:body.bottom,buttonBottom:button.bottom}});assert(bounds.x>=0&&bounds.y>=0&&bounds.right<=bounds.w&&bounds.bottom<=bounds.h,'Defense result clipped '+JSON.stringify(bounds));if(bounds.detailBottom>bounds.bodyBottom+1){await page.screenshot({path:'/tmp/sw-defense-clip.png'});console.log(await page.locator('.sw-result-content').evaluate(e=>[...e.querySelectorAll('.sw-body,.sw-result-overview,.sw-result-summary,.sw-defense-report,.sw-defense-metrics,.sw-defense-report .sw-muted,.stars,.result-stats,.victory-loot')].map(n=>({class:n.className,rect:n.getBoundingClientRect().toJSON(),display:getComputedStyle(n).display,gap:getComputedStyle(n).gap,padding:getComputedStyle(n).padding,minHeight:getComputedStyle(n).minHeight,grid:getComputedStyle(n).gridTemplateColumns}))))};assert(bounds.detailBottom<=bounds.bodyBottom+1,'Protected storage line hidden '+JSON.stringify(bounds));await page.screenshot({path:'/Users/chrismozer/Library/Developer/Stonewake-review/build11/interface/defense-result-'+width+'.png'})}await page.setViewportSize({width:932,height:430});assert.deepEqual(settled.state.army,homeArmy);assert.equal(settled.reports.filter(r=>r.id===started.battle.id).length,1);const baseline=JSON.stringify({gems:settled.state.gems,city:settled.state.city,reports:settled.reports});
 await page.evaluate(async()=>{const finish=window.__defenseHooks.finish;await Promise.all([finish(),finish()])});await page.waitForTimeout(100);const duplicate=await page.evaluate(()=>window.__defenseHooks.snapshot());assert.equal(JSON.stringify({gems:duplicate.state.gems,city:duplicate.state.city,reports:duplicate.reports}),baseline,'duplicate finish applied defense rewards/reports again');
 const report=settled.reports.find(r=>r.id===started.battle.id),raw=await page.evaluate(input=>{const {frames,...result}=window.__defense.Kl(input);return result},started.input);assert.equal(report.result.won,raw.won,'defense report uses inverted attacker result');assert.equal(report.result.destruction,raw.destruction,'defense report labels intact city as destruction');
 await page.getByRole('button',{name:'Return to your capital',exact:true}).click();await page.getByRole('button',{name:'Kingdom menu',exact:true}).click();await page.getByRole('button',{name:'Reports',exact:true}).click();const card=page.locator('.report-card').first();await card.waitFor();assert((await card.innerText()).includes(raw.won?'Defeated':'Held'),'report label is reversed');await card.click();await page.waitForFunction(()=>window.__defenseHooks.snapshot().replay);await page.evaluate(()=>{const h=window.__defenseHooks;h.advance(h.snapshot().forecast.duration)});await page.waitForFunction(()=>window.__defenseHooks.snapshot().result);const replay=await page.evaluate(()=>window.__defenseHooks.snapshot());assert.deepEqual(replay.state.city,settled.state.city,'replay settled defense twice');assert.equal(replay.state.gems,settled.state.gems,'replay granted more gems');assert.equal(replay.reports.length,settled.reports.length);
 assert.deepEqual(errors,[],'page errors');console.log('PASS Build 11 defense starts through UI, preserves home army, resumes exact snapshot, settles once, reports correct outcome, and replays without rewards',{battleId:started.battle.id,won:settled.result.result.won,raidCount:settled.state.city.raidCount});
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
